### ISSUE TITLE
Multi-World?

### ISSUE THREAD

**Issue by saltstorm** [benbaptist/minecraft-wrapper#101]
Is it possible to have multiple worlds like multiverse (bukkit plugin).

**Comment by suresttexas00** [comment]
I'll let those more into the development of this chime in on whether this is possible, but I will say this:

You are probably better off creating a small "Hub" instance (running wrapper) that does all the on-line mode True validation, then player.connect() them to off-line Wrapper worlds.  When they "leave" that world, kick them, sending them back to the hub world.  The hub world could have a very small world border and use a "small" amount of memory like java -xmx512M.

Multiworld might seem like a great idea, but I know it gives me fits on my craftbukkit worlds.  I have all sorts of compatibility issues between other plugins.  It was so bad on my factions world and the massivecore plugin that I did actually get BungeeCord instead and made the factions world a different server, with it's own plugins.

**Comment by TomSharratt** [comment]
I would prefer having 2 servers than 2 worlds but I need both in online mode...

**Comment by suresttexas00** [comment]
I guess I will say this too.. It is probably possible to "wrapper" a bukkit instance... ?? kind of defeats what wrapper is intended to be, though.

**Comment by TomSharratt** [comment]
The reason I'm using the wrapper in the first place is for the vanilla jar :P

**Comment by suresttexas00** [comment]
FYI, I am talking about using 3 worlds:  HUB world, which is online and does all the "online" validation.
world1 and world2 are the "multiworlds" which operate in offline and can only be accessed by the HUB world (their ports would not be exposed to the internet).

**Comment by suresttexas00** [comment]
If you used the HUB world, I don't see why the other two would have to be online.

**Comment by TomSharratt** [comment]
I understand that, but won't peoples skins be broken in the offline 'worlds' (servers)?

**Comment by suresttexas00** [comment]
well, that part I don't know.. since the wrapper proxy mode already does this, are their skins broken now?

**Comment by suresttexas00** [comment]
You should try it out and see first.

**Comment by TomSharratt** [comment]
Just tried it. The skin doesn't seem to break however the tab list has me in it twice, once with my skin and once with the default skin.

**Comment by suresttexas00** [comment]
very interesting.

**Comment by suresttexas00** [comment]
"The reason I'm using the wrapper in the first place is for the vanilla jar :P"
Yep!

**Comment by suresttexas00** [comment]
yea, I got tired of every update making my server obsolete unless I wanted every plugin broken until the new versions got updated.  Even now, I notice that craftbukkit/spigot builds do not quite fully replicate vanilla behaviors or or broken entirely, especially with some commands like "spreadplayers" (Which I use in some of my bukkit command blocks).

**Comment by TomSharratt** [comment]
Yeh the connect is very buggy, it has made me crash a couple times etc.

**Comment by TomSharratt** [comment]
Ideally, while connect() is so buggy, having 2 worlds on 1 server would be perfect for me.

**Comment by suresttexas00** [comment]
That would, I'm guessing, require modifying the Jar we so love... I think getting the bugs worked out  and creating a more robust player.connect is the only way this will happen.

**Comment by suresttexas00** [comment]
maybe someone should mosey on over to the spigot site and see how their sourcecode handles this...

**Comment by suresttexas00** [comment]
if your have a plugin determine which of the skins are the duplicate "steve skins", you could send a packet to hide the steve skins from the tab lists of every online player #68.  However, you have to send this packet to every player that logs on, every time they log on, for all the steve skins currently logged on.

question:  What happens when a second player comes on?  Do you see 4 players in the tab, or does only each player see their "second" instance? (the tab list is a client list)

I'm guessing the second is generated by the second login and will not be seen by other players.

**Comment by suresttexas00** [comment]
if you have your plugin(s) determine which of the skins are the duplicate "steve skins", you could send a packet to hide the steve skins from the tab lists of every online player #68.  However, you have to send this packet to every player that logs on, every time they log on, for all the steve skins currently logged on.

**Comment by suresttexas00** [comment]
If the steve skin in the tab list is the one created by the second server instance, your skins might be broken after all and you just can't see it (but other players will see it's broken).
