### ISSUE TITLE
Command Block Bug

### ISSUE THREAD

**Issue by saltstorm** [benbaptist/minecraft-wrapper#104]
Command Blocks don't save their contents, pretty big bug.

**Comment by suresttexas00** [comment]
Mine works fine.. is this using the hub server to another server instance we were discussing?

**Comment by saltstorm** [comment]
This is a stand-alone server, nothing unusual. What version are you running?

**Comment by suresttexas00** [comment]
I always run the most recent build... currently 77 i believe..

**Comment by suresttexas00** [comment]
My worlds all have command blocks and I never had an issue...  I can't think of anything in wrapper that would interfere with this.. If you have any running plugins, the problem could be there, especially if they are trying to cancel mine events and stuff.

**Comment by suresttexas00** [comment]
I just tested it right before i replied.

**Comment by saltstorm** [comment]
Strange, i'll test it again.

Also, have you ever been kicked for IndexOutOfBounds exceptions before? I've had it a few times when a friend of mine logs off the server (the same friend, doesn't seem to do it with anyone else).

**Comment by saltstorm** [comment]
Im not saying the commandblocks dont work, i'm saying if you type a command in one, it doesn't save. At least not for me

**Comment by suresttexas00** [comment]
I know what you meant.  That's the part i just verified.

**Comment by suresttexas00** [comment]
Try stopping all your plugins, run just wrapper without them and see if the problem exists then.

**Comment by suresttexas00** [comment]
aside from the obvious.. being opped AND in creative mode.

**Comment by saltstorm** [comment]
Yeah................................. I had command blocks disabled in the server.properties (I forgot I redid them earlier).

**Comment by suresttexas00** [comment]
Would the command blocks still run with it set like that??  I thought that disabled them entirely..
