### ISSUE TITLE
How to delete an item from a json container

### ISSUE THREAD

**Issue by suresttexas00** [benbaptist/minecraft-wrapper#105]
OK, I am writing a mail plugin and there is a `self.mail = self.api.getStorage("mail", True)` container in it.  The container then contains a UUID object for each player.  Each UUID has its own "inbox".  Each inbox has username categories/objects, that contain the messages from each respective player.

So my goal is to delete the messages from a specific player _fromplayer_

So, i cycle through the "inbox" contents by:
```
				for x in self.mail[uuid]["inbox"]:
					if fromplayer in self.mail[uuid]["inbox"]:
```
So I could delete messages from _fromplayer_ by:
```
self.mail[uuid]["inbox"][fromplayer] = {}
```

However, what I actually want to do is delete the whole _fromplayer_ entry, without deleting mail from other players... How do you do that?

**Comment by saltstorm** [comment]
Can you paste the stuff JSON structure?

**Comment by suresttexas00** [comment]
```
{"4f953255-6775-4dc6-a612-fb4230588eff": {"flag": "Y", "inbox": {"Minecraftboy2019": "{}-Hey........ Man,... I need some wood! \n", "[CONSOLE]": "{}-hey folks! time for a weekly weebly update!!! \n"}, "humanname": "SurestTexas00"}, "54880482-2b03-47e5-a268-8290fd1e0b46": {"flag": "Y", "inbox": {"[CONSOLE]": "{}-hello players!  Welcome to the new mail system! \n-the mail system is now operational. \n-check our website for new rules tic.weebly.com \n-hey folks! time for a weekly weebly update!!! \n", "SurestTexas00": "{}-hello d00d, i saw your mammy the other day \n-hello d00d, i saw your mammy the other day \n-hello d00d, i saw your mammy the other day \n-yo my n***, whats up? \n"}, "humanname": "Minecraftboy2019"}}
```

**Comment by suresttexas00** [comment]
kind of curious why it is prefixing the first message with {} too... probably my plugin code...?

do i need to do 
`self.mail[uuid]["inbox"][fromplayer] = {}`
or can I just 
`self.mail[uuid]["inbox"][fromplayer] = ""`
when i am establishing a new level of stuff?

**Comment by suresttexas00** [comment]
the way it works is that the players arguments are used to look up the human name, get the corresponding UUID mailbox (only want mail to be able to sent is player has been on with that name). then the UUID is used to key to the "inbox", where the message is deposited.  Each players mail is deposited in the UUID "inbox" under their username, which is how the receiving player sees the messages titled under.

**Comment by suresttexas00** [comment]
I don't want playernames with no message cluttering the "inbox".

**Comment by suresttexas00** [comment]
I want the ability to delete messages from individual players.  Currently, I CAN do a clear of the whole mailbox as the only way to clear the clutter:
`self.mail[uuid]["inbox"] = {}`

**Comment by saltstorm** [comment]
You should make inbox an array.

**Comment by suresttexas00** [comment]
but can i store that in the self.storage?

**Comment by saltstorm** [comment]
A JSON array? Do you know how JSON works?

**Comment by suresttexas00** [comment]
was the first sentence a question?

**Comment by benbaptist** [comment]
Does Del work?

del self.whatever.blah["etc"]

**Comment by suresttexas00** [comment]
did not know about that.. ill try it! ...are you taking any shortcuts there... ?  I can use it just like you stated?

**Comment by benbaptist** [comment]
I was just wondering if you tried that yet - I think that'll work. It
deletes it completely.

**Comment by saltstorm** [comment]
Yes, del is what he is looking for, but he should probably change index to an array e.g:

"inbox":[{"from": "notch", "message":"hi!"}, {"user": "_jeb", "message": "hi!"}]

then iterate the inbox array, check if it is the one you want to delete then "del"

**Comment by suresttexas00** [comment]
that works perfect.  what's wrong with my current setup?

**Comment by saltstorm** [comment]
you're using an object like an array.

**Comment by suresttexas00** [comment]
I'm too much of a noob to know what that means... or why it is a problem. I know one difference, is that each player can have multiple messages under the same player:
"inbox":[{"from": "notch", "message":"hi!""message":"hi there""message":"hi again!"}, {"user": "_jeb", "message": "hi!"}]

**Comment by suresttexas00** [comment]
I guess I tend to think of arrays as a grid or cube, etc (x, y, z), which is not the structure I wanted.

**Comment by suresttexas00** [comment]
No... I know next to nothing about json.

**Comment by saltstorm** [comment]
We're talking about 2 'things' here: An Inbox and a Message.

The Inbox is literally just a list of messages (array).
A message contains the message and some info about it (object).

So for example:

"inbox": [
    {"sender": "notch", "message": "This is the message sent from notch", "timestamp": "00-00-00 00/00/00"},
    {"sender": "notch", "message": "This is another message sent from notch", "timestamp": "00-00-00 00/00/00"},
    {"sender": "_jeb", "message": "This is the message sent from jeb", "timestamp": "00-00-00 00/00/00"},
    {"sender": "notch", "message": "This is something sent from notch", "timestamp": "00-00-00 00/00/00"}
]

So with this you can then easily iterate through the array like so:

for message in self.player.mail["inbox"]:
    if message["sender"] == "notch":
        # do what you want with that message.

**Comment by suresttexas00** [comment]
That's what I am doing.  The inbox part is
`"Minecraftboy2019": "{}-Hey........ Man,... I need some wood! \n", "[CONSOLE]": "{}-hey folks! time for a weekly weebly update!!! \n"}`

```
                for message in self.mail[uuid]["inbox"]:
                    if "Minecraftboy2019" in self.mail[uuid]["inbox"]:
                             #read or delete a message:
```

**Comment by suresttexas00** [comment]
The above is suresttexas00 accessing his mailbox to do something with the block of messages from minecraftboy2019 (subcommand2)..

`/mail read Minecraftboy2019`

**Comment by suresttexas00** [comment]
I can see it's a little more flexible that way, especially if I want something other than just he raw massages in the container.
