### ISSUE TITLE
proxy does not pass ban reason through

### ISSUE THREAD

**Issue by suresttexas00** [benbaptist/minecraft-wrapper#109]
When you ban a player and they attempt to login, their connection attempt hangs and they never see the console message below:

```
{},legacy=false] (/127.0.0.1:61462): You are banned from this server!
Reason: hacking  by SurestTexas00
[02:09:10] [Server thread/INFO]: com.mojang.authlib.GameProfile@50c5cb06[id=************************************************,name=******,properties={},legacy=fals
e] (/127.0.0.1:61462) lost connection: You are banned from this server!
Reason: hacking  by SurestTexas00
```

Upon the initial ban, all the player sees is a ban with no reason:
![image](https://cloud.githubusercontent.com/assets/10001762/5890730/c076eca6-a437-11e4-88a6-400913bd17fe.png)

**Comment by suresttexas00** [comment]
If kicked with a reason given, the kicked player WILL see the reason he was kicked.
![image](https://cloud.githubusercontent.com/assets/10001762/5893959/6642609c-a4c5-11e4-9742-571ccb040839.png)

**Comment by benbaptist** [comment]
This isn't a Wrapper bug AFAIK - VANILLA minecraft doesn't like ban reasons
for some reason, despite allowing you to set a reason.

**Comment by suresttexas00** [comment]
At least with the vanilla,  I do get a reason if it try to log back in..
![image](https://cloud.githubusercontent.com/assets/10001762/5894371/7ba85ce4-a4d3-11e4-9887-d5b0c195a67b.png)

**Comment by suresttexas00** [comment]
When I do this with wrapper, it just hangs and never connects

**Comment by benbaptist** [comment]
Oh, I wonder if maybe the new line is the issue.

**Comment by benbaptist** [comment]
Okay, I believe that I fixed this issue. Should be good in build #79.

**Comment by suresttexas00** [comment]
Yes, does not give reason on the initial ban, but it does tell them when they try to log back on.
