### ISSUE TITLE
MOTD parsing is broken.

### ISSUE THREAD

**Issue by saltstorm** [benbaptist/minecraft-wrapper#110]
https://github.com/benbaptist/minecraft-wrapper/blob/481b2940db33e557aac94d97633cfac4bed0d364/src/proxy.py#L281

The MOTD works when it uses the § charactar, however this gets converted by the minecraft server after the first load. After that the MOTD is output as a raw string with no formatting taking effect.

Is there a special format I should be using for my MOTD instead of standard vanilla or is this broken?

**Comment by saltstorm** [comment]
In addition to this, could you add an event there so we can customize the MOTD from our plugins.

**Comment by suresttexas00** [comment]
This MOTD works on mine:
motd=&6&k00000&r &1The Imagine Craft Vanilla 1.8.2 pre-4 &6&k00000

**Comment by benbaptist** [comment]
Yup, Wrapper.py takes & instead of the double dollar symbol.

**Comment by suresttexas00** [comment]
I think the vanilla and CB/Spigots, etc have too. I have always used the ampersand.

**Comment by saltstorm** [comment]
Doesn't work for me :s
![](http://puu.sh/f0Uex/8a4fd28e6c.png)

**Comment by suresttexas00** [comment]
what are you intending that to produce? (why the "CR")

**Comment by saltstorm** [comment]
&9 is the colour code, CR is just the text that should be blue

**Comment by saltstorm** [comment]
motd=&9Minecraft Server

Just tried it and it doesnt work.

**Comment by saltstorm** [comment]
Alright, It is not working because I'm using an older version of the Wrapper because the newest version has that disconnection bug.
