### ISSUE TITLE
Idea: send payload as event result.

### ISSUE THREAD

**Issue by saltstorm** [benbaptist/minecraft-wrapper#113]
Being able to send a payload as an event result would be very useful..
e.g:
prelogin -> {"cancelled": True, "reason": "the message why you were not allowed to login"}

**Comment by benbaptist** [comment]
I've essentially implemented the basis for this now in the latest builds, so I'll close this now. However, I do still need to implement more events that will support this new system later on. e.g. the prelogin event won't respond to this yet.
