### ISSUE TITLE
Disconnected when opening inventory in gamemode 1

### ISSUE THREAD

**Issue by tomsharratt** [benbaptist/minecraft-wrapper#114]
Title says it all.

When I open an my inventory while in gamemode 1 (creative) I get disconnected.

**Comment by suresttexas00** [comment]
I can't duplicate this error... is there anything special in your inventory?? I know there is a bug with certain written books that kick you when you open them... not sure if it only happens in wrapper, but it WAS on my production wrapper server where it was happening.

**Comment by saltstorm** [comment]
Yep, i've got books in my inventory.
I also get disconnected sometimes when opening it... Infact, now I think about it, you also get an error when you try save a very long command into a command block. Normally, vanilla disconnects you but when you log back on the commandblock has saved the long command, but with the wrapper it doesn't.

So i'd assume it is something to do with the compression threshold not working properly and causing out of bounds exceptions?

**Comment by suresttexas00** [comment]
interesting because the offending books were over 40+ pages (one of my players "journals")

**Comment by suresttexas00** [comment]
I wonder if this is "wrappers" bug or minecraft's?

**Comment by saltstorm** [comment]
definitely the wrapper.

I know if you type a super long command into a command block you get disconnected normally but it does save the command, with the wrapper it doesn't.

**Comment by suresttexas00** [comment]
it could be from malformed Json - maybe the wrapper does not handle json properly after a certain byte length?  I was reading that malformed json disconnects client and server
```

Packet ID	State	Bound To	Field Name	Field Type	Notes
0x02	Play	Client	JSON Data	Chat	Limited to 32767 bytes
Position	Byte	0: chat (chat box), 1: system message (chat box), 2: above action bar
 Warning.png Malformed JSON will disconnect the client```

**Comment by benbaptist** [comment]
I still need to test saving long command blocks, but I generally haven't had any issues with books. I tried writing 40 page books, going in and out of creative mode while opening the inventory, clicking on them, reading them, etc. and nothing ever happened. I even keep a book in me on my Wrapper development server and have had it in there for over a week now and I've still not had any disconnections. I keep one book in my hotbar and one in the top.

**Comment by suresttexas00** [comment]
I had one player that I had to take her book from here because it would kick her.  At the time, it did not equate the possibility that it was wrapper-related, So I did not save it.  Backups were not working at the time, so I can't get it back.  maybe I'll have her write another one! :D

**Comment by benbaptist** [comment]
heh dang

**Comment by benbaptist** [comment]
This bug is more than likely fixed with the recent patches in build 101. Closing.
