### ISSUE TITLE
how again to get another players dimension?

### ISSUE THREAD

**Issue by suresttexas00** [benbaptist/minecraft-wrapper#115]
Not the `player.getDimension()` , but `getDimension("someotherplayer")`

All I am getting are "global name api not defined", "no instance of ..", etc for every variation I am trying....

**Comment by saltstorm** [comment]
`otherplayer = self.minecraft.getPlayer("someotherplayer")
otherplayer.getDimension()`

**Comment by suresttexas00** [comment]
thanks.. I tried `tplayerobj = self.api.minecraft.getPlayer(targetplayer)` , but it got mad at me for that too.

**Comment by suresttexas00** [comment]
This worked, FYI.  Thanks
