### ISSUE TITLE
Help menu improvements

### ISSUE THREAD

**Issue by suresttexas00** [benbaptist/minecraft-wrapper#121]
1) Users should not be able to see any items for help group "wrapper".. I think the most logical way to deal with this (and solve issue #99) is to make the permission nodes for the wrapper commands or a single permission node just for the help "wrapper.seehelp" (and just let the is isOp() criteria continue to operate the actual permission).

2) help groups where the user has no permissions simply display: 
`---Showing help page 1 of 1 ---`
Where there are no items, it should display "You can't use this plugin!" or "there are no items to display!"
preferably, maybe those plugins won't show on the list for that user...

3) The main help groups are still Bold... did you want that or did you miss that one?  I personally think it looks better without, but I can live with it in the main groups.

**Comment by benbaptist** [comment]
1. Good idea.

2. Yeah, I still need to fix some weird quirks with the menus. I know that sometimes it'll also show a Page 2 that's available, but when you try to do it, it shows nothing else. 

3. I'll have to investigate that one - I generally enjoy making things pop out more with bold but I'll have to see the differences myself. I thought I actually did change something related to bold recently, though. Maybe that was the help command menus themselves.

**Comment by suresttexas00** [comment]
3), yes ... you removed the bolding from the menus themselves.  I think the gold color does pretty well sans bolding.
2), yea, I had noticed the second page thing.
