### ISSUE TITLE
How to abort a chat

### ISSUE THREAD

**Issue by suresttexas00** [benbaptist/minecraft-wrapper#123]
Tried to abort a player.message event with this code.  It does not work... I.e. returning false does not stop the chat from going out:

![image](https://cloud.githubusercontent.com/assets/10001762/6054558/09f85ef4-acbd-11e4-9b0d-1b14af4f37a2.png)

Code:
```
	def playerMessage(self, payload):
		player = payload["player"]
		hisuuid = str(player.uuid)
		if self.playerdata[hisuuid]["muted"] == True: 
			player.message("No one can hear you.. You are muted")
			return False
		else:
			return True
```

**Comment by benbaptist** [comment]
Just change player.message to player.rawMessage (this includes commands).

**Comment by suresttexas00** [comment]
OK.. thanks.  Once again, even though it was more expansive than what i originally intended, this actually worked much better since I can also mute the commands that a muted person should not have access to... :D
