### ISSUE TITLE
Name changes are HERE..

### ISSUE THREAD

**Issue by suresttexas00** [benbaptist/minecraft-wrapper#126]
And so is my first OH CRUD!  I just had a user who was UUID.. XXX123.  Well, the proxy mode, based on username assigns a UUID of XXX345.  So now, my user changed her name, and logs back in on UUID XXX123.  However, the Proxy now generates a UUID based on the New name, XXX998.  

WHOOPS!  Where's my stuff?  Its me "oldUser" .. i used to have a house by the village near a savannah...

D:

**Comment by suresttexas00** [comment]
I'm not even sure what the problem is.  I just know she changed here name and came back on and was treated as a new player.  I knew it was her...  The login data reflected the same UUID and from the same login IP.

**Comment by suresttexas00** [comment]
This is a bummer because I don't know which of the hundreds of UUIDs is her old one.  I

**Comment by benbaptist** [comment]
Damn. I was just waiting for a name change bug. I was scared it wouldn't work well - it's impossible to test since Mojang never gave us any real tools to help test it out. Is her username the same? It should be - I made it fallback to using the first username they had.

**Comment by suresttexas00** [comment]
Here is what has happened.  player name is "foxy" with offline uuid of XX1.  She changes name to "ImmaFox" and wrapper changes/creates the new offline UUID XX2... and then DELETES XX1...  so I used the offline vanilla jar to convert the "foxy" name into a XX1, pulled the most recent backup containing XX1 and I am going to rename it to XX2 so she can get her stuff back.

**Comment by suresttexas00** [comment]
my plugins, which I fortuitously decided to index data by UUID's have done fine :D ... all data stored by the on-line UUIDS from player.uuid.  Very happy about that.

**Comment by suresttexas00** [comment]
No, her username is now the new one mojang provided.  I have to check whether her /home actually worked.. she was "lost" and wanted to get home.. not sure if she actually tried to do /home.

**Comment by suresttexas00** [comment]
maybe trying to force the old name was what caused this.. I think the proper way to do this (again, no idea how you handle presently) is when a UUID logs in, create the new UUID hash and then compare it to any associated off-line name and it's HASH/UUID.  If they don't match, rename the old offline.dat to the new_offline.dat

**Comment by benbaptist** [comment]
yeah, I should probably just do that. I'm a bit worried about other stuff like the server's ban list and whatnot. For now, I would like to fix it to use the old username, and then eventually in an update, I'll implement .dat renaming and go through all of Minecraft's vanilla files and fix scoreboards and such.

**Comment by suresttexas00** [comment]
I don't think you need to do anything other than get the Dat renaming going... the ban list runs off UUIDs in the banned-players.json.  I would not try to force an old username down on the system.  I'm pretty certain if you just rename that .dat file for the user that changes his name, the minecraft jar will handle the scoreboards and stuff just fine.

**Comment by suresttexas00** [comment]
i verified that my player WAS still able to use her home that she set before the name change.. my routine simply got her current UUID, which matched the old one, looked up the home coords for that UUID, and proceeded to chug her right over to her old home!

**Comment by benbaptist** [comment]
but the UUID's in banned-players is based off of the server's offline mode UUID, because everything in the server uses that incorrect offline-mode UUID. I might also implement a ban/whitelist system into the wrapper itself as this is all handled by the server right now. 

Also, awesome!

**Comment by suresttexas00** [comment]
Yea, it seems the bans are incorrect.. I mean, they work for the offline mode, but if someone changed their name, they would get a new lease on life....  I can work around that and keep a ban list in my plugin, like I do with homes.. and if someone gets back on with new username, re-HAMMER them under the new name automatically

**Comment by suresttexas00** [comment]
The loss of inventory and XP is the more critical item because it is going to come up more frequently than ban dodgers...

**Comment by suresttexas00** [comment]
maybe during the .dat file comparisons, search the banned-players.json for any bans on the old name and if so, update the UUID in the bans file too.

**Comment by suresttexas00** [comment]
from what my player tells me, she has to wait 2 months to change it back (if she wants to).

**Comment by benbaptist** [comment]
Alright, I just pushed a fix for this. However, this fix won't roll her back, as it's probably already overridden the Wrapper's entry of her old name. If you want to fix this, go into wrapper-data/json/proxy-data.json and search for her new name. Replace it with her old name, and it'll start logging her in as that.

Also, as a fun little trick, you can use this to change your own/other people's names permanently. Your skin will remain, but you'll actually be genuinely logged in as a different username, inventory and all. 

Hope this fixes it!

**Comment by suresttexas00** [comment]
So....This is still using the online UUID to verify who they are and then just making them use the last name they logged in with ?

**Comment by suresttexas00** [comment]
1) Is there a wrapper command to get the players offline UUID?
2) How does one use that little "trick"?

**Comment by suresttexas00** [comment]
OK, about the code, Line 376 of proxy.py does this:

`					if not newUsername == self.username: `

Is there a reason you don't simply:
`					if newUsername != self.username: `

I ask because I have noted, during the course of writing my plugins, that sometimes this does not return the expected results.  sometimes this statement gets treated like:
`					if (not newUsername) == self.username: `

in some cases, I have to do things like `if not (newUsername == self.username):` to get the output I expected.  It seems to be a spurious behaviour, but I would swear this is happening sometimes. An example (that I had to fix) is this line from the getrawmessage for muted players:
```
				if (comm == "/msg") and (comm2 == jrmodName): 
					return True
```
I had to use those parenthesis to force it do interpret it the way I 'meant'.

**Comment by benbaptist** [comment]
Woah. I seriously had no clue that != was valid syntax in Python. Earlier on when I first started python years ago, I remember failing to get `if stuff != things` working like I could in other languages, since it syntax error'd out. I have no clue why, but it was ingrained into my head to use `if not stuff == things` instead. I guess I'll have to start doing != now. 

The trick I was referring to was how you could edit that file that I mentioned above to fix your player's changed name. It can be used to permanently change anyone's name on your server when they log in. :P

**Comment by benbaptist** [comment]
Oh, also, player.client.serverUUID should be the player's offline UUID. And yes, Wrapper is just forcing them to login with their oldest username (or the one the Wrapper has on record). Eventually I'll implement the fancy code, but for now, this is my fix.

**Comment by suresttexas00** [comment]
I actually did modify the file.. I searched wrapper-data/json/proxy-data.json file for my own usename, edited it to a nickname I wanted.. and now I am a different person! :)   However, I had to turn wrapper off while I made the edit because it kept over-writing the file... I was looking for a "live" way to do that.

**Comment by suresttexas00** [comment]
The magic of google :P

**Comment by suresttexas00** [comment]
OK, I had a couple more name changes and guess what..?  I actually like this system! If you do eventually create a permanent fix, can there be an option to use this offline method instead?  I have found it quite handy!  Please keep this option open while you implement the new code!

**Comment by benbaptist** [comment]
Sure! How about something like proxy-preserve-old-names in wrapper.properties? And maybe I'll throw in some name-changing APIs or something. Perhaps with the client.login event (or whatever it's called), you could return an object containing a different name, thus changing their name.

**Comment by suresttexas00** [comment]
Sounds good.

**Comment by suresttexas00** [comment]
After I ran the last version (96/97) briefly.. I noticed that my one player's "local" name went away and the server started using the Mojang name.... Did you do something here to cause that?

**Comment by benbaptist** [comment]
did it start working again after you downgraded?

**Comment by suresttexas00** [comment]
Yes, but I had to rename the player (with wrapper stopped) manually.

**Comment by benbaptist** [comment]
hmm. Did the whole json file get reset? was anyone elses' names reset?

**Comment by suresttexas00** [comment]
I'm about to restart without the name conversions... I missed the added config entry when I restarted the first time.  I think that default should have probably been false...

**Comment by benbaptist** [comment]
it should still use your old names though with that set to true - it only converts the player files and whitelist entries' UUIDs.

**Comment by suresttexas00** [comment]
I don't know... 
There were still lots of names there...   I had no whitelist entries

**Comment by suresttexas00** [comment]
I just have 1 player that ever changed her name.  The other one is my account

**Comment by benbaptist** [comment]
did your account continue to use your customized name?

**Comment by benbaptist** [comment]
I can tell you for sure right now, the UUID code in the Wrapper has hit rock bottom awful. It's so messy. So so so so soooooooooo messy. I think it works well, but who knows? It's messy as could be! I need to start organizing these chunks of the code into their own files to make this less horrible.

**Comment by suresttexas00** [comment]
Before you do any more upgrades, we should fix the existing issues.  I think this was a good build, but that default should have been False.
I have just tested it with False for the setting and it retains the old name.
