### ISSUE TITLE
I needs my fancy junk!

### ISSUE THREAD

**Issue by suresttexas00** [benbaptist/minecraft-wrapper#128]
The /src is still missing stuff from folder /html that should be there... I needs my fancy interface!

**Comment by suresttexas00** [comment]
All I think you need to do to fix this one is make sure your script/Gitignore is uploading those files to the /src as well as the wrapper.py

**Comment by benbaptist** [comment]
Yeah. I'm surprised that's still happening, I'll have to force it to commit soon.

**Comment by suresttexas00** [comment]
Closing this
