### ISSUE TITLE
How to make group inherit another group

### ISSUE THREAD

**Issue by suresttexas00** [benbaptist/minecraft-wrapper#131]
```
/perms groups jrmod new
/perms groups mod new
/perms groups admin new
/perms groups OP new

/perms groups OP set OP  (OP is just a node for some of the older plugins i made and will be removed)
/perms groups OP set broadcast.create
/perms groups OP set broadcast.delete
/perms groups OP set broadcast.modify


/perms groups admin set staff.ban

/perms groups mod set staff.gm3
```
How can I make the admin inherit the mod permissions and OP inherit admin (and mod)?

**Comment by benbaptist** [comment]
I don't know if I've implemented that yet - perhaps
```
/perms groups admin inherit mod  (it's toggle-able, so you can run this again to stop inheriting from mod)
/perms groups op inherit admin (will automatically inherit mod too)
/perms groups op inherit pizza (just another random group to inherit from)
```

would be a good way to implement it?

**Comment by suresttexas00** [comment]
Well, no rush, I was just seeing if I missed something.  It would be nice, but right now, I think we are more concerned about fixing the existing bugs/features.  i can just give the applicable group as needed.

**Comment by suresttexas00** [comment]
That would be the best way, I think (using the inherit subcommand).

**Comment by suresttexas00** [comment]
So in my example above, simply:
/perms groups OP set admin
/perms groups admin set jrmod

Pull and close for RC-2?
