### ISSUE TITLE
sending 0x07 packet

### ISSUE THREAD

**Issue by suresttexas00** [benbaptist/minecraft-wrapper#132]
what am I doing wrong here?

`self.minecraft.getPlayer(player.name).client.send(0x07, "varint|ubyte|ubyte",(1,0,1,"default"))`

![image](https://cloud.githubusercontent.com/assets/10001762/6139724/f7891476-b15c-11e4-8253-77a2b6fac2f6.png)

**Comment by suresttexas00** [comment]
Let me re-do that properly... I removed "string" from the units during my mad dash to try fixing it...
Here we go...
`self.minecraft.getPlayer(player.name).client.send(0x07, "varint|ubyte|ubyte|string",(1,0,1,"default"))`


![image](https://cloud.githubusercontent.com/assets/10001762/6139789/c30ce50a-b15d-11e4-89c7-28d2ce72464d.png)

**Comment by benbaptist** [comment]
I think the first field is supposed to be a regular int, not a varint. Otherwise, it looks perfect.

**Comment by suresttexas00** [comment]
Ohhhhhhhhhh... Thought varint was an int.. sorry.  OK!  I'll give that a shot.

**Comment by suresttexas00** [comment]
It worked.. and what a weird experience to be in the end, yet still in the overworld! :D .. just the first step, I know more is actually needed, but this is the method I am thinking of pursuing for dimensional switching...

**Comment by benbaptist** [comment]
Ahh. I played around with that earlier on when I was working on proxy mode - changing player dimensions visually, but still being in the regular world. Switching to the nether is great too.  :P

**Comment by suresttexas00** [comment]
I want to finish the process and make the changeover by
`To change the player's dimension (overworld/nether/end), send them a respawn packet with the appropriate dimension, followed by prechunks/chunks for the new dimension, and finally a position and look packet. You do not need to unload chunks, the client will do it automatically.'

**Comment by benbaptist** [comment]
They won't actually be in the new dimension, though. Even if you send the chunks and all, it'll only be client-sided. If they break a block, it won't work right. And they won't see the right people. It would be really glitchy and weird. :P

**Comment by suresttexas00** [comment]
ok, well it was a nice experiment

**Comment by suresttexas00** [comment]
So how does Bukkit do this?  The TP command (when a player is used as the target) works interdimensionally.  If player A is in the nether, TP <me> <playerA> will tp me to the nether...
