### ISSUE TITLE
two "auto-update-dev-build" in wrapper properties

### ISSUE THREAD

**Issue by suresttexas00** [benbaptist/minecraft-wrapper#134]
```auto-update-dev-builds = False```
...
```auto-update-dev-build = False```

**Comment by benbaptist** [comment]
I don't think that's a wrapper thing - if anything, I changed the name
across two different builds and it duped.  Are you sure you didn't add the
s by accident?

**Comment by suresttexas00** [comment]
No.. I never messed with that line ever.  I figured it was something like that because I have been through a few different build now.

**Comment by suresttexas00** [comment]
Just wanted to make sure.... So the 's' is not supposed to be there?

**Comment by suresttexas00** [comment]
Compare lines 9 and 88 of config.py... that is where the difference is.

**Comment by suresttexas00** [comment]
I guess the second line is now 85

**Comment by suresttexas00** [comment]
One has the 's' and the other does not.

**Comment by benbaptist** [comment]
Oh, okay. I edited it and should be in the latest release once I push that code.
