### ISSUE TITLE
Feature request - registerCommand

### ISSUE THREAD

**Issue by suresttexas00** [benbaptist/minecraft-wrapper#135]
1) Can you get the wrapper to not be case sensitive with commands? 
`if Thecommand.lower() == registeredCommand.lower(): DoTheCode`

2) also, is there a way to register multiple aliases without doing:
```
		self.api.registerCommand("sethome", self._sethome, None)
		self.api.registerCommand("sethm", self._sethome, None)
		self.api.registerCommand("seth", self._sethome, None)
		self.api.registerCommand("sh", self._sethome, None)

```

1) is more important than 2), though...

**Comment by benbaptist** [comment]
Are you sure commands should be case-insensitive? The vanilla server, bukkit/spigot, etc always used case-sensitive commands. Also, 2) is fixed in 97..

**Comment by benbaptist** [comment]
For now, I just went ahead and implemented both anyways in build 97.

**Comment by suresttexas00** [comment]
Well, in bukkit/spigot essentials /Home works the same as /home... I don't see why you would really want case sensitivity.. It IS there in vanilla, but.. 'VANILLA' LOL

**Comment by benbaptist** [comment]
Heh, I guess :P

Also, update incoming...
