### ISSUE TITLE
Python wrapper optimization

### ISSUE THREAD

**Issue by suresttexas00** [benbaptist/minecraft-wrapper#136]
Is there any configuration or adjustments/optimizations to ensure that wrapper/python/plugins don't become a source of lag?

**Comment by benbaptist** [comment]
Not that I'm aware of. The only thing I could think of is making sure on the server side, that network-compression-threshold is set to -1 in server.properties. It causes a lot of problems having it turned on, and since Wrapper.py already handles it, it should not be an issue.

**Comment by benbaptist** [comment]
I don't think there's really any need optimizations needed - Python is overall very light and easy to work with. The wrapper already is mostly bare bones as it is.

**Comment by suresttexas00** [comment]
` making sure on the server side, that network-compression-threshold is set to -1 in server.properties. It causes a lot of problems having it turned on`  ... A titbit, I knew not... ;)

**Comment by suresttexas00** [comment]
What about memory and stuff - like the way java needs options like Xmx2G Xms2G, etc...?

**Comment by suresttexas00** [comment]
So this is going to be OK when I start doing things like checking every block a player clicks and where he is when he does it, and logging the results, etc ,etc..?

**Comment by benbaptist** [comment]
Memory usage is dynamic in python - it doesn't have a set allocated amount
of melort.
