### ISSUE TITLE
Changing a playerRawMessage

### ISSUE THREAD

**Issue by suresttexas00** [benbaptist/minecraft-wrapper#137]
If a player types "/warp surest", which piece of code handles it first, the registered command "/warp" or the playerRawMessage event?

I tihnk the playerRawMessage would , but I want to be sure..?

**Comment by suresttexas00** [comment]
I am trying to implement a nickname system and I want it to substitute nicknames into real names before it is passed to the commands.

**Comment by suresttexas00** [comment]
Question answered, BUT.. I can't ("don't know how to..") return the modded text back to the wrapper.  The following code is intended to change the word "op" to "SurestTexas00" the two are are paired in the container ____________


```
	def playerRawMessage(self, payload):
		player = payload["player"]
		hisuuid = str(player.uuid)
		content = (payload["message"]).split(" ")
		if content[0].lower() != "/nick": #substitute for all commands/chats but "/nick"
			for conts in range(len(content)):
				for nick in self.playerdata[hisuuid]["nicks"]:
					if str(nick).lower() == str(content[conts]).lower():
						#substitute!
						content[conts] = self.playerdata[hisuuid]["nicks"][nick]
		#add even more stuff here - like removing nasty words, etc!
		if self.playerdata[hisuuid]["muted"] == True:
...
			player.message("Access denied. Only a mod can restore your access.")
			return False
		# put it back together for return
		returnedtext = " ".join(content)
		player.message(returnedtext)
		payload["message"] = "This doesn't work"
		return ("nor does this")
```

The text substitutes and such, but I can't pass it back:
![image](https://cloud.githubusercontent.com/assets/10001762/6216754/c90adf8a-b5da-11e4-8c59-32c561181953.png)

**Comment by suresttexas00** [comment]
```
		# put it back together for return
		returnedtext = " ".join(content)  #<- -This is already tested and returns the substituted text.
		payload["message"] = returnedtext  #<--This also works- does modify "payload["message"]"
		return payload      #<-------------------This does nothing but allow the passage of the original raw message
```

Is this what Tom saltstorm was referring to in #113 ?

**Comment by benbaptist** [comment]
Yup, and I really would like to improve the event system in that department. I'm not b

**Comment by benbaptist** [comment]
thanks for posting that without letting me finish, Github. Anyways, I'm not back home yet, but since I have nothing to do, I'm gonna install bluefish and try to do a little programming here on my laptop.

**Comment by suresttexas00** [comment]
Is there a workaround in the meanwhile (for my specific problem)?  Can i re-run the command "as" the user or something and return False to the original rawtext?

**Comment by suresttexas00** [comment]
which module of wrapper handles this?

**Comment by benbaptist** [comment]
I think that player.say will do precisely what you want it to. 
e.g. player.say("Ohai y'all!") or player.say("/help"). 

However, it must be noted that this will NOT have an effect on Wrapper's commands and whatnot - this will send it directly to the server jar.

**Comment by suresttexas00** [comment]
no, that won't ultimately work since the idea is to substitute command parameters for the plugin commands.. so if someone;
`/mail send op ohai dood` it would become
`/mail send SurestTexas00 ohai dood`

**Comment by benbaptist** [comment]
How come you're doing it that way though? Couldn't you just implement `if name == "op"` into your own mail plugin and have it substitute for the username?

**Comment by suresttexas00** [comment]
but then I have to do it from "every" single command and piece of code where i might want that substitution.  This is a nicer, simpler, place for it to happen.  I have over 10 commands (and growing) now that might use such substitutions...

**Comment by suresttexas00** [comment]
keep in mind that the real code is going to loop though a nickname container for each player, substituting his own personal nicks for other players and commands and such.. and it must do that in each place where a person may be referring to a nickname:
/Whereis thatdood
/tpto thatotherdood
/seen someguywhosNameImessUp

**Comment by suresttexas00** [comment]
I suppose I could create a substitution routine that each command would call first... It would work until you get this working.

**Comment by suresttexas00** [comment]
I wont be able to nick the actual commands (which would be highly useful) themselves though.  I would like to eventually have some more useful substitutions, like
`/r so how are you, pal?`
to
`/tell SurestTexas  so how are you, pal?`

**Comment by benbaptist** [comment]
Just got this implemented http://s.benbaptist.com/p4rt3

**Comment by suresttexas00** [comment]
Ok, not too bad... 8 commands with this as the first line now:
`args = self.globalset.substNicks(player,args)`

Which runs this:
```
	def substNicks(self, player, argsWillBeReturned): #args = self.globalset.substNicks(player,args)
		hisuuid = str(player.uuid)
		content = args.split(" ")
		#if content[0].lower() != "/nick": #substitute for all commands/chats but "/nick"
		for conts in range(len(content)):
			for nick in self.playerdata[hisuuid]["nicks"]:
				if str(nick).lower() == str(content[conts]).lower():
					#substitute!
					content[conts] = self.playerdata[hisuuid]["nicks"][nick]
		# put it back together for return  (this wont work until Ben Baptist upgrades to allow payload return
		returnedtext = " ".join(content)
		args = returnedtext
		return args
```

**Comment by benbaptist** [comment]
The plugin's code:

```class Main:
	def __init__(self, api, log):
		self.api = api
		self.minecraft = api.minecraft
		self.log = log
	def onEnable(self):
		self.api.registerEvent("player.rawMessage", self.playerMsg)
	def playerMsg(self, payload):
		return payload["message"].replace("op", "benbaptist")
	def onDisable(self):
		pass
```

I've implemented #113, so once I push the latest dev code, you'll be able to use this.

**Comment by suresttexas00** [comment]
wow.. fast :)

**Comment by suresttexas00** [comment]
As useful as it is, I;m not sure I will be using the .replace method though... would not want to see
`can you give me a hopper?` become `can you give me a hSurestTexas00per?` :D

**Comment by suresttexas00** [comment]
Cool, though... can't wait for the push..

**Comment by benbaptist** [comment]
LOL, all of the possibilities.

```
This sword is really benbaptist.
Can I be benbaptistped?
I need a benbaptist! I was griefed! 
```

**Comment by suresttexas00** [comment]
the way i set it up will do that, if there is not another character in it, ie.

Can I be op?
can i be op
can I be opped?

```
Can I be op?
can i be SurestTexas00
can I be opped?
```

**Comment by suresttexas00** [comment]
I seem to still have some problem:
![image](https://cloud.githubusercontent.com/assets/10001762/6219750/b151e7dc-b5fb-11e4-96de-f59999859968.png)

Plugin code:
```
		returnedtext = " ".join(content)
		payload["message"] = returnedtext
		player.message(payload["message"])
		return payload["message"]
```

Everything else is the same as your example, except that my event is called playerRawMessage, not playerMsg

**Comment by suresttexas00** [comment]
Why won't it return the new message?

**Comment by suresttexas00** [comment]
the first line is what I actually type and should be just like the second line, which is just a printout for debugging purposes.

**Comment by suresttexas00** [comment]
OK, found it.  Your code is expecting a string to be returned and my code is creating a list.  If I string it before returning it, it works:
```
		returnedtext = " ".join(content)
		payload["message"] = str(returnedtext)
```
