### ISSUE TITLE
Page counts

### ISSUE THREAD

**Issue by suresttexas00** [benbaptist/minecraft-wrapper#141]
Let's talk about this code and why it generates an extra "page" then the item-per-page limit is reached:
```
			def showPage(page, items, command, perPage):
				pageCount = len(items) / perPage
				if page > pageCount or page < 0:
					player.message("&cNo such page '%s'!" % str(page + 1))
					return
				player.message(" ") # Padding, for the sake of making it look a bit nicer
#				player.message("&2--- Showing help page %d of %d ---" % (page + 1, pageCount + 1))
				player.message({"text": "--- Showing ", "color": "dark_green", "extra":[
					{"text": "help", "clickEvent": {"action": "run_command", "value": "/help"}},
					{"text": " page %d of %d ---" % (page + 1, pageCount + 1)}
				]})
```

so lets say there are 4 items per page.  When you have 3 items, 3/4 = 0, so you compensate for this by `(page + 1, pageCount + 1)}` or similar...  However, when you get to 4; 4 /4 now = 1, so pagecount + 1 now results in '2'.. which is wrong and results in an extra null page.

I had similar situation in my code and I tried to deal with it by:
`if (int(len(items) / perPage))  != (len(items) / perPage): pagecount = pagecount + 1`

However, this won't work because everything is treated as integers by Python by default, so you must:
`if (int(len(items) / perPage))  != (float(len(items)) / perPage): pagecount = pagecount + 1`
having done so, you won't need the pageCount + 1 and the page count will always be correct.

**Comment by benbaptist** [comment]
Fixed in build 97.
