### ISSUE TITLE
!!  Eeek !!

### ISSUE THREAD

**Issue by suresttexas00** [benbaptist/minecraft-wrapper#142]
```
[16:10:05] [Wrapper.py/INFO] Server started
Error in the Client->Server method:
Traceback (most recent call last):
  File "Wrapper\proxy.py", line 543, in handle
    if self.parse(id) and self.server:
  File "Wrapper\proxy.py", line 438, in parse
    if player["uuid"] == str(self.serverUUID):
KeyError: 'uuid'
```

**Comment by suresttexas00** [comment]
No one can log in...

**Comment by benbaptist** [comment]
is this on the latest build?

**Comment by suresttexas00** [comment]
yep, the latest build. 97/96.. whatever it is LOL.

**Comment by suresttexas00** [comment]
Looks like it's happening in the whitelist area.  I commented that part out to get it working, but rolled back to build 94 just in case.

**Comment by suresttexas00** [comment]
I rolled back because it also looked like I am losing the "local" name feature I have come to enjoy.

**Comment by suresttexas00** [comment]
However, on the plus side, the web interface worked again, and better than ever.

**Comment by benbaptist** [comment]
Ohhhhh, I see. I suppose this is a result of damaged/weirdly formatted whitelist entries in the whitelist.json area. I have absolutely no error handling for that - if something is amiss, it'll instantly explode.

**Comment by benbaptist** [comment]
Also, you can turn this off with the convert-player-files option for now. I'm working on a fix.

**Comment by benbaptist** [comment]
I was able to get the custom usernames working - is that what you were referring to? http://s.benbaptist.com/VDB1t

**Comment by suresttexas00** [comment]
DId you push any new code?

**Comment by benbaptist** [comment]
Sorry, just pushed right now!
