### ISSUE TITLE
hasGroup() yielding "None" even though player has group

### ISSUE THREAD

**Issue by suresttexas00** [benbaptist/minecraft-wrapper#144]
plugin code
```
			comm2player =  self.makenamevalid(comm2, online = False, returnUUiD = False) # yields name.
			print(comm2player)
			#try:
			comm2playerObject = self.api.minecraft.getPlayer(comm2player)  #Yields object from username
			print(comm2playerObject.hasGroup("jrmod"))
```

results in the console output:
![image](https://cloud.githubusercontent.com/assets/10001762/6385922/fb8761fc-bd3e-11e4-92e1-1bbd2aaefae9.png)

although the player has that group:
![image](https://cloud.githubusercontent.com/assets/10001762/6385930/20c88838-bd3f-11e4-9803-cb40384b087b.png)

**Comment by benbaptist** [comment]
Fixed in build 97.
