### ISSUE TITLE
Capturing bed sleeping / right click

### ISSUE THREAD

**Issue by suresttexas00** [benbaptist/minecraft-wrapper#146]
Is there an event to see if a player right clicks a bed (or tells what object is being touched)?  player.place shows a none item (or whatever the player is holding).  Player.mount does not capture it either, even if it is night and the player goes to bed.

**Comment by benbaptist** [comment]
The problem lays in understanding the world. I don't know the world yet - I need to parse the chunk packets. Furthermore, once that's implemented, I will need to implement a system that removes said chunks from memory once they're out of reach, or else memory leaks will occur.

**Comment by suresttexas00** [comment]
Wow.. that sounds so meta-physical. LOL

**Comment by suresttexas00** [comment]
Well,, OK.  I guess this is not a priority.  I have always believed that one should do something well and better versus quick and shallow, so by all means take your time. :D

**Comment by suresttexas00** [comment]
I also thought this would have application to the //wand type systems since the right click under the player.place action does not actually select the block that is clicked, but rather, the block that faces the one that was clicked.  So, in your "worldedit" example, the selected area will be "off" a block, resulting misplacing a structure or selection (unless you happen be be aware of this nuance and select accordingly).

**Comment by suresttexas00** [comment]
So, on a bit of a tangent, since we are discussing the world:
1) are we able to create "fake blocks" that are only client-side visible?  For instance, to mark a boundary so the player can see the corners of a selection...
2) can we "restore" / "resync" / "refresh" a client's view (to remove the false blocks)?

**Comment by benbaptist** [comment]
Fake blocks are easy - all you need to do is formulate a block change packet. http://wiki.vg/Protocol#Block_Change

This MIGHT work: player.client.send(0x23, "position|varint", ((5, 80, 5), blockIDFormattedInTheWayThatTheAboveArticleDescribesBecauseIDontReallyKnowHowDoWorkWithBitwiseStuff))

Refreshing could be done by making your own chunk packets based off of what we've received from the server (e.g. the chunk packets and the individual block placements) and sending those back to the client to restore any glitched blocks.

**Comment by suresttexas00** [comment]
Yea, my attempt at that just gets me kicked.
http://wiki.vg/
is totally noob unfriendly
The article really does not say how to format it.

**Comment by suresttexas00** [comment]
If I did this:
```
player.client.send(0x23, "position|varint", ((payload["position"]), 0x85)
```
and got this:
![image](https://cloud.githubusercontent.com/assets/10001762/6429395/dbb646c2-bf9b-11e4-9976-3ca73a4ef604.png)

Would that help figure it out?  Attempted an Emerald Block.  Id 133 decimal 85 hex.

**Comment by benbaptist** [comment]
You're putting the position inside of a tuple. Provided position returns a tuple, you don't want to do that.

player.client.send(0x23, "position|varint", (payload["position"], 0x85))

**Comment by suresttexas00** [comment]
does your "position" type convert the three numbers to the "however-many-bit" integers that go there?
Did I do the second part right, or is it OK to just put decimal 133?

**Comment by benbaptist** [comment]
I don't think 133 is the right value - If I'm not mistaken, I think it works by just putting this in, replacing id and data with your block ID and damage/data value respectively.

``` id << 4 |  data```

So here's a working example (block 85 with 0 damage value):

```85 << 4 | 0 ```

and these bitwise operators formulate the special number. It'll probably be something in the thousands, as this generated 1360. Also, to make sure these numbers seem right, I read the 0x23 packet coming from the vanilla server itself, and it sent numbers very similar. 

However, despite this, it actually still gives me the same error that you encountered.

**Comment by benbaptist** [comment]
On another, completely unrelated note, I'm re-organizing a ton of code. __main__ currently contains a crapton of junk that shouldn't really be there - plugin handling, command handling, event handling, permissions handling, etc. so I'm splitting them off into individual files. 

```plugins.py
commands.py
events.py
```
It's really nice, and is a bit more sane for finding relevant code.

**Comment by suresttexas00** [comment]
Oh no!  :o ... can we get a good release first?

**Comment by benbaptist** [comment]
I've already done it :P that's why I haven't pushed anything recently - I didn't want to push any half-baked code. Also, it was getting annoying working on it with all the clutter, hence why I just decided to do it now and get it over with.

**Comment by suresttexas00** [comment]
Too bad, I was just getting used to the insanity.. :D

**Comment by suresttexas00** [comment]
well, I tried all sorts of stuff and nothing worked.  Once I understood what the bitwise notation meant, its pretty easy to do this without calculating too hard.  The item I am using is not 85,, but 133 (decimal) - emerald block, which is 85 in Hexidecimal.  As long as you are dealing with bitwise operations that are divisble by four, hex bit wise is easy.. just like multiplying by 10 in decimal.. just add 0 for every  4, two zeroes for eight... So we end up with 0x850, which is 2128 in decimal.

However, I think we have to do the same contorted crap to the 64 bit position, which is NASTY because 26 and 14 bits don't fit nicely into the 4 bit nibbles of a hex character...  I gave it a shot, but i don't really know...

Did someone say `Fake blocks are easy - all you need to do is ...`?

**Comment by suresttexas00** [comment]
I swear this packet stuff is worse than Json!

**Comment by suresttexas00** [comment]
Does this bitwise stuff like (133 << 4 | 0) even work in python?  seems like all these documents are java-based... and all the real world examples are java :(

**Comment by benbaptist** [comment]
Yeah, Mojang decided to make this 300% more difficult than it used to be
about three major versions ago... this all was indeed quite easy but it has
apparently gotten worse.

**Comment by suresttexas00** [comment]
I may have this figured out by the time you reply, but; "can I send raw data in the packet, like so:"
`player.client.send(0x23,0xCCCCDDDDEEEEFFFF8850))` or just
`player.client.send(0x23CCCCDDDDEEEEFFFF8850))`?

(0xCCCCDDDDEEEEFFFF being the coords and 8850 being the Varint of 0x850, the emerald block)

**Comment by suresttexas00** [comment]
I think I'm getting close:
Plugin code:
```
		if itemid == 271:
			p["sel2"] = payload["position"]
			coords = p["sel2"]
			player.message("&dPoint two selected.")
			x= coords[0]
			y=coords[1]
			z=coords[2]
			encodedposition = ((x & 0x3FFFFFF) << 38) | ((y & 0xFFF) << 26) | (z & 0x3FFFFFF)
			print encodedposition
			player.client.send(0x23, encodedposition, 0x8850)
			return False
```

Console output:
```
[15:56:35] [Server thread/INFO]: SurestTexas00 joined the game
942560637880100
[15:56:42] [Wrapper.py/ERROR] Plugin 'com.suresttexas00.plugins.simple' errored
out when executing callback event 'player.place':
[15:56:42] [Wrapper.py/ERROR] Traceback (most recent call last):
[15:56:42] [Wrapper.py/ERROR]   File "C:\Users\JRUSSELL\Desktop\vanilla\src\__ma
in__.py", line 139, in callEvent
[15:56:42] [Wrapper.py/ERROR]     result = self.events[pluginID][event](payload)

[15:56:42] [Wrapper.py/ERROR]   File "wrapper-plugins\simple.py", line 149, in a
ction_rightclick
[15:56:42] [Wrapper.py/ERROR]     player.client.send(0x23, encodedposition, 0x88
50)
[15:56:42] [Wrapper.py/ERROR]   File "src\proxy.py", line 955, in send
[15:56:42] [Wrapper.py/ERROR]     if len(expression) > 0:
[15:56:42] [Wrapper.py/ERROR] TypeError: object of type 'long' has no len()
[15:56:42] [Wrapper.py/ERROR]
```

**Comment by benbaptist** [comment]
If you just want to send the packets' contents manually, try player.client.send(0x23, "raw", ("\xff\xff\xff\xff etc etc etc"))

**Comment by suresttexas00** [comment]
what does the \ stand for?

**Comment by suresttexas00** [comment]
That did not work either.. I even selected a real easy coordinate set: 0 (.5) , 64, 0:

player.client.send(0x23, "raw", ("\x00\x00\x00\x01\x00\x40\x00\x00\x08\x50"))

: ( 
![image](https://cloud.githubusercontent.com/assets/10001762/6475509/2ad8f0a8-c1d9-11e4-91be-9a1b289439cc.png)

**Comment by Cougar** [comment]
I didn't find any packet id from minecraft protocol to query block code by position. This means that caching chunks is only way bit it would be quite heavy task and needs a lot of memory. Maybe try to cache only positions of items like bed, chests, crafting table, buttons etc but no building blocks. I'm thiking about this right now to implement /lock /unlock commands for chests, furnaces, hoppers etc.

**Comment by suresttexas00** [comment]
yes, that would be nice.

**Comment by suresttexas00** [comment]
for the chest buttons hoppers and all that, denying player.place by returning false works (happy accident I found out on my server).. anyway the problem I was having with fake block placement is fixed by #174

**Comment by suresttexas00** [comment]
Coming back to this, we could install an event for this here:
```
		if id == self.pktCB.usebed: # Use Bed
			data = self.read("varint:eid|position:location")
			if data["eid"] == self.eid:
				self.client.send(self.pktCB.usebed, "varint|position", (self.client.eid, data["location"]))
				return False
			return True
```
presently, all we are doing is modding the eid with this packet...

**Comment by suresttexas00** [comment]
I have installed the new event in a test branch.
It works by implementing a new event ("player.usebed") and a new client property "bedlocation" accessible with player.getBedPostion().

Wrapper will not save bedpostion between client logins.. once the client object closes, there goes the bedposition... it is up to the plugin to use the event as a signal to get the position and save it in it's own Storage instances.
