### ISSUE TITLE
log.py changes

### ISSUE THREAD

**Issue by suresttexas00** [benbaptist/minecraft-wrapper#147]
Changed my log.py as follows:
```
class Log:
	def __init__(self):
		fn = ("%s wrapper.log" % (time.strftime("%Y-%m-%d-%H")))
		self.file = open("logs/" + fn, "a")
		self.abort = False
		lg = threading.Thread(target=self._archiveLog, args=())
		lg.daemon = True
		lg.start()
	def _archiveLog(self):
		while self.abort == False:
			fn = ("%s wrapper.log" % (time.strftime("%Y-%m-%d-%H")))
			self.file.close
			self.file = open("logs/" + fn, "a")
			time.sleep(14400)
```
I did a couple things here:
1) I changed to log location to the same log folder minecraft uses.
2) I changed the filename format, so filenames are now something like: `2015-02-27-13 wrapper.log`, again, same as minecraft's archived logs.
3) Not sure if this is coded properly and I am sure there are "holes" in it, but it works.  Every 4 hours, it attempts to change the log file name.

**Comment by Cougar** [comment]
Don't use space in file name if it is not absolutely neccessary. Also I suggest to make log rotation period configurable or remove time component form logfile name and use only date. In this case log file should change every midnight.

**Comment by suresttexas00** [comment]
The space in the file name is precisely what the default minecraft server jar does with its logs.  I chose to mimic this behavior (which has caused no issues, even under windows) to cause the files (which are side-by-side with the regular server log files) to sort consistently by default.  I agree it could be configurable, however, again, I am (somewhat) mimicking the default server behavior, which creates a new file every time the server is started or at periodic intervals throughout  the day (I am sure the default behavior is more complex, based on both date and file size).

I have been running this config and it works well.  Naturally, if you want to make it more richly featured, you are certainly skilled enough to do so.  Updating the log file behavior is on the feature list, so I'm sure Ben would welcome the help.  I would like to see it also gzip the archived file...

**Comment by suresttexas00** [comment]
it's #89 on his list

**Comment by benbaptist** [comment]
Build 102 implements a version of this. The logs will be stored in logs/wrapper and are gzipped. I have not tested the full functionality (including the automatic rotating when the day changes), but it hopefully should all work well.
