### ISSUE TITLE
Vanilla only?

### ISSUE THREAD

**Issue by SirWilli** [benbaptist/minecraft-wrapper#153]
hey,

does this only support vanilla servers or also bukkit/spigot?

**Comment by suresttexas00** [comment]
theoretically and, as advertized, yes... I have only tried vanilla so far.  There is a setting for use with spigot...

**Comment by benbaptist** [comment]
Oh, and I should probably mention - if you do use Spigot, make sure your jar name has the name "spigot"
in it - like spigot_server.jar or whatever. As long as you do that, Wrapper will detect it as being a Spigot server and should make the appropriate compromises.
