### ISSUE TITLE
player.getItemInSlot(x)["id"]) inventory is not current

### ISSUE THREAD

**Issue by suresttexas00** [benbaptist/minecraft-wrapper#163]
getItemInSlot seems to only be refreshed at player login... :/

code:
```
	def hasItem(self, player, item):
		print item
		for x in range(36, 45):
			#print item
			if (player.getItemInSlot(x)) != None:
				print ( player.getItemInSlot(x)["id"])
				if ( player.getItemInSlot(x)["id"]) == item:
					return True
					#print ("hasit")
		return False
```

The printed results do not change unless I logout and back in.

**Comment by benbaptist** [comment]
This is pretty old - I assume this has been fixed with the slew of improvements to 0x30. I assume the bug was not parsing 0x30, but it helps that I also fixed slot parsing in 106. Gonna presume this is fixed and close it now.

**Comment by suresttexas00** [comment]
Ok!
