### ISSUE TITLE
Will the real timer.tick please stand up!?

### ISSUE THREAD

**Issue by suresttexas00** [benbaptist/minecraft-wrapper#164]
per your [documentation](https://docs.google.com/spreadsheets/d/1TZ5fOiKBzzVVkCckP5RsjY1vjIuT41Ecxzem4jLBGCo/edit#gid=0), the timer.Tick function purports to exist with these parameters: `timer.tick		Called 20 times per second, like a game tick.	no`.

However, no such event seems to exist in the code, except where is is usually defned as:
`self.api.registerEvent("timer.second", self.onTick)` where it is being used as a timer.second event.

I'm looking for something faster than a second...

**Comment by benbaptist** [comment]
hmm. I never seemed to implement this one. I always wanted to get around to it, but yeah. Will add as soon as I do my next code push (which is when I actually get to working on this again!)

**Comment by benbaptist** [comment]
Implemented in build 102.

**Comment by suresttexas00** [comment]
Really??

**Comment by benbaptist** [comment]
Yup, this got so buried and I haven't seen it in forever and completely forgot.. Wish I had, I could've gotten it pushed in long ago.

**Comment by suresttexas00** [comment]
I re-opened this because the timer.tick is presently commented-out code.

I question whether we really want and event being being called in wrapper 20 times a second...

Any thoughts?

**Comment by suresttexas00** [comment]
There is a LOT of overhead associated with running an event.. especially if it will be a cron event at this speed:
```
    def callevent(self, event, payload):
        if event == "player.runCommand":
            if not self.wrapper.commands.playercommand(payload):
                return False
        for sock in self.listeners:
            sock.append({"event": event, "payload": payload})
        try:
            for pluginID in self.events:
                if event in self.events[pluginID]:
                    try:
                        result = self.events[pluginID][event](payload)
                        if result is None:
                            continue
                        if result is not True:
                            return result
```

Maybe something like this is best left to a plugin developer's own code as something to maybe run in a timed thread??

**Comment by benbaptist** [comment]
Yeah, probably. The overhead is quite intense, and there's just too much potential for issues. If it's really important, it's best that they run their own thread anyways so that it won't choke up with the other thread calling stuff.

**Comment by suresttexas00** [comment]
agreed.
