### ISSUE TITLE
Packet.send_position() and Packet.read_position() sign extensin errors

### ISSUE THREAD

**Issue by Cougar** [benbaptist/minecraft-wrapper#172]
Position data is 64 bit long struct (26 bit + 12 bit + 26 bit) where all numbers are signed. Current code doesn't process negative X coordinates right way. For example sending packet with negative X coordinate raises error
```
struct.error: integer out of range for 'q' format code
```
This error is well hidden because packet parsing code in Packet.send() silently discards all exceptions (Packet.read() does the same).

**Comment by suresttexas00** [comment]
This was probably what was wrong with #165

**Comment by suresttexas00** [comment]
Are you sure this was just the x coord? or was that an example? .. Because in #165  , I saw the error specifically with the z Coordinate..

**Comment by Cougar** [comment]
Not sure about other coordinates. I saw that there was quite complicated on probably not right conversion for z too.

Also ulong vs long could be also bigger issue than just a sign because higher bit itself doesn't change a sign but the number is also two's complement and firs sign bit could spoil all other bits too. 

This is why separated numbers and then converted to the negative if highest bit was set. Could be that there is better conversion available but I don't know.. This is good example where tests could help a lot :-D

**Comment by suresttexas00** [comment]
I think this one is closed?  It seems to be in the latest Dev build...

**Comment by suresttexas00** [comment]
Whoever has close permission for this thread should close it
