### ISSUE TITLE
onEnable versus `__init__`

### ISSUE THREAD

**Issue by suresttexas00** [benbaptist/minecraft-wrapper#183]
My editor (PyCharm) complains about this.  It thinks things like `self.homes = self.api.getStorage("homes", True)` should be done in the init... can they be done in init?  why are they done in onEnable?

```
class Main:
    def __init__(self, api, log):
        self.api = api
        self.minecraft = api.minecraft
        self.log = log

    def onEnable(self):
        # DATA
        self.homes = self.api.getStorage("homes", True)
        self.config = self.api.getStorage("config", True)
        self.playerdata = self.api.getStorage("playerdata", True)
        self.mail = self.api.getStorage("mail", True)
        self.filter = self.api.getStorage("filters", True)
        self.breaklog = self.api.getStorage("breaklog", True)
        self.regions = self.api.getStorage("regions", True)
        self.quietlogins = self.api.getStorage("quietlogins", True)
```

**Comment by suresttexas00** [comment]
I sha'n't ask such questions anymore.. I guess that is just how wrapper operates due to the plugin import system.. :)

**Comment by benbaptist** [comment]
I hate editors that complain about the *literal* silliest of things. I seriously cannot fathom why people are so obsessive about very particular methods of doing things when it comes to programming.

**Comment by suresttexas00** [comment]
well I'm not worried about this one... The editor cannot know that the plugins are imported into another program.... It also complains saying that args goes unused in many commands, etc. because it does not know that args is going to be passed regardless...
