### ISSUE TITLE
player object being returned as a boolean

### ISSUE THREAD

**Issue by suresttexas00** [benbaptist/minecraft-wrapper#191]
```
    def action_leftclick(self, payload):  # player break block
        # print payload  # for when you want to parse the payload
        player = payload["player"]
        action = payload["action"]
        # face = payload["face"]  # not sure what use this is
        gamemode = int(player.getGamemode())
        dim = int(player.getDimension())
        name = player.username
```

I get these errors at some point where wrapper is getting confused somehow:
```
[10:10:42] [Wrapper.py/ERROR]
[10:10:43] [Wrapper.py/ERROR] Plugin 'com.suresttexas00.plugins.logger
' errored out when executing callback event 'player.dig':
[10:10:43] [Wrapper.py/ERROR] Traceback (most recent call last):
[10:10:43] [Wrapper.py/ERROR]   File "Wrapper\events.py", line 33, in
callEvent
[10:10:43] [Wrapper.py/ERROR]     result = self.events[pluginID][event
](payload)
[10:10:43] [Wrapper.py/ERROR]   File "wrapper-plugins\guarddog.py", li
ne 124, in action_leftclick
[10:10:43] [Wrapper.py/ERROR]     gamemode = int(player.getGamemode())

[10:10:43] [Wrapper.py/ERROR] AttributeError: 'bool' object has no att
ribute 'getGamemode'
```

**Comment by suresttexas00** [comment]
I suspect this happens when a player, who was online, gets kicked or loses connection and the code is then unable to get his player object... Is that possible?

**Comment by benbaptist** [comment]
Yup! How often is this happening? Are they still connected when it happens or are they kicked?

**Comment by suresttexas00** [comment]
I'm not sure.. it happens to all things player() related... I have been just beefing up the plugin code with more try:except:s to compensate.  Seems to happen more to players with bad internet connections...

The only thing in common is that the player object is a boolean.

**Comment by benbaptist** [comment]
I've noticed Wrapper.py becomes quirkier when the packets are coming in at weird rates - i.e. bad internet connections. 

Also, BTW, I created a gitter for Wrapper.py. https://gitter.im/benbaptist/minecraft-wrapper

**Comment by suresttexas00** [comment]
#190 and #227 and similar... I think it is all the same bug.
