### ISSUE TITLE
Feature addition - Read player yaw and pitch

### ISSUE THREAD

**Issue by suresttexas00** [benbaptist/minecraft-wrapper#195]
I have two pull requests #193 and #194 that are part of the single request.  I know this is probably going to be manually added, as per your custom :) 

I chose to create an additional Method `player.getPosition_more()` versus adding additional fields to the present `player.getPosition()` to maintain backwards-compatibility in case someone's plugins are only expecting three numbers from getPosition.

This allows me to set warps that make the teleported player look in the desired direction (I.e., like "/warp Rules", for instance):

Create warp:
```
            node = "staff"
            pos = player.getPosition()
            more_pos = player.getPosition_more()
            # print(more_pos)
            self.staff["warps"][warp] = (pos[0], pos[1], pos[2], node, more_pos[0], more_pos[1], more_pos[2] )
            player.message({"text": "Created warp '%s'." % warp, "color": "yellow"})
```

Use warp:
```
                    self.api.minecraft.console("tp %s %d %d %d %d %d"
                                               % (player.username, self.staff["warps"][warp][0],
                                                  self.staff["warps"][warp][1], self.staff["warps"][warp][2],
                                                  self.staff["warps"][warp][4], self.staff["warps"][warp][5]))
```

**Comment by benbaptist** [comment]
Implemented/merged in build 100.
