### ISSUE TITLE
Don't understand why api.getStorage objects fluctuate

### ISSUE THREAD

**Issue by suresttexas00** [benbaptist/minecraft-wrapper#196]
I am dealing with one object where I am storing warp data.. and it is constantly fluctuating.. items i deleted a day ago are back in the list.. and at any given moment, the list changes (I am the only one who can add/delete warps).. all the api.getstorages do this...  why?

Without any input from me, it changes from this:
'''
{"warps": {"p2": [31883.323637433674, 67.0, 25338.20901793392], "portals": [3270.5307348580477, 103.0, 2669.668092340251, "staff", -90.60082244873047, -4.050037384033203, false], "p1": [31826.95201823558, 71.0, 25412.453195705904], "stronghold1": [741.2230532498089, 33.0, 0.6999999880790738], "OProom": [235.84977598355078, 56.0, -63.3245829276579], "Jeeskarox": [8117.1371682263925, 68.15457878522446, 63.444568633883726], "alex_chestroom": [3017.820089214752, 50.83829140374222, 8739.171687385], "myregion": [1521.9157604505936, 67.22955103477543, 301.3688044397513], "nether_pearltest": [115.53734140378518, 102.0, 83.46924722296535], "spawntest": [3271.685257982652, 103.0, 2673.5810949049383, "staff"], "swamp": [-464.845840532287, 84.31968973049136, -29.682383729993838], "wason4-1": [-13811.410204106456, 81.15052866660584, 9933.376722944515], "mystiques": [-5388.5, 72.0, -10011.5], "jail": [3263.5089288523445, 98.0, 2662.511479645375], "water_temple": [197.30000001192093, 44.0, -5605.519227954707], "hacker_hell": [7483.5, 0.8873451333870699, 7817.5], "zombieSpawner": [1614.5325514656352, 11.419156430429029, 580.6350509094153], "jacklare": [-1407.0923962382235, 70.7393572271209, 4541.348465524757]}}'''

to this:
'''
{"warps": {"OProom": [235.84977598355078, 56.0, -63.3245829276579], "alex_chestroom": [3017.820089214752, 50.83829140374222, 8739.171687385], "hacker_hell": [7483.5, 0.8873451333870699, 7817.5], "jacklare": [-1407.0923962382235, 70.7393572271209, 4541.348465524757]}}'''

to this:
'''
{"warps": {"alex_chestroom": [3017.820089214752, 50.83829140374222, 8739.171687385], "hacker_hell": [7483.5, 0.8873451333870699, 7817.5], "stronghold1": [740.1556378918563, 33.0, 1.5982858292301847, "staff", 186.7499542236328, 34.949989318847656, false], "jacklare": [-1396.0239155914612, 67.0, 4533.811520126322, "staff", 72.29999542236328, 25.149999618530273, false]}}'''

**Comment by suresttexas00** [comment]
and that first one has warps that were deleted 15 minutes ago with a subsequent /reload and and a server restart...  some I deleted yesterday came back even after wrapper restarts.

**Comment by benbaptist** [comment]
So it's not deleting? Might have something to do with __del__ and maybe some sort of cache not updating and then it ends up flushing the deleted values to disk, and loading them back up next time the thing reboots.

**Comment by benbaptist** [comment]
Dagnabbit Github. I meant the `__del__` method of the Storage object in storage.py.

**Comment by suresttexas00** [comment]
well, in game it deletes, but the disk file fluctuates all the time, as per above... sometimes, the deleted items come back though.

**Comment by suresttexas00** [comment]
I still see this behavior.  I believe the version in wrappers "memory" is what one would expect, but what gets written to disk is usually some "version" the datastorage object was at some point previously.  If I /reload and quickly open the file, I can usually read the real-time contents of the object.

**Comment by suresttexas00** [comment]
I am re-opening this as I am having problems with these getStorage objects again.
The issue (besides the weird fluctuations), is that if I reload the plugin, the data does not save, even though I use the `self.data.save()` during the plugin onDisable.

Gisting my two plugins here.  One (SurestLib.py) is just a dependency.  I could just copy and paste the one method that I use from it, but ME IS LAZY!

https://gist.github.com/suresttexas00/172baa72e758997ab649 - Portals
https://gist.github.com/suresttexas00/0528e3d1b2208682e1e0 - SurestLib

After going through a portal, if the plugin is re-loaded, a person can go right back through immediately.  If they exceeded the max uses, they get a fresh start of the same number of uses.

Did I write the plugin data wrong or something?  I see no errors from the periodic save...

**Comment by JasonBristol** [comment]
I can also confirm that I am having storage object issues. I have a laws plugin that adds a list of criminals to a storage object:

```
{
    "criminals": {
        "SkyeGintama": {
            "reason": "killin pigs", 
            "arrested_by": "colonel369", 
            "booked_on": 1450214921.135376
        }, 
        "colonel369": {
            "reason": "killing pigs", 
            "arrested_by": "colonel369", 
            "booked_on": 1450214922.935432
        }
    }, 
    "laws": {}
}
```

Relevant storage lines:

```
def onEnable(self):
    self.data = self.api.getStorage("law", True)
```

```
# COMMANDS

  def arrest(self, player, args):
    if len(args) > 1:
      reason   = " ".join(args[1:])
      criminal = self.minecraft.getPlayer(args[0])
      criminal.message("&cYou have been placed under arrest by &6%s&c. Reason Given: &6\"%s\"" % (player, reason))
      self.minecraft.broadcast("&6%s&c has been placed under arrest by &6%s&c for &6\"%s\"" % (criminal, player, reason))
      self.imprison(criminal)
      self.data["criminals"][criminal.username]                = {}
      self.data["criminals"][criminal.username]["reason"]      = reason
      self.data["criminals"][criminal.username]["arrested_by"] = player.username
      self.data["criminals"][criminal.username]["booked_on"]   = time.time()
      self.data.save()
    else:
      player.message("&cUsage: /arrest <name> <reason>")

  def pardon(self, player, args):
    if len(args) == 1:
      criminal = self.minecraft.getPlayer(args[0])
      criminal.message("&aYou have been pardoned by &6%s." % player)
      self.minecraft.broadcast("&6%s&a has been pardoned by &6%s&a!" % (criminal, player))
      self.release(criminal)
      del self.data["criminals"][criminal.username]
      self.data.save()
    else:
      player.message("&cUsage: /pardon <name>")

  # FUNCTIONS

  def release(self, criminal):
    self.minecraft.getPlayer(criminal).setGroup("Basic")
    self.minecraft.console("tp %s -569.5 64.0 2109.5 0.0 0.0" % criminal)
    self.minecraft.console("spawnpoint %s" % criminal)

  def imprison(self, criminal):
    if criminal.hasGroup("Basic"): criminal.removeGroup("Basic")
    self.minecraft.console("gamemode 0 %s" % criminal)
    self.minecraft.console("clear %s" % criminal)
    self.minecraft.console("tp %s 3.3320682708052423 6.0 6.561283676739865 629.4434204101562 7.650053024291992" % criminal)
    self.minecraft.console("spawnpoint %s" % criminal)
```

Shortly after arresting someone I can confirm that the `law.json` file is populated. At a random interval it will all of a sudden get cleared and the user is no longer a criminal. Strangely, I will also notice `law.json` randomly populated will old data.

This issue in completely intermittent, all attempts to track down any kind of pattern have failed. It is almost as if some sort of caching is occurring somewhere as others have mentioned.

**Comment by JasonBristol** [comment]
I just ran into this issue again after calling `pardon` on a criminal. The `law.json` file deleted their entry properly, but upon relogging they became a criminal again as `law.json` was somehow repopulated.

I noticed that if I spammed `pardon` a couple times that the changes were persisted.

Just a guess here, but is this a threading issue? I notice in `storage.py` we have the following:

```python
class Storage:
	def __init__(self, name, isWorld=None, root="wrapper-data/json"):
		self.name = name
		self.root = root
		
		self.data = {}
		self.dataOld = {}
		self.load()
		self.abort = False
		self.time = time.time()
		
		t = threading.Thread(target=self.periodicSave, args=())
		t.daemon = True
		t.start()
```

And for `periodicSave`:

```python
def periodicSave(self):
		while not self.abort:
			if time.time() - self.time > 10:
				if not self.data == self.dataOld:
					try:
						self.save()
					except:
						print traceback.format_exc()
					self.time = time.time()
			time.sleep(1)
	def load(self):
		l = ""
		for i in self.root.split("/"):
			l += i + "/"
			if not os.path.exists(l):
				try: os.mkdir(l)
				except: pass 
		if not os.path.exists("%s/%s.json" % (self.root, self.name)):
			self.save()
		with open("%s/%s.json" % (self.root, self.name), "r") as f:
			self.data = json.loads(f.read())
		self.dataOld = copy.deepcopy(self.data)
```

Is there somehow a race condition between `self.data` and `self.dataOld`?

**Comment by suresttexas00** [comment]
I have noticed these things too.  I have normally had to run regular _data_.save() when changing data.

**Comment by benbaptist** [comment]
I think the storage.py system should be centralized to one centralized "server" that manages the flushing of data from each api.getStorage() rather than starting new threads, thus making it easier to cleanup and ensure it is all flushed when the wrapper shuts down. I should also probably add a "dirty" tracker to only save if the dirty flag is tripped - i.e. when the actual data is changed. It might not actually be a good idea though - it's probably better to just compare like how I'm doing it right now.

**Comment by suresttexas00** [comment]
I am sure we are dealing with data races here..  I think we need a locking mechanism (and central server idea) and to get rid of the periodicsave threading (which could be handled by an onTimer Chron ... either wrapper-wide or just let plugins handle their own saves.

**Comment by suresttexas00** [comment]
I think removing the threading will definitely preclude any data races between old and new data.

Most of our plugins don't use threading themselves (except my voting/votipyer plugins).. so we should "mostly" already have a system that is fairly atomic, yes?  presuming only one plugin is touching a given data structure ( i.e. "laws" being the only plugin accessing the laws data Storage structure..

I do worry about things like I have in my own plugin sets where I use getPluginContext() to access another plugins data set...

Even within plugins, is there a possibility of two different event items trying to access the data at once (like @JasonBristol mentioned with a playerlogin event)?

**Comment by suresttexas00** [comment]
I have another theory now after putting the periodicsave back in.  I have noted that periodicsave threads never abort.  The __del __ is not setting the self.abort to true.  This print statement _never_ runs:
```
    def __del__(self):
        self.abort = True
        print("Storage '%s' aborting" % self.name)
        self.save()
```

My theory is that (particularly with plugin reloads), we may get two or more instances of a particular plugin's data storage running at the same time.  These difference instances load and save at different intervals causing the fluctuations.  I think another abort method is needed.

**Comment by suresttexas00** [comment]
:) add close() method

```
    def close(self):
        self.save()
        self.abort = True
```
