### ISSUE TITLE
How to give permissions to players via plugin code

### ISSUE THREAD

**Issue by suresttexas00** [benbaptist/minecraft-wrapper#199]
I want to be able to give a player a group permission from within the plugin; equivalent to the in-game command `/perms users SurestTexas00 group Trusted`.

I tried via console, but, as you guessed, that does not work:
`self.api.minecraft.console("/perms users %s group member" % name)`
= console:
`Unknown command...`

**Comment by benbaptist** [comment]
I put myself in code hell since I kept adding code to Wrapper.py and then deciding that it wasn't stable enough. In the end, my next code push won't be that big. :P

**Comment by suresttexas00** [comment]
I think that is a wise move... How can I do this without a code change on your end?

**Comment by benbaptist** [comment]
I implemented this in build 102:
```
Added player.setGroup(group) and player.setPermission(node, value=True) [untested]
```

Will push code changes tonight. I will close this now, but feel free to re-open if it's not enough. More permissions-related methods will probably be coming soon.

**Comment by suresttexas00** [comment]
hmmmm... setgroup looks ok (hopefully)... setpermissions, though... we added a way to delete a permission node in one of the releases/builds... i'll have to see how setting it true/false works...

**Comment by suresttexas00** [comment]
ok.. how would you remove the group?  Does just using setGroup toggle it?  I'll have to see this code first.. can you re-open this until I've tested / looked it over?

**Comment by benbaptist** [comment]
I was going to make it toggle it, but I've decided against that now as it seems like it might be prone to accidentally turning it off when you don't want to (because the group was already added to them). I'll add a player.removeGroup then. And yeah, I'll go add a deletePermission command too.
