### ISSUE TITLE
Cannot load End

### ISSUE THREAD

**Issue by suresttexas00** [benbaptist/minecraft-wrapper#200]
When I go to the end now, I just get purple sky/void.  I tried using different MC versions 1.8.1 1.8.4 and the current one I am using, 1.8.7.

No unusual console output.  Just client end void.  I dont think it is client related because I tried different clients too.

**Comment by benbaptist** [comment]
Interesting. I'm going to test this right now.

**Comment by benbaptist** [comment]
Whoopie! This is probably related to the nether issues too. It had to do with me trying to receive skylight in the nether and end when the server sends no skylight packet. http://s.benbaptist.com/w8uwJ

First code push in months will probably be tonight. :P

**Comment by benbaptist** [comment]
Fixed in Build 100.
