### ISSUE TITLE
player position 0x06 05 04

### ISSUE THREAD

**Issue by suresttexas00** [benbaptist/minecraft-wrapper#203]
These look problematic to me, If I am understanding these packet formats correctly:
```
 		if id == 0x04:
 			data = self.read("double:x|double:y|double:z|bool:on_ground")
-			self.position = (data["x"], data["y"], data["z"])
+			self.position = (data["x"], data["y"], data["z"], data["on_ground"])
+		if id == 0x05: # Player Look
+			data = self.read("float:yaw|float:pitch")
+			yaw, pitch = data["yaw"], data["pitch"]
+			self.head = (yaw, pitch)
 		if id == 0x06:
 			data = self.read("double:x|double:y|double:z|float:yaw|float:pitch|bool:on_ground")
-			#objection = self.wrapper.callEvent("player.move", {"player": self.username, "xyz": (data["x"], data["y"], data["z"]), "on_ground": data["on_ground"]})
 			self.position = (data["x"], data["y"], data["z"])
+			self.head = (data["yaw"], data["pitch"])
 			if self.server.state is not 3: return False
```
0x06 is only setting the 3 number tuple as before (ommitting on ground)
0x05 packet also takes the onground Boolean value (should be `data = self.read("float:yaw|float:pitch|bool:on_ground")`

**Comment by benbaptist** [comment]
0x05 does indeed take an on_ground, but I don't actually need to parse it. I just ignored it since I don't use it and don't really want to use it. Nice catch on 0x06 though. is that possibly causing the other issues on #202?

**Comment by suresttexas00** [comment]
could be...

**Comment by suresttexas00** [comment]
especially since those errors involve teleport location changes and changes to onground (falling).

**Comment by suresttexas00** [comment]
And you're sure its OK to partially parse it?

**Comment by suresttexas00** [comment]
I think Onground is a pretty useless (for us) piece of info, but if the data is coming in, shouldn't it be parsed and the self.head updated accordingly?

**Comment by suresttexas00** [comment]
..er or self.position actually.

**Comment by suresttexas00** [comment]
were you able to replicate these kicking errors on your test platforms?

**Comment by suresttexas00** [comment]
Are you planning to push some code for this stuff anytime soon?

**Comment by benbaptist** [comment]
I don't want to trust the client's onGround, though, even though I am using it in other areas. I need to only receive the server's onGrounds. And yeah, I'll probably push if I can figure out the gzipped error. I just want to get this out of the way, and then we might have a pretty stable proxy build on our hands.

**Comment by benbaptist** [comment]
Should I even bother with onGround? Maybe I should just remove it, because it'll be pretty useless once Wrapper.py can see the world and determine for itself whether or not I'm on ground. And Wrapper's implementation would probably be better/more reliable than what the server sparatically sends.

**Comment by suresttexas00** [comment]
Well, I don't see a need for it since I doubt any plugin is going to attempt to see if you are flying, etc... But before you get all fancy with discovering the world, you should make sure you have a solid proxy that is not kicking people and can accurately handle inventories, player objects, etc.  I only handled onground in my implementation to make sure it was there just in case..  I think parsing stuff like that just makes the code cleaner and gives less grey area for errors to creep in.

**Comment by benbaptist** [comment]
I think I'll remove the onGround value then, which will mean player.getPosition() will return this:

(x, y, z, yaw, pitch)

Yeah, I do want to get that out first, but I'm just thinking into the future for stuff.

**Comment by benbaptist** [comment]
Fixed in build 101.
