### ISSUE TITLE
Build 102 won't even start

### ISSUE THREAD

**Issue by suresttexas00** [benbaptist/minecraft-wrapper#207]
No module "errors"

```
 import json, time, nbt, items, storage
 from api.player import Player
 from api.minecraft import Minecraft
+from errors import *
 """ api.py contains the majority of code for the plugin API. """
 class API:
 	""" 
```

**Comment by suresttexas00** [comment]
I undid the error handling with `src/api/__init__.py`

**Comment by suresttexas00** [comment]
It starts now, but spams the console with "version is over 6"

**Comment by benbaptist** [comment]
That's just delicious debug stuff as I work out various kinks in 1.7.10 packet handling and stuff. 

What do you mean it doesn't start? It literally just does nothing with no error whatsoever entirely ever?

**Comment by suresttexas00** [comment]
Yes, It will not start.  Wrapper just hangs with a failure to import module errors.  I had to remove that import statement and the associated code line that used errors

**Comment by suresttexas00** [comment]
To get the wrapper script to run, I had to do this:

in the imports section of `__init__.py` I removed the import statement:
```
from errors import *
```

I then changed this line (line 135-136 ish) from:
```
			raise NonExistentPlugin("Plugin %s does not exist!" % id)
```
back to:
```
			raise Exception("Plugin %s does not exist!" % id)
```

Apparently, my system cannot find a module called "errors"

**Comment by benbaptist** [comment]
errors.py is a local file. It's probably because git didn't commit it due
to its erratic nature since you run from src all the time. It might be
committed in the latest build, so try it now.
On Fri, Jun 26, 2015 at 12:39 PM, Surest Texas <notifications@github.com>
wrote:

> To get the wrapper script to run, I had to do this:
>
> in the imports section of __init__.py I removed the import statement:
>
> from errors import *
>
> I then changed this line (line 135-136 ish) from:
>
>             raise NonExistentPlugin("Plugin %s does not exist!" % id)
>
> back to:
>
>             raise Exception("Plugin %s does not exist!" % id)
>
> Apparently, my system cannot find a module called "errors"
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/benbaptist/minecraft-wrapper/issues/207#issuecomment-115749209>
> .
>



-- 
http://sawmaster2.no-ip.org:82/

iPod network

**Comment by suresttexas00** [comment]
Yes, running form the src is really SO much easier, IMHO

**Comment by suresttexas00** [comment]
I manually pulled it from wrapper.py and put it in the src folder... so 'ill try that... might want to check that.. It was definitely not in the dev build 102.

**Comment by suresttexas00** [comment]
This is all errors.py does LOL? `class NonExistentPlugin(Exception): pass`

**Comment by suresttexas00** [comment]
Once you get it in the src commit, you can close this one.

**Comment by benbaptist** [comment]
welcome to the world of exceptions

**Comment by suresttexas00** [comment]
see my latest #208

**Comment by benbaptist** [comment]
Build 102 is not the latest - it's 103.

**Comment by suresttexas00** [comment]
Yes, but build 103's src is _still_ missing errors.py ;)

**Comment by benbaptist** [comment]
It's all git's fault then. it hates this sort of stuff.

**Comment by benbaptist** [comment]
I finally got git to add `src/errors.py`. I seriously have no clue why I had to go through so many hoops. Anyways, it's added and will be on build 104.
