### ISSUE TITLE
Ohai!  Now setGroup and stuff :P

### ISSUE THREAD

**Issue by suresttexas00** [benbaptist/minecraft-wrapper#208]
You gots a prollem here:

`if uuid == self.uuid:` - uuid and self.uuid will NEVER be 'equal'...  I did not do the debugging to find out why, but they are obviously not the same data type.

Heres what you get:
```
[22:07:08] [Wrapper.py/INFO] SurestTexas00 executed: /addmember SurestTexas00
4f953255-6775-4dc6-a612-fb4230588eff
d2a44ac6-6427-4f3a-98b8-33441c263cd4
0dc85045-131f-47e3-9362-2c206c9d22a4
e98aa494-b72e-4867-a7e3-330fd885f21b
2d8074a5-5f10-4acb-8051-c9b332260d61
b4a5ffc3-07ee-4e42-89bb-78dcb17d79bf
47b3f9e7-0ea5-49a7-b3be-ff437869d2cc
0fc345e8-a4c1-4897-880b-734f8fe3826d
4f953255-6775-4dc6-a612-fb4230588eff
7661ec47-b33d-4f7a-be96-9bc1bc245e69
cd360718-1fdf-43e0-9fb6-d821579d380e
```
despite the fact that 4f9...eff is in the list, it never matches.  here is the debug code:
```
	def getGroups(self):
		""" Returns a list of permission groups that the player is in. """
		print (self.uuid)
		for uuid in self.permissions["users"]:
			print (uuid)
			if uuid == self.uuid:
				print ("found it")
				return self.permissions["users"][uuid]["groups"]
```

if we change that `if uuid == self.uuid:` to `if str(uuid) == str(self.uuid):`, we this console output:

```
[22:07:08] [Wrapper.py/INFO] SurestTexas00 executed: /addmember SurestTexas00
4f953255-6775-4dc6-a612-fb4230588eff
d2a44ac6-6427-4f3a-98b8-33441c263cd4
0dc85045-131f-47e3-9362-2c206c9d22a4
e98aa494-b72e-4867-a7e3-330fd885f21b
2d8074a5-5f10-4acb-8051-c9b332260d61
b4a5ffc3-07ee-4e42-89bb-78dcb17d79bf
47b3f9e7-0ea5-49a7-b3be-ff437869d2cc
0fc345e8-a4c1-4897-880b-734f8fe3826d
4f953255-6775-4dc6-a612-fb4230588eff
Found it
```

**Comment by suresttexas00** [comment]
I noticed this when i ran setGroup, but failed to receive the group persmission, but no errors were generated by the plugin and it ran the associated code fine (i.e. announcing to everyone on the server that I am now a member!).  I guess i'll do the type() stuff and see what's up...

**Comment by suresttexas00** [comment]
OK... self.uuid is a type "class uuid.UUID"  and uuid is a type "unicode"

**Comment by suresttexas00** [comment]
same error exists in setGroup()

**Comment by suresttexas00** [comment]
.. in fact, all the new commands; anywhere you wrote:
`if uuid == self.uuid:`

**Comment by suresttexas00** [comment]
well, hasGroup you wrote this: `if uuid == str(self.uuid):`, which seems to work.

**Comment by benbaptist** [comment]
woah bro, there's an edit button... way too many posts considering it's been literally less than 15 minutes. Yup, looks like I forgot to do a str() to get a more comparable result.

**Comment by suresttexas00** [comment]
yes, but you don't get notified when I edit.... sorry

**Comment by benbaptist** [comment]
I don't need notifications for edits.. I can see them in plain sight.

**Comment by benbaptist** [comment]
Fixed in build 104.

**Comment by benbaptist** [comment]
By the way, build 104 will be release candidate 1 - I believe that 0.7.7 is stable now but I'd like to do a release candidate first to make sure.
