### ISSUE TITLE
Still having issues with log rotation. (fixed)

### ISSUE THREAD

**Issue by suresttexas00** [benbaptist/minecraft-wrapper#210]
Unfortunately, I keep shutting down wrapper by mistake and did not get the logs to document it.  I'll try to get something tonight.  Build 104 dev.  I know it's something about file being in use...

**Comment by suresttexas00** [comment]
Build 104

**Comment by suresttexas00** [comment]
I do see you made a patch, which I have not tried.  However, i did get the console log error for you to look at:
```
None
Day changed, rotating logs...
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Python27\lib\threading.py", line 810, in __bootstrap_inner
    self.run()
  File "C:\Python27\lib\threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "Wrapper\log.py", line 36, in loop
    self.rotateLogs()
  File "Wrapper\log.py", line 28, in rotateLogs
    os.remove("logs/wrapper/current.log")
WindowsError: [Error 32] The process cannot access the file because it is being used by anot
her process: 'logs/wrapper/current.log'

Failure to write string - possibly due to writing while rotating log files
[2015-06-29 00:18:15] [Wrapper.py/INFO] Restarting Minecraft server with reason: Server is c
onducting a scheduled reboot. The server will be back momentarily!
Traceback (most recent call last):
  File "Wrapper\log.py", line 42, in write
    self.file.write(("%s\n" % payload).encode("utf8"))
ValueError: I/O operation on closed file

[00:18:15] [Wrapper.py/INFO] Restarting Minecraft server with reason: Server is conducting a
 scheduled reboot. The server will be back momentarily!
[00:18:15] [Server thread/INFO]: Stopping the server
[00:18:15] [Server thread/INFO]: Stopping server
[00:18:15] [Server thread/INFO]: Saving players
[00:18:15] [Server thread/INFO]: Saving worlds
[00:18:15] [Server thread/INFO]: Saving chunks for level 'AllTheWorld'/Overworld
[00:18:15] [Server thread/INFO]: Saving chunks for level 'AllTheWorld'/Nether
[00:18:15] [Server thread/INFO]: Saving chunks for level 'AllTheWorld'/The End
[00:18:16] [Server Shutdown Thread/INFO]: Stopping server
[00:18:16] [Server Shutdown Thread/INFO]: Saving players
Failure to write string - possibly due to writing while rotating log files
[2015-06-29 00:18:16] [Wrapper.py/INFO] Server stopped
Traceback (most recent call last):
  File "Wrapper\log.py", line 42, in write
    self.file.write(("%s\n" % payload).encode("utf8"))
ValueError: I/O operation on closed file

[00:18:16] [Wrapper.py/INFO] Server stopped
Failure to write string - possibly due to writing while rotating log files
[2015-06-29 00:18:16] [Wrapper.py/INFO] Starting server...
Traceback (most recent call last):
  File "Wrapper\log.py", line 42, in write
    self.file.write(("%s\n" % payload).encode("utf8"))
ValueError: I/O operation on closed file

[00:18:16] [Wrapper.py/INFO] Starting server...
[00:18:19] [Server thread/INFO]: Starting minecraft server version 1.8.7
[00:18:19] [Server thread/INFO]: Loading properties
[00:18:19] [Server thread/INFO]: Default game type: SURVIVAL
[00:18:19] [Server thread/INFO]: Generating keypair
[00:18:19] [Server thread/INFO]: Starting Minecraft server on 127.0.0.1:25560
[00:18:19] [Server thread/INFO]: Using default channel type
[00:18:19] [Server thread/WARN]: **** SERVER IS RUNNING IN OFFLINE/INSECURE MODE!
[00:18:19] [Server thread/WARN]: The server will make no attempt to authenticate usernames.
Beware.
[00:18:19] [Server thread/WARN]: While this makes the game possible to play without internet
 access, it also opens up the ability for hackers to connect with any username they choose.
[00:18:19] [Server thread/WARN]: To change this, set "online-mode" to "true" in the server.p
roperties file.
[00:18:19] [Server thread/INFO]: Preparing level "AllTheWorld"
[00:18:19] [Server thread/INFO]: Preparing start region for level 0
[00:18:22] [Server thread/INFO]: Preparing spawn area: 0%
[00:18:25] [Server thread/INFO]: Preparing spawn area: 0%
[00:18:26] [Server thread/INFO]: Done (6.509s)! For help, type "help" or "?"
Failure to write string - possibly due to writing while rotating log files
[2015-06-29 00:18:26] [Wrapper.py/INFO] Server started
Traceback (most recent call last):
  File "Wrapper\log.py", line 42, in write
    self.file.write(("%s\n" % payload).encode("utf8"))
ValueError: I/O operation on closed file

[00:18:26] [Wrapper.py/INFO] Server started
```

**Comment by benbaptist** [comment]
The second error is just a result of it not finishing the rotating process and thus writing to write to a closed file. I can only imagine that this isn't closing on Windows properly:
```
with open("logs/wrapper/current.log", "r") as f:
				logData = f.read()
```
The patch was literally only a time.sleep() to possibly delay and allow the rotating to work properly, but since I know what line it is that breaks it, I think my time.sleep() probably isn't placed very well. I'm going to just try this instead, to see if I can get the file to explicitly close:
```
with open("logs/wrapper/current.log", "r") as f:
				logData = f.read()
				f.close()
```
followed by a small time.sleep just to make sure. 

Hooray for Windows..... ugh..... :P

**Comment by suresttexas00** [comment]
Actually, I think I would do it with this indentation:
```
with open("logs/wrapper/current.log", "r") as f:
                logData = f.read()
f.close()
```

**Comment by benbaptist** [comment]
No, because that would be outside of the namespace of the with statement (unless something's changed).

**Comment by suresttexas00** [comment]
Oh, i see what you are saying.  I think I have done the way I had it before without errors before.. but I don't know.  when I get some time, I am going to dig into this issue more.

**Comment by suresttexas00** [comment]
ok...
The explicit close is not needed.
1) the one second delay did help the changeover.
2) The other error from the printing of logs during changeover, especially at startup...

I created (am creating) a pull request that fixes the issue by buffering the log during changeovers.  I also changed the timer that checks the day to every minute versus each second.

**Comment by suresttexas00** [comment]
Fixed with #215 .  Please close this request after pulling or manually inserting.

**Comment by suresttexas00** [comment]
Well that did not work and this was a particularly vexing problem.  I tried about 101 different arrangements and nothing worked.  My final solution is a follows: Get rid of the self.file thing that is always writing in the back ground.  That thing produces so many locks, windows never lets go until wrapper is halted.  I went with a simple system that only writes the log file on demand, directly using `with open(self.file, 'a') as f:` (self.file is now just a text string - "logs/wrapper/current.log").  During log changeover, file writing is prevented and items are cached in the self.buffer.  Since there is no permanent lock on the current.log anymore; no more issues!

New pull request in just a bit...

**Comment by suresttexas00** [comment]
RC3 did not Fix it. file is still "being used by another process".  I must continue to use my system in pull request #216.  Wrapper never releases it's file lock unless the whole wrapper is shutdown.  The only solution I found is to simple open and close the individual writes when a log entry is made.

**Comment by benbaptist** [comment]
the individual writes!?!? That's awful. that will murder disks.

**Comment by suresttexas00** [comment]
I doubt that a modern OS implementation would care if you had one continuous unending file open process (not as though the read/write head hangs out at the whim of your file... it probably is moving and doing other tasks too...) or if you manually append the items as they come in... But "Somehow", you have to reliably and completely close the file for the changeover.  Unless you restart the wrapper, the only way I know is to:

1) turn off the updates and commence the caching, as we are both doing it.
2) Change the self.file to something else (different file, a _real_ file, not just "none"), but _don't_ write any logs to it.
3) Do the changeover.
4) reset the self.file to logs\wrapper\current.log and re-commence writing.

**Comment by suresttexas00** [comment]
How many threads can possibly get opened by this??

**Comment by benbaptist** [comment]
While a simple f.write() and f.flush() usually doesn't block, even under high I/O load conditions, a full .close() and .open() is more likely to result in blocking, which means Wrapper can lag more just from writing to disk.  

2. won't do anything. It makes literally no difference. self.file is just a variable. it is not a file lock. set it to the most magical variable ever, and it'll be 100% zero difference versus just getting it to None.

The rest (1, 3, 4) is already being done in this order. The issue must lay somewhere else, even if it is some sort of really stupid os.path.exists lock which would make no sense to me but is possible, considering this is Windows and I've been more surprised at other things.

**Comment by suresttexas00** [comment]
well, we could try just:
```
		if not os.path.exists("logs/wrapper/current.log"):
			return
```

before we do any self.file.close()'s  After all, if file does not exist, why archive it?

**Comment by suresttexas00** [comment]
Just curious why you changed to "w" versus append?

**Comment by suresttexas00** [comment]
I am still trying to get my head around this comment - "the individual writes!?!? That's awful. that will murder disks."  Do you have an references or links that would substantiate what you are saying?  If this is truly the case, why not cache the log and only write at some interval?

Aren't you assuming that the actual hardware will instantly perform all these writes in real-time to the disks?  Don't OS's (and even the disks themselves) cache stuff like this?  I mean, it's one of the reasons in Linux you have to actually unmount file systems, right? - to ensure the changes actually get written to the disk?   Also, I'm sure that when you "open" a file, the disk heads don't sit there waiting around for your next set of writes..?  I'm sure they are doing other things ( for example, like modding all your r.x.x.mca files as players are building, etc, etc...)  It seems to me, that the "individual writes" are doing pretty much the same thing from a hardware perspective.  Lastly, how fast and how many entries are being made, on average, to a log file? 1 per second on a busy server would be a lot, I think.... but I am sure updates to other files are being made much sooner and more frequently... and the read/write heads still have to shuffle back and forth despite your having permanently opened the file.

I will say that after looking it over, I really should be using "with" to make the writes, though.

**Comment by suresttexas00** [comment]
I have more information now.  I created this code to see if the "switching" would work and I learned something very interesting that confirms my earlier suspicion (that code is keeping the file lock).  I created the following version of log.py:
```
	def __init__(self):
		self.file = open("logs/wrapper/temp.log", "a")
		self.buffer = ""
		self.usebuffer = True
		self.rotateLogs()
		
		t = threading.Thread(target=self.loop, args=())
		t.daemon = True
		t.start()
	def rotateLogs(self):
		if not os.path.exists("logs"): os.mkdir("logs")
		if not os.path.exists("logs/wrapper"): os.mkdir("logs/wrapper")
		if os.path.exists("wrapper.log"):
			with open("wrapper.log", "r") as f:
				originalLog = f.read()
			with gzip.open("logs/wrapper/oldWrapper.log.gz", "w") as f:
				f.write(originalLog)
			os.remove("wrapper.log")

		self.file.close()
		self.file = open("logs/wrapper/temp.log", "a")
		self.usebuffer = True
		if os.path.exists("logs/wrapper/current.log"):
			with open("logs/wrapper/current.log", "r") as f:
				logData = f.read()
				f.close()
			with gzip.open("logs/wrapper/%s.log.gz" % time.strftime("%Y-%m-%d_%H-%M-%S"), "w") as f:
				f.write(logData)
			os.remove("logs/wrapper/current.log")
		self.file.close()
		self.file = open("logs/wrapper/current.log", "w")
		self.usebuffer = False
		if os.path.exists("logs/wrapper/temp.log"):
			os.remove("logs/wrapper/temp.log")
	def loop(self):
		day = time.strftime("%M")
		while True:
			if day != time.strftime("%M"):
				print "Day changed, rotating logs..."
				day = time.strftime("%M")
				self.rotateLogs()
			time.sleep(1)
	def timestamp(self):
		return time.strftime("[%Y-%m-%d %H:%M:%S]")
	def write(self, payload):
		try:
			if self.usebuffer is False:
				if len(self.buffer) > 0:
					self.file.write(self.buffer)
					self.buffer = ""
				self.file.write(("%s\n" % payload).encode("utf8"))
				self.file.flush()
			else:
				self.buffer += ("%s\n" % payload).encode("utf8")
		except:
			print "Failure to write string - possibly due to writing while rotating log files"
			print payload
			print traceback.format_exc()
```

As a result, I now have TWO files with a file lock on them: Current.log and temp.log!  I tried opening the file manager and deleting the files manually while this test server was running and the files cannot be deleted.. until wrapper is shut down.

using self.file = "somefileObject" causes that object to remain open, even after you close it.  I can't get a handle on this.  I have even tried `os.close(self.file.fileno())`

**Comment by suresttexas00** [comment]
WAIT A SEC!  If you are using "w" now, there is actually NO need to remove the old file! :D  "w" will over-write with the new version! :dancer:

**Comment by suresttexas00** [comment]
Tested and works successfully! Pull request #218

**Comment by benbaptist** [comment]
Yes, that's why I set it to W in the first place instead of A. :P In very rare instances I see removing the file to be a good idea, but it probably doesn't matter.

**Comment by suresttexas00** [comment]
Awesome... Please close this too once you patch the code.  The list is being whittled down! :)

**Comment by suresttexas00** [comment]
Fixed
