### ISSUE TITLE
Plugin Speed and getPluginContext()

### ISSUE THREAD

**Issue by suresttexas00** [benbaptist/minecraft-wrapper#211]
If I have methods in plugin "A" that plugin "B" could use, does having plugin "B" run a getPluginContext("A") and using those methods cause me to take a performance "hit" versus just copying and pasting those methods for use directly in Plugin B?

**Comment by benbaptist** [comment]
I can guarantee there'll technically be a performance hit - how much of a performance hit is the question. It has to take extra steps to get the method when using getPluginContext, but it's so miniscule that it probably won't matter. However, is it being run rapidly (100+ times per second)? If it is, it may help to just copy and save some CPU cycles.

**Comment by suresttexas00** [comment]
Yea, I should probably stop trying to be fancy schmancy and just re-do them.. make the plugins more modular as well.
