### ISSUE TITLE
Player disconnect associated with inventory problems with False player.place

### ISSUE THREAD

**Issue by suresttexas00** [benbaptist/minecraft-wrapper#214]
I just snagged a bad player.dat file. The player cannot login and I believe it is inventory-related. The problem occurred during a set of player.place events that returned false... When this occurs, the client "places" the block and the number of, say dirt blocks, in the player inventory is reduced by 1 until they run out of the block. I suspect the difference between client and server 'reckonings' of the player inventory is causing the issue. Where can I drop the raw player data file for you?

https://www.dropbox.com/s/l2fimmx1uaeqsr6/3be20d2e-932d-31ae-b7ca-562a6b62bf41.dat?dl=0

**Comment by suresttexas00** [comment]
The only solution I have is to turn off 0x30 parsing:
```
		#if id == 0x30: # Window Items
		#	data = self.read("byte:wid|short:count")
		#	if data["wid"] == 0:
		#		for slot in range(1, data["count"]):
		#			try:
		#				data = self.read("slot:data")
		#			self.client.inventory[slot] = data["data"]
```
This is causing too many connection problems and I don't use it... Window operations are a little too buggy and alpha right now.  

Here's some error code from the console:

```
Error in the Server->Client method:
Traceback (most recent call last):
  File "Wrapper\proxy.py", line 968, in handle
    if self.parse(id, original) and self.safe:
  File "Wrapper\proxy.py", line 889, in parse
    data = self.read("slot:data")
  File "Wrapper\proxy.py", line 1084, in read
    if type == "slot": result[name] = self.read_slot()
  File "Wrapper\proxy.py", line 1234, in read_slot
    id = self.read_short()
  File "Wrapper\proxy.py", line 1216, in read_short
    return struct.unpack(">h", self.read_data(2))[0]
  File "Wrapper\proxy.py", line 1195, in read_data
    self.obj.disconnect("Received no data or less data than expected - connection closed")
AttributeError: Server instance has no attribute 'disconnect'
```
commenting out the `self.obj.disconnect` results in the same error, but it ends with line 1216 and states something about struct.unpack needing two bytes of string... well i forget, exactly.

**Comment by benbaptist** [comment]
Commenting out the self.obj.disconnect does no good - it's not actually causing an issue, it just isn't handling the disconnection properly. 

Awesome, I think I'll go into my dev system right now and try to fix. Seems like slot parsing is indeed broken.

**Comment by benbaptist** [comment]
Fantastic! The issue was easily reproducible and fixable. The slot parsing wasn't parsing the NBT chunk. Your broken player file now works. Also, commenting out just 0x30 wouldn't be enough - other packets use the slot parsing too and would be just as prone, especially if they had fields to parse afterwards, multiple slots, and NBT data mixed in. The fix will be in build 106.

**Comment by suresttexas00** [comment]
Yes, I have noticed this with other events!  Good to finally nail another one down!  I will eagerly await 106!
