### ISSUE TITLE
Proper place for self. variable definitions?

### ISSUE THREAD

**Issue by suresttexas00** [benbaptist/minecraft-wrapper#217]
Example from the teleport plugin:
```
    def __init__(self, api, log):
        self.api = api
        self.minecraft = api.minecraft
        self.log = log
        # change these if desired
        self.usePermissions = False  # Perms - 'teleport.tpahere', 'teleport.tpa', or 'teleport.denied'
        self.useVanillaBehavior = False  # mask Teleport plugin.  Hide help group and give "unknown command" message.

        # Don't change this - automatically detects Global plugin
        self.hasDependencyGlobal = True
        """ if SurestTexas00 global plugin available, gets it for use in Teleports.  The global plugin simply tracks
        and stores the users location prior to teleport.  This is for use in commands by other plugins, like "/back",
        which need to know where the user was before the teleport. """
        try:
            self.globalset = api.getPluginContext("com.suresttexas00.plugins.global")
        except:
            self.hasDependencyGlobal = False

    def onEnable(self):
        self.data = {}
```

What is the purpose of `self.data` being in the onEnable event versus putting it under the `__init__` ?

Please, if you can explain any difference in how the plugin might function or unexpected results of using one versus the other..?

**Comment by benbaptist** [comment]
None - I did not write this plugin and I have no clue why it's there.

**Comment by suresttexas00** [comment]
I wrote the parts in the `__init__`, but the  `self.data = {}` is just following the same convention used by your example plugins... and you have now explained your rationale...

Does it make a difference, code or performance wise... ?

**Comment by benbaptist** [comment]
A possible difference in the future - onEnable should contain all throw-away variables in the event that I implement a way to reset plugins without forcing a full reload (more intensive) or to force plugins to reload configuration files.

**Comment by suresttexas00** [comment]
Seems like a logical way for it to work.  I think I personally will stick with the python recommendation to avoid self definitions outside init.
