### ISSUE TITLE
api.minecraft getAllplayers

### ISSUE THREAD

**Issue by suresttexas00** [benbaptist/minecraft-wrapper#221]
This error makes more sense than our previous "file access" issues in windows:

```
			with open("wrapper-data/players/" + uuidf) as f:
				try:
					players[puuid] = json.loads(f.read())
				except:
					self.log.error("Failed to load player data '%s'" % puuid)
					self.log.getTraceback()
					# os.remove("wrapper-data/players/" + uuidf)
```
this throws the file access because you are legitimately trying to remove the file from within the `with` statement.  I vote we not bother to os.remove here either.. the bad uuid file gets logged and be manually removed, otherwise just skipping is sufficient.

**Comment by benbaptist** [comment]
Having users manually removing things is NOT a good idea. That just goes against any sense. If there's a problem and it is possible to fix automatically with one swift motion, it needs to be done with said one swift motion. It shouldn't need someone to manually do it themselves - I want Wrapper.py to be as automated, fault tolerant and self-maintaining as possible. I even plan to implement systems that automatically check for chunk corruption and player data corruption and have it restore from backups. it shouldn't need constant maintaining - and besides, what if you end up not seeing the error in the console? It just makes no sense to skip os.remove.

**Comment by suresttexas00** [comment]
Not "users"... Admin/Server owners!  I would never give a user access to my console, OS filesystem, or hardware!

You absolutely should not be doing an os.remove on an open file.. that's just not good!

Really there is no need to mess with deleting this at all... As far as I can tell it was a harmless error in one file... which would likely be over writtten if the user logged on.  besides, even if it did not, you may want to keep files like this to figure out WHY is was bad (the file in question was filled with something like `<Null><Null><Null><Null><Null><Null><Null><Null><Null><Null><Null><Null>`

**Comment by benbaptist** [comment]
I'm not talking about players when I say 'users'. Obviously I'm not talking about players logging into the server to fix their own corruption. 

And I'm not saying it's good to be deleting from an opened file - I understand that it does need to be moved out of the statement, but I never said to KEEP it in the with statement. It's still good to reset the file.

There's very much a need to mess with this. The functionality is now broken and can cause unforseen issues. The only reason this would ever error out is if there's invalid JSON - meaning the file was probably never saved properly, was modified outside of Wrapper.py, disk corruption, etc. and will almost certainly be useless to debug. It's 100% fine to delete it.

**Comment by suresttexas00** [comment]
This seems to work OK:
```
			uuidfileOk = True
			with open("wrapper-data/players/" + uuidf) as f:
				try:
					players[puuid] = json.loads(f.read())
				except:
					self.log.error("Failed to load player data '%s'" % puuid)
					self.log.getTraceback()
					uuidfileOk = False
					# os.remove("wrapper-data/players/" + uuidf)
			if uuidfileOk is False:
				os.remove("wrapper-data/players/" + uuidf)
				uuidfileOk = True
```

**Comment by benbaptist** [comment]
nono no no no no no no no no on ono

Fixed in latest build, hopefully.

**Comment by suresttexas00** [comment]
By nono nonononon are you saying something is wrong with what I wrote, or you just used a different approach?

**Comment by benbaptist** [comment]
Yeah, I just used a slightly different approach with moving everything but the f.read() out of the `with` statement. Wayyyyyy cleaner, as long as I implemented the fix properly (I didn't test anything, just kinda hoped it would work).
