### ISSUE TITLE
question about hasPermission code

### ISSUE THREAD

**Issue by suresttexas00** [benbaptist/minecraft-wrapper#223]
What is the item "wrapper.permission" referring to?  The majority of the code uses self.permissions, then these last three lines move through something called "permission"

```
		for id in self.wrapper.permission:
			if node in self.wrapper.permission[id]:
				return self.wrapper.permission[id][node]
```

entire method (for reference):
```
	def hasPermission(self, node):
		""" If the player has the specified permission node (either directly, or inherited from a group that the player is in), it will return the value (usually True) of the node. Otherwise, it returns False. """
		if node == None: return True
		if "users" not in self.permissions:
			self.permissions["users"] = {}
		uuid = str(self.uuid)
		if uuid in self.permissions["users"]:
			for perm in self.permissions["users"][uuid]["permissions"]:	
				if node in fnmatch.filter([node], perm):
					return self.permissions["users"][uuid]["permissions"][perm]
		if uuid not in self.permissions["users"]: return False
		allgroups = []  # summary of groups included children groups
		for group in self.permissions["users"][uuid]["groups"]:  # get the parent groups
			if group not in allgroups:
				allgroups.append(group)
		itemsToProcess = allgroups[:]  # process and find child groups
		while len(itemsToProcess) > 0:
			parseparent = itemsToProcess.pop(0)
			for groupPerm in self.permissions["groups"][parseparent]["permissions"]:
				if (groupPerm in self.permissions["groups"]) and self.permissions["groups"][parseparent]["permissions"][groupPerm] and (groupPerm not in allgroups):
					allgroups.append(groupPerm)
					itemsToProcess.append(groupPerm)
		for group in allgroups:
			for perm in self.permissions["groups"][group]["permissions"]:
				if node in fnmatch.filter([node], perm):
					return self.permissions["groups"][group]["permissions"][perm]
		for perm in self.permissions["groups"]["Default"]["permissions"]:
			if node in fnmatch.filter([node], perm):
				return self.permissions["groups"]["Default"]["permissions"][perm]
		for id in self.wrapper.permission:
			if node in self.wrapper.permission[id]:
				return self.wrapper.permission[id][node]
		return False
```

**Comment by benbaptist** [comment]
You need to remember the context in this class namespace. self.wrapper
takes you to the main Wrapper class, and permission contains the object
with all the permission data in it. Some classes or functions might just
have an alias to it via self.permission or self.permissions but the
absolute path would be self.wrapper.permission. It all depends on what I'm
doing and where. Some of the code might be outdated and using self.wrapper
if I wrote that prior to having an alias, and some of it mgiht be a result
of needing to reference the absolute variable - occasionally referencing
pointers can lead to some odd results in Python 2.x (I think particularly
Python 2.6 had some weird quirks that you needed to watch out for, but I
could be mistaken).

On Sat, Jul 25, 2015 at 6:44 PM, Surest Texas <notifications@github.com>
wrote:

> What is the item "wrapper.permission" referring to? The majority of the
> code uses self.permissions, then these last three lines move through
> something called "permission"
>
>         for id in self.wrapper.permission:
>             if node in self.wrapper.permission[id]:
>                 return self.wrapper.permission[id][node]
>
> entire method (for reference):
>
>     def hasPermission(self, node):
>         """ If the player has the specified permission node (either directly, or inherited from a group that the player is in), it will return the value (usually True) of the node. Otherwise, it returns False. """
>         if node == None: return True
>         if "users" not in self.permissions:
>             self.permissions["users"] = {}
>         uuid = str(self.uuid)
>         if uuid in self.permissions["users"]:
>             for perm in self.permissions["users"][uuid]["permissions"]:
>                 if node in fnmatch.filter([node], perm):
>                     return self.permissions["users"][uuid]["permissions"][perm]
>         if uuid not in self.permissions["users"]: return False
>         allgroups = []  # summary of groups included children groups
>         for group in self.permissions["users"][uuid]["groups"]:  # get the parent groups
>             if group not in allgroups:
>                 allgroups.append(group)
>         itemsToProcess = allgroups[:]  # process and find child groups
>         while len(itemsToProcess) > 0:
>             parseparent = itemsToProcess.pop(0)
>             for groupPerm in self.permissions["groups"][parseparent]["permissions"]:
>                 if (groupPerm in self.permissions["groups"]) and self.permissions["groups"][parseparent]["permissions"][groupPerm] and (groupPerm not in allgroups):
>                     allgroups.append(groupPerm)
>                     itemsToProcess.append(groupPerm)
>         for group in allgroups:
>             for perm in self.permissions["groups"][group]["permissions"]:
>                 if node in fnmatch.filter([node], perm):
>                     return self.permissions["groups"][group]["permissions"][perm]
>         for perm in self.permissions["groups"]["Default"]["permissions"]:
>             if node in fnmatch.filter([node], perm):
>                 return self.permissions["groups"]["Default"]["permissions"][perm]
>         for id in self.wrapper.permission:
>             if node in self.wrapper.permission[id]:
>                 return self.wrapper.permission[id][node]
>         return False
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/benbaptist/minecraft-wrapper/issues/223>.
>



-- 
http://sawmaster2.no-ip.org:82/

iPod network

**Comment by suresttexas00** [comment]
I was a little confused because the permissions code appears to work fine without these three lines

Date: Sun, 26 Jul 2015 18:00:19 -0700

**Comment by benbaptist** [comment]
I believe specifically the permission object was used as a cache for permissions from an earlier version, as well. I think I removed such things as these quite a while back, but I am not 100% sure.
