### ISSUE TITLE
OnDisable method question

### ISSUE THREAD

**Issue by suresttexas00** [benbaptist/minecraft-wrapper#229]
How long does the onDisable have to run its code on a /reload or /halt?

**Comment by benbaptist** [comment]
What do you mean? This doesn't make sense.

**Comment by suresttexas00** [comment]
Well, I have had plugins where a series of lines of code should have run (for instance, to loop through a list of players to record some data or perform some cleanup and it seems the first record or first few code lines will execute, but that is it.... I thought maybe wrapper was shutting the plugin off before it had time to run all the onDisable code..

**Comment by benbaptist** [comment]
There's no limits and your plugin could even block forever and make Wrapper never continue, if I recall correctly. Probably something else.

**Comment by suresttexas00** [comment]
ok
