### ISSUE TITLE
Eating messes up slot positions

### ISSUE THREAD

**Issue by suresttexas00** [benbaptist/minecraft-wrapper#233]
I have no idea why, but if you eat some beef or rotten flesh (only two i tested) from say, slot 3, and then select slot 1 or 2, gethelditem will return a different slot index's item.  Slot 3 where you ate the meat will also reflect the contents of a different slot.

**Comment by suresttexas00** [comment]
For example, with this specific inventory, after eating and getting full on the rotten flesh, wrapper thereafter believes that the 57 arrows are 64 sticks and that the 64 sticks are a single stick:

![image](https://cloud.githubusercontent.com/assets/10001762/9286701/3cb95ffa-42c7-11e5-8d46-16d5fdfca21a.png)

**Comment by benbaptist** [comment]
Any ideas as to what might be causing this? This is really strange.

**Comment by benbaptist** [comment]
0x30 is a mess of a packet. I've disabled it for now in build 108. it'll fix the issues with people being permanently disconnected, but this means Wrapper most likely won't have the most up-to-date copy of the inventory. Definitely going to investigate this more though as we get closer to fixing the slot parsing. 7

by the way, the issue with the slot parsing seems to be related to not reading the correct amount of NBT data or something. Every item sent after the golden cap in that dropboxed inventory you sent me was complete gibberish. Also, I didn't think NBT could be compressed to just 10 bytes only - leading me to think that the length is incorrect. We'll have to investigate that, it seems.

**Comment by suresttexas00** [comment]
Well,

The error is easy to duplicate... make an enchanted piece of armor and right click it on.. Voila! bad file!

**Comment by suresttexas00** [comment]
I don't know what the inventory issue is.. I'm grateful we narrowed it down to happening when eating!

**Comment by suresttexas00** [comment]
Because the gethelditem is a vital part of things like the worldedit plugin as well as a couple of my own that use a "wand", may I make a suggestion?

instead of disabling 0x30 entirely, can you simply make it ignore the NBT portions for now and still pass the item number, count, and damage items?

**Comment by benbaptist** [comment]
It cannot ignore the NBT part. It doesn't need to be parsed (which I'm
already not doing) but it has to be read in order to read all of 0x30
properly. There's no way to avoid it. That's why I just disabled 0x30. I
assume 0x30 is also resulting in the issues with the slots being garbled.
Probably an all-around broken packet implementation.

**Comment by suresttexas00** [comment]
Isn't parsing the NBT portion what throws the errors?  The client and server don't seem to be having problems with these packets...

**Comment by benbaptist** [comment]
It's reading the structure, not parsing. We're not parsing the actual NBT data, just parsing the slot packet as a whole. For some reason, the length packet is screwy or something on the NBT. Maybe it's not a byte, but a short or something like that, for the length of the packet.

**Comment by suresttexas00** [comment]
Good thoughts.... and you might be right.  Your code say `data = self.read("byte:wid|short:count")`.
The protocol says the window id is an unsigned byte, though.  Not sure that really accounts for these errors, though.

**Comment by suresttexas00** [comment]
Looking at the slot data on http://wiki.vg/Slot_Data , it looks like there is no field to tell you the length of the nbt blob... Seems you would HAVE to parse it to determine where it ends and the next element of the array starts.... as the 0x30 packet field "slot data" is actually an array of slots.

**Comment by suresttexas00** [comment]
I think the problem is an incomplete slot reading algorithm.  This line `nbtCount = self.read_byte()` in read_slot is not actually producing and NBT count as the variable name would imply.  After that, the code is largely commented out and seems incomplete as it does not do anything to get the actual length of the NBT data.

**Comment by suresttexas00** [comment]
I'm thinking this might be fixed with the various updates sasszam made.

**Comment by Sasszem** [comment]
I re-written the NBT(& slot) reading & writing methods, so if that caused the problem, then it's over.
(The WIKI's doc about the NBT format is a junk. I had to experiment with other python-based packet frameworks to get it work.)
