### ISSUE TITLE
3 errors in smallbrother

### ISSUE THREAD

**Issue by suresttexas00** [benbaptist/minecraft-wrapper#240]
I was going to use this for a quick and dirty logger for my servers.  As I was gong through the code, three errors were flagged:

two of them are here in the Logger class:
```
    def close_chest(self, x, y, z):
        return self.write(uuid, 0x05, "int|int|int", (x, y, z))

    def chest_action(self, x, y, z, action, slot, itemid, damage):
        return self.write(uuid, 0x04, "position|byte|byte|short|short", ((x, y, z), action, slot, itemid, damage))
```
self.write takes three arguments (aside from self), but four are given.  I assume the uuid items are the typo?

in the `subcommand == "_debug_parse_region_data":`, the following line appears:
```
                chunk = ChunkReader(int(x / 1024), int(z / 1024), self.logger.worldName)
```
It appears to be a typo and this is supposed to be a call to create an instance of the Reader class, but the first argument confuses me as it does not seem to be a uuid, as per: `class Reader:    def __init__(self, uuid, worldName):`

Am I just spinning wheels with this one?  Will this be pretty much broke after 1.8.x?

**Comment by benbaptist** [comment]
I think that line is old code that might not really matter anymore - although I'm not 100% sure. I think I just had debug code that I forgot to remove.

**Comment by suresttexas00** [comment]
I believe #284 is being caused by one of these errors.

**Comment by suresttexas00** [comment]
Well, I've pored over the SB code quite a bit and cleaned it up some, fixing #284 .  The debugging command was removed and I removed uuid as an argument passed to the chest functions.  However, since the chest logging part is not working, the write() for chest stuff is probably what needed the corrections,

**Comment by suresttexas00** [comment]
#312
