### ISSUE TITLE
Proxy.py Rewrite

### ISSUE THREAD

**Issue by benbaptist** [benbaptist/minecraft-wrapper#244]
So, I've been thinking of this internally in my head for months now. I really want to re-do proxy.py (again!), but I want to run this by everyone. Right now, implementing backwards compatiblity is a mess and 1.9 just makes it worse (if I recall correctly, doesn't 1.9 shift a ton of packet IDs by one or something?). I want to re-do it in a way that not only makes backwards compatibility easier, but also allows cross-protocol support (i.e. allowing 1.9 clients to connect to a 1.8 server, connecting 1.9 clients to 1.9 servers, but then player.connect'ing them to a 1.8 server, etc etc etc.)

How should we go about this? I've thought of having a primary translation layer in the middle of everything. Throw a packet in, and have it come out the other side, translated to whatever it needs for the recipient to understand it. `player.connect()`should be a primary focus with this whole system, ensuring that it works well and doesn't go crazy like it does now. Oh, and, of course, I've always wanted to split proxy.py into multiple files. :P

What do you all think? Any ideas or stuff?

**Comment by suresttexas00** [comment]
The translation layer is a good idea and I have thought about that myself.  Not sure how feasible it would really be to allow a 1.8 client to attempt playing on a 1.9 server. 

I have had good success by using self variables and changing the packet numbers to cope with different versions:
```
		if self.version >= PROTOCOLv1_9REL1:
			self.pkt_joingame = 0x24
			self.pktchat = 0x0f
			self.pktspawn = 0x42
			self.pktrespawn = 0x33
			self.pktplayerpos_look = 0x2e
		else:
			self.pkt_joingame = 0x01
			self.pktchat = 0x02
			self.pktspawn = 0x05
			self.pktrespawn = 0x07
			self.pktplayerpos_look = 0x08

```

```
		if id == self.pktplayerpos_look: # Player Position and Look
			data = self.read("double:x|double:y|double:z|float:yaw|float:pitch")
			x, y, z, yaw, pitch = data["x"], data["y"], data["z"], data["yaw"], data["pitch"]
			self.client.position = (x, y, z)
```

**Comment by suresttexas00** [comment]
what is the purpose of the various "flush" methods?  I am asking what the concept of flushing in general is...
I notice this is done quite a bit with socket connections.  For instance, Proxy.host starts client.handle as a thread, but client.handle then spurs off client.flush as yet another "sub-thread".

**Comment by benbaptist** [comment]
Flushing is for sending data - the first thread is for receiving data. The idea is that if you .send() from more than one thread, collisions can occur and result in mixing data. The buffer and flush concept fixes this by queueing up packets and sending them in one, unified thread rather than sending them at the time of running the .send() method, since .send() can be ran from outside of the main thread, including but not limited to the Player class.

**Comment by Sasszem** [comment]
I'm working on some sending&reading functions(nbt & slot), when I finish them I'll send it you or do a pull request.

**Comment by benbaptist** [comment]
Awesoem!

**Comment by Sasszem** [comment]
Ok, NBT writing looks like works fine, here's a bytearray that made with it:
'\x01\x16\x01\x00\x00\x0a\x00\x03tag\x0a\x00\x07display\x08\x00\x04Name\x00\x03ASD\x09\x00\x04Lore\x08\x00\x00\x00\x02\x00\x05FIRST\x00\x06SECOND\x00\x00'

I need to see the reading system for writing the NBT reader, or I can make this for the existing Proxy.py.
I'll post the code for the NBT writer, you can implement it in your code.

**Comment by jackwilsdon** [comment]
Is there a reason that we are not using the [NBT](https://pypi.python.org/pypi/NBT) Python library?

**Comment by benbaptist** [comment]
Interesting! I have not acutally begun working on the re-write proxy.py just yet but I will whenever I get the time to do so.

**Comment by Sasszem** [comment]
Then I should do the reading system for the existing Proxy.py?

**Comment by suresttexas00** [comment]
Yes, Please do share it that way.. Ben may be a while with that rewrite.

**Comment by Sasszem** [comment]
NBT reading & sending  done, code cleanup & re-compiling, then send pull req.

**Comment by suresttexas00** [comment]
Do you have the changes yet?  I don't need the compiled version.. I don't use it anyway.  I run the /src directly.

**Comment by Sasszem** [comment]
Pull req. sent, along with a dirty sample plugin. You can checkout my 
fork of this.

2015.12.20. 18:29 keltezéssel, Surest Texas írta:
>
> Do you have the changes yet? I don't need the compiled version.. I 
> don't use it anyway. I run the /src directly.
>

**Comment by suresttexas00** [comment]
If you do a rewrite, my #272 version might be a good place to start... and all the packet numbers and such are documented now.

**Comment by suresttexas00** [comment]
This is complete at the new forks.

**Comment by suresttexas00** [comment]
"Flushing is for sending data - the first thread is for receiving data. The idea is that if you .send() from more than one thread, collisions can occur and result in mixing data. The buffer and flush concept fixes this by queueing up packets and sending them in one, unified thread rather than sending them at the time of running the .send() method, since .send() can be ran from outside of the main thread, including but not limited to the Player class."

I am not sure this is necessary.  My thoughts are that the socket connections should be atomic, which seems to be what I have found in researching it.  I think we are taking a performance hit in wrapper by using this flushing mechanism.  I wonder if it is not responsible for some proxy issues I am having in the new wrapper.  I wonder if getting packets "in spurts" like this makes the server think we are lagging or causes it to think we are hacking (moving too fast, sending packets to rapidly).  I notice the server sends a lot of playerposlook packets (which are sent when it thinks the client is not doing things properly) making the client jerk or get Tp'ed backwards.

http://stackoverflow.com/questions/1981372/are-parallel-calls-to-send-recv-on-the-same-socket-valid

**Comment by suresttexas00** [comment]
They are wrong... but I did get inspiration on ways to improve flushing from here:
https://github.com/blixt/py-minecraft/tree/master/example/wrapper
