### ISSUE TITLE
Windowing

### ISSUE THREAD

**Issue by Sasszem** [benbaptist/minecraft-wrapper#245]
I've seen in the code of Player.py that you want to add a system to manage inventory windowes. When I try to run the following code, It crshes the client. I don't know, what's wrong with it, becouse there is no code sample at the docs of the protocol about the slot type.

```python
player.openWindow(None,"Name",20)
player.getClient().send(0x2f, "byte|short|short|byte|short|byte", (player.getClient().windowCounter, 0, 98, 2, 0,0}))
```
I saw that there is _read_ method for slots in the proxy, but there's no _send_ method 4 them.

* Please
    * Tell me, what's wrong with this code
    * Add a method 4 sending slots

**Comment by Sasszem** [comment]
Code corrected.
* _**proxy.py**; Packet class_
```python
def send_slot(self,payload):
		id,count,damage=payload
		return self.send_short(id)+self.send_byte(count)+self.send_short(damage)+self.send_byte(0)
```
* _**proxy.py**; Packet class_
```python
def send(self, id, expression, payload):
		result = ""
		result += self.send_varInt(id)
		if len(expression) > 0:
			for i,type in enumerate(expression.split("|")):
				pay = payload[i]
				if type == "string": result += self.send_string(pay)
				if type == "json": result += self.send_json(pay)
				if type == "ubyte": result += self.send_ubyte(pay)
				if type == "byte": result += self.send_byte(pay)
				if type == "int": result += self.send_int(pay)
				if type == "short": result += self.send_short(pay)
				if type == "ushort": result += self.send_ushort(pay)
				if type == "varint": result += self.send_varInt(pay)
				if type == "float": result += self.send_float(pay)
				if type == "double": result += self.send_double(pay)
				if type == "long": result += self.send_long(pay)
				if type == "bytearray": result += self.send_bytearray(pay)
				if type == "bytearray_short": result += self.send_bytearray_short(pay)
				if type == "uuid": result += self.send_uuid(pay)
				if type == "metadata": result += self.send_metadata(pay)
				if type == "bool": result += self.send_bool(pay)
				if type == "position": result += self.send_position(pay)
				if type == "slot": result += self.send_slot(pay)
				if type == "raw": result += pay
		self.sendRaw(result)
		return result
```
* _**calling** from plugins:_
```python
player.openWindow(None,"Name",20)
player.getClient().send(0x2f, "byte|short|slot", (player.getClient().windowCounter, 0,(98,2,0)))
```

When I'll finish the packet reading, I'll create a pull request.

**Comment by suresttexas00** [comment]
Do you know how to make this so that the NBT data is also sent?

**Comment by Sasszem** [comment]
I have no idea now, but there's no reference about it in *http://wiki.vg/Protocol#Set_Slot* and in *http://wiki.vg/Slot*.

I have added a new event type, **player.setSlot**, triggered when a player *__clicks__*(I shoud rename it). Now it works fine. When I'll finish the Windowing system, I'll create a pull request. Now I've written a simple function that allow *setting the data* in the window using *setSlot(0x2F)* packages.
Sample plug-in:
```python
NAME = "Window test"
AUTHOR = "Sasszem"
ID = "com.sas.plugins.win"
VERSION = (1, 2)
SUMMARY = "This plugin opens a window with nothing!"
WEBSITE = ""
DESCRIPTION = """This plugin is just a test. Do /open ingame"""
class Window():
	def __init__(self,player,title,slots):
		pass


class Main:
	def __init__(self, api, log):
		self.api = api
		self.minecraft = api.minecraft
		self.log = log
		self.players={}
	def openW(self,player,args):
		if len(args)>1:
			self.dumpI(player)
			player.openWindow(None,args[0],int(args[1]))
			for i in range(len(self.players[player.name])):
				inv=self.players[player.name]
				item=inv[i]
				if item != None:
					player.message(str(item))
					itemData=(item['id'],item['count'],item['damage'])
					try:
						player.getClient().send(0x2f, "byte|short|slot", (player.getClient().windowCounter, i-9,itemData))
					
					except:
						pass
		else:
			player.message("Usage: /open <Title> <SLOTS>")
	def dumpI(self,player):
		#player.message(str(player.getClient().inventory))
		self.players[player.name]=player.getClient().inventory
	def onEnable(self):
		self.api.registerCommand("open",self.openW,"s.open")
		self.api.registerEvent("player.setSlot",self.setSlot)
	def setSlot(self,payload):
		payload['player'].message(str(payload))
		#payload['player'].getClient().send(0x2f, "byte|short|slot", (-1, -1,(98,0,0)))
		return False
	def onDisable(self):
		pass
```

One thing that when I want to set the item picked up by the cursor to air(by using the *payload['player'].getClient().send(0x2f, "byte|short|slot", (-1, -1,(0,0,0)))* line in *setSlot()*, it crashes the game)

**Comment by Sasszem** [comment]
* Sorry, now it cancels all 0x0E packets, I'll update it.

**Comment by suresttexas00** [comment]
Do you have the code for event.setSlot

**Comment by Sasszem** [comment]
_**Proxy.py,** in **Client.parse()**_
```python
if id == 0x0e:
			data = self.read("ubyte:wid|short:slot|byte:button|short:action|byte:mode|slot:clicked")
			data['player']=self.getPlayerObject()
			if not self.wrapper.callEvent("player.setSlot",data): return False
```

**Comment by suresttexas00** [comment]
If you want to tackle it further, here is further info about the NBT format that fills in the blanks left by  http://wiki.vg/Protocol#Set_Slot : 

http://wiki.vg/NBT
http://minecraft.gamepedia.com/NBT_format
https://github.com/twoolie/NBT

It is beyond my time or expertise level at this point...

**Comment by suresttexas00** [comment]
I would love to see a fix of the full NBT parsing, as we also had to turn off window items parsing 0x30 because of a faulty parsing of NBT data it contains.

**Comment by Sasszem** [comment]
For some reason, the client crashes when I try to send NBT. I've manually encoded a slot data with nbt, here's it:
'\x01\x16\x01\x00\x00\n\x03tag\n\x07display\x08\x04Name\x03ASD\x00\x00'
I haven't tested it, but I found that I may need to write a custom nbt writer & reader.

**Comment by Sasszem** [comment]
Ok, the main reason of the crashes was that I send the length prefix of the names as byte, but it needs to bee short.

**Comment by Sasszem** [comment]
Ok, the NBT writing & reading methods finished, after a bit of cleanup & re-compiling, I'll send a pull req.

Now I'm wondering that what functionality needed in the Window(or InventoryWindow) class.
I think that something like this will be good:
https://ci.visualillusionsent.net/job/CanaryLib/javadoc/net/canarymod/api/inventory/Inventory.html

**Comment by suresttexas00** [comment]
Is this still open?

We are working on a new fork for development.  I am hosting it on my fork.  Your input would be valued.

We are using branch "experimental" for development work and will periodically be sending BenBaptist pull requests to his development branch.

**Comment by suresttexas00** [comment]
@Sasszem is this still open?
