### ISSUE TITLE
Unable to run in-game commands

### ISSUE THREAD

**Issue by JasonBristol** [benbaptist/minecraft-wrapper#246]
I have dropped a couple of your example plugins into my wrapper-plugins folder

>root@crownless:/home/jason/Documents/minecraft-server/wrapper-plugins# ls
>Gauntlet.py   home.py   Scarlet.py   SmallBrother.py   teleport.py   zombie.py
>Gauntlet.pyc  home.pyc  Scarlet.pyc  SmallBrother.pyc  teleport.pyc  zombie.pyc

 and can confirm that they are loaded by Wrapper.py

>root@crownless:/home/jason/Documents/minecraft-server# python Wrapper.py
>[23:09:17] [Wrapper.py/INFO] Wrapper.py started - Version 0.7.6 (stable)
>[23:09:17] [Wrapper.py/DEBUG] [Wrapper.py] Registered help group 'Wrapper' with 4 commands
>[23:09:17] [Wrapper.py/INFO] Loading plugins...
>[23:09:17] [Wrapper.py/INFO] Loading plugin SmallBrother.py...
>[23:09:17] [Wrapper.py/DEBUG] [SmallBrother] Registered event 'player.dig'
>[23:09:17] [Wrapper.py/DEBUG] [SmallBrother] Registered event 'player.place'
>[23:09:17] [Wrapper.py/DEBUG] [SmallBrother] Registered event 'timer.second'
>[23:09:17] [Wrapper.py/DEBUG] [SmallBrother] Registered event 'server.started'
>[23:09:17] [Wrapper.py/DEBUG] [SmallBrother] Registered command 'sb'
>[23:09:17] [Wrapper.py/INFO] Loading plugin zombie.py...
>[23:09:17] [Wrapper.py/DEBUG] [zombie] Registered event 'player.message'
>[23:09:17] [Wrapper.py/DEBUG] [zombie] Registered event 'player.death'
>[23:09:17] [Wrapper.py/INFO] Loading plugin Gauntlet.py...
>[23:09:17] [Wrapper.py/INFO] Loading plugin teleport.py...
>[23:09:17] [Wrapper.py/DEBUG] [teleport] Registered help group 'Teleport' with 4 commands
>[23:09:17] [Wrapper.py/DEBUG] [teleport] Registered command 'tpa'
>[23:09:17] [Wrapper.py/DEBUG] [teleport] Registered command 'tpahere'
>[23:09:17] [Wrapper.py/DEBUG] [teleport] Registered command 'tpaccept'
>[23:09:17] [Wrapper.py/DEBUG] [teleport] Registered command 'tpdeny'
>[23:09:17] [Wrapper.py/INFO] Loading plugin Scarlet.py...
>[23:09:17] [Wrapper.py/DEBUG] [Scarlet] Registered event 'player.login'
>[23:09:17] [Wrapper.py/INFO] Loading plugin home.py...
>[23:09:17] [Wrapper.py/DEBUG] [home] Registered help group 'Home' with 2 commands
>[23:09:17] [Wrapper.py/DEBUG] [home] Registered command 'sethome'
>[23:09:17] [Wrapper.py/DEBUG] [home] Registered command 'home'
>[23:09:17] [Wrapper.py/INFO] Starting server...
>[23:09:21] [Server thread/INFO]: Starting minecraft server version 1.8.8
>[23:09:21] [Server thread/INFO]: Loading properties
>[23:09:21] [Server thread/INFO]: Default game type: CREATIVE
>[23:09:21] [Server thread/INFO]: Generating keypair
>[23:09:21] [Server thread/INFO]: Starting Minecraft server on *:25564
>[23:09:21] [Server thread/INFO]: Using epoll channel type
>[23:09:21] [Server thread/INFO]: Preparing level "world"
>[23:09:22] [Server thread/INFO]: Preparing start region for level 0
>[23:09:23] [Server thread/INFO]: Preparing spawn area: 36%
>[23:09:23] [Server thread/INFO]: Done (1.889s)! For help, type "help" or "?"
>[23:09:23] [Wrapper.py/INFO] Server started

However when I go to use a command in-game, say `/sethome` it does not work

![image](https://cloud.githubusercontent.com/assets/3958523/11322058/fc9c9b0c-90a6-11e5-9949-4600ce718e24.png)

Below are my configs

**wrapper.properties**

```
[General]
server-name = Akaria
command = java -Xms1G -Xmx1G -jar minecraft_server.1.8.8.jar nogui
auto-restart = True
auto-update-wrapper = True
auto-update-dev-builds = False
pre-1.7-mode = False
timed-reboot = True
timed-reboot-seconds = 86400
timed-reboot-warning-minutes = 5
debug = True
shell-scripts = False
auto-update-dev-build = False

[Backups]
enabled = True
backup-folders = ['server.properties', 'world']
backup-interval = 3600
backup-notification = True
backup-location = backup-directory
backup-compression = True
backups-keep = 10

[IRC]
irc-enabled = False
server = benbaptist.com
port = 6667
nick = MinecraftWrap
channels = ['#wrapper']
command-character = .
show-channel-server = True
autorun-irc-commands = ['COMMAND 1', 'COMMAND 2']
obstruct-nicknames = False
control-from-irc = False
control-irc-pass = password

[Proxy]
proxy-enabled = False
proxy-port = 25565
proxy-bind = 127.0.0.1
server-port = 25564
online-mode = True
max-players = 20

[Web]
web-enabled = False
web-bind = 0.0.0.0
web-port = 25565
web-password = password
web-allow-file-management = True
public-stats = True
```

**server.properties**

```
#Minecraft server properties
#Sat Nov 21 23:16:30 EST 2015
spawn-protection=16
max-tick-time=-1
generator-settings=
force-gamemode=false
allow-nether=true
gamemode=1
broadcast-console-to-ops=true
enable-query=false
player-idle-timeout=120
difficulty=2
spawn-monsters=true
op-permission-level=2
resource-pack-hash=
announce-player-achievements=true
pvp=true
snooper-enabled=true
level-type=DEFAULT
hardcore=false
enable-command-block=true
max-players=25
network-compression-threshold=256
max-world-size=29999984
server-port=25564
server-ip=
spawn-npcs=true
allow-flight=false
level-name=world
view-distance=10
resource-pack=
spawn-animals=true
white-list=true
generate-structures=true
online-mode=true
max-build-height=256
level-seed=
use-native-transport=true
enable-rcon=false
motd=Welcome to Akaria\!
```

I am currently running on

>root@crownless:/home/jason/Documents/minecraft-server# lsb_release -a
>No LSB modules are available.
>Distributor ID: Ubuntu
>Description:    Ubuntu 14.04.3 LTS
>Release:        14.04
>Codename:       trusty

Am I missing a step toward activating a plugin?

Thanks

**Comment by suresttexas00** [comment]
You must use proxy mode to use slash commands



[Proxy]
proxy-enabled = False
proxy-port = 25565
proxy-bind = 127.0.0.1
server-port = 25564
online-mode = True
max-players = 20

**Comment by suresttexas00** [comment]
You must use proxy mode to be able to use slash commands.

**Comment by suresttexas00** [comment]
and you must connect to the proxy port (25565).

**Comment by JasonBristol** [comment]
That did the trick, it is clear to me know how proxy is being used!

One thing I noticed however once running through the proxy is that my whitelist was no longer being picked up. I usually whitelist my server, but was unable to join with `white-list=true` in **server.properties**. Trying to reinitialize my white list with `/raw whitelist add colonel369` and `/raw whitelist reload` was unsuccessful.

I noticed I had to disable online mode in favor of the wrappers authentication handling. Does the wrapper/proxy abstract whitelisting?

**Comment by suresttexas00** [comment]
you will have to whitelist everyone again via the console because the UUIDs are different from online mode versus proxy mode

**Comment by suresttexas00** [comment]
One other thing about whitelisting and banning in proxy mode... the capitalization must match exactly

**Comment by JasonBristol** [comment]
Cleared whitelist and re-whitelisted folks through the console with proxy enabled, everything looks good right now. Thanks again for the help
