### ISSUE TITLE
Why send keep alives?

### ISSUE THREAD

**Issue by suresttexas00** [benbaptist/minecraft-wrapper#249]
at many places in the proxy code, something like this appears:

```
			elif self.state == 3:
				if self.client.version > 7:
					id = self.read("varint:i")["i"]
					if not id == None:
						self.send(0x00, "varint", (id,))
```

Why do we have to send these keep alives?  Why can't the proxy just let these packets pass back and forth between the server and client unmolested (i.e., just let the server and client handle their keep alive status?

Might seem pointless of me to ask, but this packet is also being changed by 1.9... not only that the packet number is different depending on whether it is client-bound or server-bound.

**Comment by benbaptist** [comment]
Because you're not always guaranteed to be connected to the same server, or ANY server - I've had the idea of implementing a limbo-connection to allow server restarts without causing everyone to disconnect. I can't rely on the actual server to send these properly as well, since they might change servers (i.e. player.connect()) and the server doesn't always send them in the right timings after a different connection has been made. Besides, I want Wrapper.py to be able to figure out if one or the other has disconnected on its own (i.e. client lost connection, or server froze up and isn't responding, or somehow both).

I really want to start working on this stuff again. I just get excited whenever I write these responses. Wrapper.py is fun to work on. I just wished BenBot wasn't taking up so much of my time. :( Eventually, I'll be able to slow down on BenBot updates and be able to work on more on other projects.

**Comment by suresttexas00** [comment]
I suppose I figured that is the reason, but I am finding that making that part of the code 1.9-functional is giving me fits.  It's hard to find the correct packet numbers and since it is not just 0x00 for both, I am having to make sure I am using the correct number and the correct direction for these.

**Comment by suresttexas00** [comment]
Well, I have started my migration to linux.  It started with a computer I got back (it had been a gift) due to a failed hard drive / inability to boot windows.  I replaced the HD and installed Linux Mint for the OS.  It worked so well, I installed it as a dual boot for another friend and it solved some issues where windows would give him fits with wireless connections.  The Linux handled the hardware better than the OEM's windows 8.  So, I decided to install Mint on my laptop too (still dual boot for now).  Once I get everything ironed out on this, I'll run some test servers and, if all goes well, I'll start migrating my production tower units 100% to Linux.

**Comment by suresttexas00** [comment]
It seems that your code is not doing anything with these... also, as I read the documentation, the keep alive is solely for the server's benefit (to verify client is still connected); If you restart a server, or someone transfers between servers, shouldn't they be disconnected or reconnected (from the server in  question) anyway??

```
Keep Alive
The server will frequently send out a keep-alive, each containing a random ID. 
The client must respond with the same packet.
Packet ID	State	Bound To	Field Name	Field Type	Notes
0x00	Play	Server	Keep Alive ID	VarInt	
```

from the sounds of the documentation, clients don't send keep-alives, except in response to a server keep-alive... So if a server does not send them (say, because wrapper is holding the client "in limbo"), won't the clients stay connected to the proxy anyway (unless the server "kicks" them)?

**Comment by benbaptist** [comment]
An idea I had for a future update was the ability to actually keep clients connected - and put them into a sort've 'limbo' state until the server came back online. Would've made server restarts slightly more seamless.

**Comment by suresttexas00** [comment]
But won't clients stay connected to wrapper anyway (providing they are not kicked)?  The keep alives are only prompted by the server...  server sends; client responds.. ??..??  The clients don't send the keep alives, they just respond, right?  Unless there is some client code that says "oh, the server has not sent me a keep alive for a while.." ?

**Comment by benbaptist** [comment]
yes, but the client disconnects when it doesn't receive anything. it is needed. and furthermore, I don't want Wrapper hanging around thinking something's connected when there isn't anything connected.

**Comment by suresttexas00** [comment]
Sure I understand all that, but... Are you 100% positive that a vanilla client will disconnect simply because It has not received a keep alive?  If so, after what interval?   If I were writing my own client, is there some guideline I would use (# of seconds, etc)?

**Comment by suresttexas00** [comment]
right now, wrapper replies to server keep alives and sends separate keep alives to the client... I understand you want wrapper to track that activity on the client end: I am just now more curious about the actual client behavior... Such knowledge might come on handy.
