### ISSUE TITLE
Use Linux native-transport for wrapper?

### ISSUE THREAD

**Issue by suresttexas00** [benbaptist/minecraft-wrapper#251]
use-native-transport	boolean	true	Linux server performance improvements: optimized packet sending/receiving on Linux
true - Enabled. Enable Linux packet sending/receiving optimization
false - Disabled. Disable Linux packet sending/receiving optimization

Is this supposed to be set for wrapper?  Does it make a difference?

**Comment by suresttexas00** [comment]
This does not seem to be hurting anything...

**Comment by benbaptist** [comment]
I doubt it makes a difference for Wrapper, but probably doesn't hurt. I bet I can make Wrapper 50x more efficient by using select.poll though.

**Comment by suresttexas00** [comment]
what is select?

**Comment by benbaptist** [comment]
It's hard to explain, but it's not really select particularly that we want but poll() - it just so happens that Python puts poll() functionality in the 'select' module. In general networking, select() is a system for reading from multiple file descriptors (in this case, sockets) without using multiple threads or such. It has a limit of 1024 file descriptors/sockets, and it generally isn't as memory and CPU efficient as poll. poll() is just a more efficient way of handling it, and works without a 1024 socket limit.

**Comment by suresttexas00** [comment]
I understood you were talking about poll; I was just referencing the module as a whole...  Poll is a part of select, right??

**Comment by benbaptist** [comment]
Yup!
