### ISSUE TITLE
Wrapper memory Usage

### ISSUE THREAD

**Issue by suresttexas00** [benbaptist/minecraft-wrapper#266]
So are there any ideas/guidelines/thumbrules that indicate how much memory wrapper uses on top of what the server is using?  If I am running -XMX of 6G, how much does wrapper add to the system's usage?  how is the memory managed by python?

**Comment by benbaptist** [comment]
It doesn't matter what you pass to memory allocation on the server itself - Python just uses what it wants.

**Comment by suresttexas00** [comment]
Have you tracked what python uses?  I am asking because I have 16G RAm and run a 6G server... can I use more (dedicated to MC)?  or will it start paging if I do?

**Comment by JasonBristol** [comment]
You can run the wrapper with a python profiler:

`python -m cProfile Wrapper.py`

This will give you process metrics. One thing to note is that the wrapper spawns shell scripts to perform tasks such as backups, the information you will collect is not a full picture.

All in all I doubt the wrapper uses any significant amount of memory compared to the greedy java jvm running the server jar itself. You could give the server 10G - 12G and still have enough to operate normally.

**Comment by suresttexas00** [comment]
Thanks!
