### ISSUE TITLE
Problem in player.py

### ISSUE THREAD

**Issue by suresttexas00** [benbaptist/minecraft-wrapper#270]
Ben, there is a problem right here:
```
	def getClient(self):
		if self.client == None:
			for client in self.wrapper.proxy.clients:
				try:
					if client.username == username:
						self.client = client
						return self.client
				except:
					pass
		else:
			return self.client
```

`if client.username == username:` - username is not defined here.

**Comment by JasonBristol** [comment]
Does this have anything to do with #227 or #191 ?

**Comment by suresttexas00** [comment]
I suppose that is possible, since a new client would not get returned and the class self value of the client starts out being False or None by default.  I don't know what Ben is doing here.  Maybe we need some more debug print lines here to see what is going on.

**Comment by suresttexas00** [comment]
Wow. 24 days and no Ben-Bot response :(

**Comment by suresttexas00** [comment]
This ought to be simple.. what is 'username' supposed to be or come from?  is it supposed to be passed from self (i.e., should be 'self.username')... what usernames is wrapper attempting to compare??

**Comment by suresttexas00** [comment]
looks like it should be self.username.

**Comment by suresttexas00** [comment]
#292
