### ISSUE TITLE
inventory issue?

### ISSUE THREAD

**Issue by suresttexas00** [benbaptist/minecraft-wrapper#273]
BenBaptist,

got kicked again while eating a golden enchanted apple...

Can you look this player dat file over to see if something is odd about it?  I just could not log in until I deleted this file.

https://www.dropbox.com/s/adb0dmngm45eq5e/3269fd15-5be9-3c2a-af6c-12147a760f78.dat?dl=0

**Comment by benbaptist** [comment]
Did you put your own code in? I can't really do anything about it if you've modified proxy.py so heavily.

**Comment by suresttexas00** [comment]
I just don't have a tool or know how to parse the NBT.  Once I know that, can probably debug it.  I probably reactivated the broken window inventory parsing or something...  I have not had time to look at it yet... What tools do you sue to browse these files?

**Comment by Sasszem** [comment]
NBTExploer? Works on window, but I think there's a Linux version...

**Comment by suresttexas00** [comment]
well, It does not matter now... the inventory is not the problem.. it is a bad packet somewhere.. a packet I now know is associated with eating a golden enchanted apple... when I get time, I wil get back to the wiki, find out all the packets that are exchanged during or associated with eating on both client/server and see which packets proxy might be interacting with in a bad way.

I may look for that Linux version.. very handy tool to have.

**Comment by suresttexas00** [comment]
Fixed.. just a typo in entity effect parsing.  FINAL finished #275
