### ISSUE TITLE
Solutions for multiple plugins using a single wrapper event

### ISSUE THREAD

**Issue by suresttexas00** [benbaptist/minecraft-wrapper#277]
Firstly, if we start making something with additional pull requests, I'd like for the pull request to be made against my 1.9 development branch (https://github.com/suresttexas00/minecraft-wrapper/tree/development) as well to avoid conflicts with Ben's current development version (until Ben approves the PR or writes a 1.9 version).

My "reflex" action to this issue is to create a "hook" plugin of some kind that would register all the wrapper events and then use the hook plugin to call each plugins event.  Wrapper would only call the hook's event.  The hook event would then call each plugin's event, in series, evaluating the results after each plugin's event and then deciding which/what payloads or return results to return to Wrapper.

I'm sure this function should probably be a part of Wrapper itself; maybe even a change to the registerEvent API.. like including a priority level to the event registration or something?

Thoughts? Obviously, I would like to see this done with as little complexity as possible...

**Comment by JasonBristol** [comment]
I agree, this kind of functionality should be native to the wrapper itself, and I think it would actually be a bit easier to implement. This is basically a change to the registerEvent API architecture that will allow it to route events to each plugin that registers them.

**Comment by suresttexas00** [comment]
The question of course is how to implement the ordering or what to do when plugin "A" returns a False (drop the packet for, say blockplace) and Plugin "B" returns True.. or in more extreme cases where two plugins will each attempt to mod the payload...

**Comment by JasonBristol** [comment]
Hmm this sounds like an opportunity for mutex locks, oh joy! This is kind of like threading in the sense that we may have two or more plugins competing for the same event.

Initially I see two options:

1. We disallow multiple plugins to hook into the same event (this is not ideal for many reasons)
2. We have plugins lock volatile resource (like payload or packet) and ensure that for the duration of their processing they maintain a handle on them before releasing the lock and allowing the next plugin to process.

Option #2 would require plugins to register events with some kind of priority so the API knows which to allocate the first lock to. We would need a locking mechanism which may require some abstraction of objects like payload (I think your new packet class does this already)

**Comment by suresttexas00** [comment]
Since different plugins may or may not know what their "proper" order should be with respect to each other, I kind of like the W3C model.  Any plugin that may "cancel" the payload would be set as capture = True and any plugin that might do a modification and/or cancel would be capture = False (bubbling). 

Capture events would be simple "informational" plugins (getting a player position to set a home) or would accept/deny such as a protection plugin blockPlace or a muting of a player from playerRawMessage.  Events marked as capture should only return True (default) or False.

Plugins that modify a payload like a playerRawMessage chat filter, could be set as bubbling.  Plugins using bubbling for their event would be responsible for returning the plugin as False or with the properly formatted payload (for processing by the next plugin).  Bubbling plugins should never return True; only false or the original (or modded) payload.

I think as long as the plugins are called sequentially with captures first, bubblings second, the specific order should not matter (as long as they go in series).

I guess we could have a few general "priority" codes that would help order it further.. so if you KNEW the plugin you were writing needed to be first on the bubbling list, for instance, you could ensure it was one of the first ones (provided no other plugin used a higher priority).

I know we are not at the point where 1000+1 different plugins are being made by different developers, so this might seem a silly conversation.  However, I now already have 2 plugins competing for chat events now.. one is a spam/profanity filter and the other is a "permission" system for the vanilla minecraft commands.  Right now only one or the other can work at a time.

**Comment by suresttexas00** [comment]
Or perhaps use a priority where 1-3 would be captures and 4-6 would be bubbling levels.

**Comment by Sasszem** [comment]
The problem is that if two plugins return two different resoults for the same event. If the writer of the plugins does a mistake, then the wrapper breaks.
Possible soulution is to check if the return datas are same(ignor eempty returns) and if they arent, raise an error. Also, there're some special cases where it's possible to have two diffrent resoults(like tab comletion), so handle them as well...

**Comment by suresttexas00** [comment]
I agree that differing return payloads is __The__ primary issue here.  I'm not sure if I like the prospect of using the Raise Error system since it breaks the wrapper program flow and results in a wrapper unreliability.  I don't have a solution.  I think what we were discussing _was_ developing a system to determine _which_ payload had priority, where a possible payload conflict exists.

Bear in mind that a False return may be just as valid (i.e. chat modifications or denials).

**Comment by Sasszem** [comment]
Yeah, but if that's a abortable event(like player.dig), then it would be 
better if returning false means that we don't allow that event. It's 
more natural.

---
Ezt az e-mailt az Avast víruskereső szoftver átvizsgálta.
https://www.avast.com/antivirus

**Comment by suresttexas00** [comment]
Of course,that is how we currently handle it.  Those are easy to handle.  I think those can simply be handled as "first to return false".  The ones I am concerned with are payload return types where a conflict may exist in the payloads.

**Comment by Sasszem** [comment]
So we need 3 types of return: Modify data, ignore event(Null) and cancel event. Correct?

**Comment by suresttexas00** [comment]
Yes; indeed, those events already exist (Null also being equivalent to True) in the present code:
Modify
Null/True
False

However, modify data could be conceptualized as an "array" of different possible modifications.  The code has to figure some way to:
1) decide which will be the valid modification.
or
2) Merge them somehow.
or
3) Prioritize the plugins and pass the payload sequentially through the plugins based on their priority A->B->C

**Comment by suresttexas00** [comment]
For the present, I am opting for something like this:

1) Each plugin event is passed to the requesting plugins in the sequence as-iterated through the self.events dictionary.

2) each plugin can -
     - Null/True (do nothing)
     - False (reject the event, thereby canceling it)
     - return a payload.  The payload must be valid.

3) Null/True - The plugin's event code ran.  No payload changes were made. The event caller return signal is not changed.

4) False - Any False encountered permanently sets the return call value to False.  Other plugins will get equal access to run their events, but they will not be able to affect the payload or return call value.

5) Return payload - if no plugins return False, the payload can be returned back to the event caller.  The new returned payload is then passed to the next registered plugin for processing by its event handler just as though it were the original payload.  The next plugin may likewise further modify the payload or False/None/True it.


The only remaining issue is the ordering of payload-returning plugins.  It will be random according to item 1).

Basic code idea:
```
    def callevent(self, event, payload):
        if event == "player.runCommand":
            if not self.wrapper.commands.playercommand(payload):
                return False

        # listeners is normally empty.  Supposed to be part of the blockForEvent code.
        for sock in self.listeners:
            sock.append({"event": event, "payload": payload})

        payload_status = True
        old_payload = payload  # retaining the original payload might be helpful for the future features.

        # in all plugins with this event listed..
        for plugin_id in self.events:

            # for each plugin...
            if event in self.events[plugin_id]:

                # run the plugin code and get the plugin's return value
                result = None
                try:
                    # 'self.events[plugin_id][event]' is the <bound method Main.__the_plugin_event_function>
                    # pass 'payload' as the argument for the plugin-defined event code function
                    result = self.events[plugin_id][event](payload)
                except Exception as e:
                    self.log.exception("Plugin '%s' experienced a problem calling '%s': \n%s",
                                       plugin_id, event, e)

                # Evaluate this plugin's result
                # every plugin will be given equal time to run it's event code.  however, if one plugin
                # returns a False, no payload changes will be possible.
                #
                if result is None:  # Don't change the payload status
                    pass
                elif result is False:  # mark this event permanently as False
                    payload_status = False
                elif result is True:    # Again, don't change the payload status
                    pass
                else:
                    # A payload is being returned
                    # if any plugin rejects the event, no payload changes will be authorized.
                    if payload_status is not False:
                        # the next plugin looking at this event sees the new payload.
                        payload, payload_status = result

        return payload_status
```
