### ISSUE TITLE
Project Collaborators / Organization

### ISSUE THREAD

**Issue by JasonBristol** [benbaptist/minecraft-wrapper#278]
I think it would be beneficial to the community that consumes Wrapper.py to have a couple other people capable of managing pull requests and issues. I know @benbaptist is often busy and may or may not address these tasks at a cadence that continues to seed development.

This is my ask -- is it possible to add at least one collaborator to this project (I think @suresttexas00 would be a good fit) to at least get some of these PRs moving. This will allow us to continue our development and share it with the community instead of having to manage a fork and have people push and or pull from there.

Let me know what you think

**Comment by benbaptist** [comment]
I've been thinking about this too. I was waiting because I wanted to build a better/proper build system/actual build bot/etc., but I think I'll just let that slide and work with what we have. I'm going to push the code that I currently have, get all the pull requests lined up, push a build and then start adding more collaborators.

**Comment by JasonBristol** [comment]
This will also help us clean up/organize our issues tracking so we can quickly and effectively address longstanding issues

**Comment by benbaptist** [comment]
Surest has already been a collaborator for a billion years now. :P

**Comment by suresttexas00** [comment]
I think he means someone who can approve pull requests and/or manage the issues tracker (some of these need to be closed due to lack of response, etc).

**Comment by JasonBristol** [comment]
Correct, I also think even access to our wiki or documentation will allow
us to flush it out, I often have periods of free time where I would be more
than willing to do some of these things. I think this will also help us
organize and address issues and development faster and more effectively

**Comment by suresttexas00** [comment]
@benbaptist , I think that the best thing to continue development is to create a new repo for bleeding edge development.  The repo with have two branches... "development", which will be our tested stable version that will then be used to feed PR's to your development branch, and 'uber', which will be a highly volatile version with frequent changes.  I will manage these two branches and periodically send a PR.

These branches will not update the build, and will just be copies of the build files you use.  They will only modify the source code.  I will periodically pull any changes you might make to development so it's base code remains updated with development.  There will be no 'master' branch.. that function will totally be on your page as always.

**Comment by suresttexas00** [comment]
Collaborator status is working and I have moved the code over.  We may start an experimental branch over here.
