### ISSUE TITLE
The intended function of player.connect() and how does wrapper handle multi-servers

### ISSUE THREAD

**Issue by suresttexas00** [benbaptist/minecraft-wrapper#279]
I am still very vague about how this stuff gets handled and its future direction.  If you can answer each question for us to keep this and maybe later include it in the API documentation...

First my own understanding of wrapper based on my primary mode of use (proxy mode).  So, wrapper runs on, say port 25565 on some address "1.2.3.4".  A server is running on 25566 (same IP/computer).
A client (or clients) connect to 1.2.3.4:25565 , the (top-level) wrapper.  The wrapper then processes everything from the client and then passes it to the server on 25566.

Assumptions/what I think now:
A) wrapper can only have one server running.

questions:
1) player.connect - how does it work.- player object becomes defunct and is transferred to new IP/port:

a) Is the client still connected to and remain connected to the original ip/port of the 
wrapper that it first connected to (the one the player clicked on to connect)?
b) Does player.connect() work with proxy mode?
c) Does the connection have to be to another server, or can it (should it) connect 
to another wrapper?
d) IF player.connect does work with proxy mode and the player remains connected 
to first wrapper, does that mean the packets are getting parsed by both wrappers
 (assuming second connection was to another wrapper)?  (Again, assuming proxy mode)
e)  Does the new IP/port have to be publicly accessible (i.e., a port forward to that
 port must exist)
b) assuming e) is "yes", how do you keep people from connecting directly?

I am sure there are more questions I have.. I know in the future you were wanting to implement a proxy mode that would work a bit like bungeecord and allow the servers to run in online mode...

**Comment by benbaptist** [comment]
a) Yes, the connection is still to Wrapper itself - the client does not support native server switching. Though it would be cool if it did (but also a huge security risk).
b) It's required for proxy mode. 
c) It can connect to other wrappers, provided they're in offline mode. I need to make sure it can forward the UUIDs, though. 
d) Yes, but the first wrapper ignores most packets and does not notify the plugins of events caused after they disconnect (the plugins only receive events for that particular server). 
e) No, it does not need to be publically accessible. 
b again) You can bind to 127.0.0.1 on wrapper/server itself to ensure it's not publically connectable. 

Yup! I'd love for Wrapper.py to fully become something that can work like BungeeCord. would be awesomesauce.

**Comment by suresttexas00** [comment]
If Wrapper connects playerA to serverA, but playerA runs a plugin command to connect to ServerB, how do plugins know which world the player is interacting with?  Based on the discussion thus far, I am under the impression that only one set of plugins is running the show (i.e., we are not connected to another offline wrapper)?  So when a player digs at 123, 65, 124 in serverB world, but those coordinates are protected in ServerA world.. will he be unable to dig?  If he sets a /home in serverA, does this overwrite (assume 1 home only) the /home he did on serverB world?
