### ISSUE TITLE
stop command stops and immediately reboot server

### ISSUE THREAD

**Issue by hhiru** [benbaptist/minecraft-wrapper#283]
When I enter "stop" in command prompt to stop the server, wrapper.py automatically reboot server preventing the complete stop. How can I stop the server without disabling the wrapper's auto-reboot feature?

Using latest wrapper version, latest 2.7.x python version and Minecraft 1.9

**Comment by benbaptist** [comment]
You'll want to type /halt (with the slash) to shutdown the wrapper itself.
If you wish to stop the server without shutting down Wrapper, /stop will
work. Putting a slash indicates that you are sending the command to Wrapper
and not directly to the server. Typing stop with no slash will just result
in a restart.

**Comment by hhiru** [comment]
Oh, thanks!

**Comment by suresttexas00** [comment]
This has actually been changed now.  start and stop are superceded by wrapper's /start and /stop... So this should not happen again.

'/stop' or 'stop' will stop the server legitimately so that it does not auto-restart.  If you DO want to restart it, use '/restart'
