### ISSUE TITLE
Ban-IP does not work

### ISSUE THREAD

**Issue by suresttexas00** [benbaptist/minecraft-wrapper#287]
I tried to ban someone tonight who has 100 alts... they used their own IP, but although the server bans the IP, they still get on.

**Comment by benbaptist** [comment]
Yes, because the server only sees the localhost connections (127.0.0.1)
instead of their actual IP. Wrapper.py needs to handle IP banning itself.

**Comment by suresttexas00** [comment]
Yea, that is what I thought [&#X02639]


________________________________

**Comment by suresttexas00** [comment]
I added the IP banning into wrapper.  It is part of PR #288.

**Comment by suresttexas00** [comment]
#292
