### ISSUE TITLE
Python 3

### ISSUE THREAD

**Issue by l33tlinuxh4x0r** [benbaptist/minecraft-wrapper#301]
Are there any plans to port this to the latest version of python?

**Comment by suresttexas00** [comment]
Yes, we are working towards making wrapper work with either 2.x or 3.x python.  We have other issues to address first, so we are not pursuing it at the moment, but we already have an item in to track this:
https://github.com/suresttexas00/minecraft-wrapper/issues/24

**Comment by suresttexas00** [comment]
I have a lot of bugs to iron out of this before I will be ready for PY3 updates.  I am heavily refactoring the proxy portions.  Once I get it working (only client.py is refactored and reasonably debugged), then we can revisit this.  I know wrapper is going to be chock full of problems with byte/string usages.

**Comment by suresttexas00** [comment]
I have made some really good progress with this, but there are more pressing issues to resolve and features that need added.  As I am working, I am adding the PY3 compatibility where I see I can.

**Comment by suresttexas00** [comment]
I have decided that I will start getting wrapper to at least be PY 3 compatible in non-proxy mode.  This should be pretty easy to do.  Proxy mode may require some real work since the whole thing (packet parsing) kind of depends on the way Py2 treats strings as bytes and bytes as ASCII strings.

**Comment by suresttexas00** [comment]
#400

**Comment by suresttexas00** [comment]
Just an FYI, if you are using storages; I made a fairly healthy change to the API.  Very important for plugin access to storage data! 
see item def getStorage:
https://github.com/benbaptist/minecraft-wrapper/blob/development/documentation/base.rst
