### ISSUE TITLE
Collaborators / Contributors

### ISSUE THREAD

**Issue by suresttexas00** [benbaptist/minecraft-wrapper#302]
In Player.py, this does not really do what you (@benbaptist) intended:
```
        self.username = username
        self.name = self.username  # just an alias - same variable
```
The two variables are _separate_ values and if you change one, you must change the other or they will differ.  Example:

```
class Clint:
    def __init__(self, usernameofplayer):
        self.username = usernameofplayer
        self.name = self.username  # just an alias - same variable


x = Clint("suresttexasoo")
print(x.name)
print(x.username)

x.username = "fungal"
print(x.name)
print(x.username)
```
will output:
```
/usr/bin/python2.7 /home/surest/projects/Wrapper/wrapper/utils/test.py
SurestTexas00
SurestTexas00
SurestTexas00
fungal

Process finished with exit code 0
```

The best way to fix this (picking one and not having an 'alias') will break some plugins.  I am going with ".username" for the player api.  I will update the 'standard plugins, like essentials.py, that would be broken by this.

**Comment by suresttexas00** [comment]
Yuk.. Too many plugins are using .name... I need to research a solution.

**Comment by suresttexas00** [comment]
Looks like this will do what is needed, leaving the wrapper code base to deal exclusively in ".username", while providing and alias for plugins.
```
        self.username = username
...

    @property
    def name(self):
        return self.username
```

**Comment by suresttexas00** [comment]
Keeping this open as FYI.. close it after reading.

**Comment by benbaptist** [comment]
Totally off-topic: since I haven't seen you do anything, I'm not sure if you knew that I added you a contributor. You've been a contributor for a few months now. :P Just making sure you knew.

Also, very interesting. This shows some of the stupid things I didn't understand with Python back in the day. I've learned a lot more about Python since - especially thanks to BenBot and such pushing my knowledge to its limits far more than even Wrapper ever did, thus resulting in me learning these kinds of things. 

Also, why did I even do .name in the first place? I don't get it. Was I really that lazy that I wanted a shortcut to .username that didn't involve me typing `user`? Man, laziness really got the best of me when doing Wrapper.py... which is the biggest reason why it suffered in the codebase more than anything else - moreso than my then-current knowledge of Python. :P

**Comment by suresttexas00** [comment]
I've fixed this in the experimental branch.  Once I am done with it, I'll pull that over.  So, we can close it here.  My fix is to add a "name" property to player, so it will not break any plugins.

**Comment by suresttexas00** [comment]
Would you mind if we moved wrapper into public open-source and remove the proprietary "my code" language from the copyright?

**Comment by suresttexas00** [comment]
Are you sure about that?  I seem to have '0' permissions of any kind. I can't even do minor things like close old issues or add labels...

**Comment by suresttexas00** [comment]
Ok... Now I understand the confusion... I am a "contributor" because you have approved a pull request or two of mine in the past, which causes GitHub to mark me as a contributor. There are six contributors:
https://github.com/benbaptist/minecraft-wrapper/graphs/contributors

Contributors have no permissions of any kind.  They are just people who have contributed some code to the wrapper code base over the years now.

However, I am not a "Collaborator"; which requires specific action from you...  Collaborators can approve pull requests, administer issues, apply labels, etc.  I can't do anything unless I am added as a Collaborator:
This is my page where I added jasonbristol as a Collaborator for the experimental branch we are working on:
![image](https://cloud.githubusercontent.com/assets/10001762/15231770/216d5d30-186b-11e6-8f3b-eb28f98f8a8e.png)

**Comment by benbaptist** [comment]
That's the page I added you to - but it was giving me weird "Internal Server Error occurred, try again later!" when I did it a while back. I just figured it had properly added you. I'll try it again.

**Comment by suresttexas00** [comment]
Works!  Got the invite.

**Comment by benbaptist** [comment]
Hooray!

**Comment by benbaptist** [comment]
No wonder why you weren't using that power all this time - Github didn't bloody add you!

**Comment by suresttexas00** [comment]
While I have you attention, what are your thoughts on Forge... Many of the `if self.version < 6: return True` statements you made to stop parsing forge packets are going to filter out vanilla clients in that version too... See my tirade on #186 and #187..

read those replies and tell me your thoughts....

**Comment by benbaptist** [comment]
That isn't to stop parsing Forge packets, it's, as you said, to stop parsing something below that version overall. I don't really know the context of what you're talking about, but I'm fairly certain that's what they're for. There's nothing Forge-specific there. Wrapper.py has not had proper Forge support yet for proxy mode, but it was always planned. There's other particular packets that need to be implemented but it isn't terribly easy as the documentation for the Forge-specific packets are (or were) sparse. You'll probably have better luck finding documentation on it now, but at the time it was a bit hard to find.

**Comment by suresttexas00** [comment]
You made those changes in response to #186, which is why I thought that (since 5 is the 1.7.10 and below versions)..

I'm not so sure about forge myself.  It's really a whole different protocol.. even the login is more complex...  We are certainly not ready to be implementing it at this point.  maybe once a really good stable release is out.  I'm still working on the one in my branch... There's a few things I want to iron out before we move that pull request.

**Comment by benbaptist** [comment]
yeah, definitely just getting a nice, rock-solid release out is probably better, and the stuff like that can come later.

**Comment by suresttexas00** [comment]
Oh, yes, one more item... Open source?  which licence would you prefer?
