### ISSUE TITLE
Community input on Storage.py storage objects

### ISSUE THREAD

**Issue by suresttexas00** [benbaptist/minecraft-wrapper#308]
Turning my attention to this area now because I think we have serious performance issues, like #196 and it appears [SurestTexas00 #152](https://github.com/suresttexas00/minecraft-wrapper/issues/152), and possibly even a component of #276 in this code.

1) the periodic save uses threading.. a thread that may not get closed if __DEL__ fails to set the self.abort for the thread.
Read the warnings : https://docs.python.org/3/reference/datamodel.html#object.__del__

2) the periodic thread is superfluous and we have enough thread instability and disk action going on anyway.  I think having the plugins handle their own .save() is sufficient...

Which is something else that worries me:  data races.  I'm sure we have TONS of them anytime more than one player (or 5) gets on.

MY first proposal is to get rid of the periodic save and associated threads... for which purpose I want to get anyone's input who is interested or has a view on it..

#  ? ? 

-----------------------
that aside we definitely need an improvement here, with methods of locking and allowing "partial updates where two plugins grabbed the storage object and modified it; but modified two different sections such that both updates should be compatible...

**Comment by benbaptist** [comment]
Yeah, the threads are an awful way of handling things. I definitely wasn't thinking scalability and such (having mass amounts of Storage objects) when writing this.

My idea isn't to change it to manual flushes, but rather to have one master thread handling/managing flushing all storage objects to disk. It'll go through one at a time and save if any changes were made. Another thing that would be nice is to use ujson if it's installed to take advantage of better performance. Do note, however, that ujson will crash under certain circumstances, i.e. if a variable is more than 256**2, etc. and the only way to get by this is to manually check the object that you're serializing for any large variables and killing them beforehand. There might be other issue that I'm unaware of, too, but I'm not sure. I have a function that I'll get to you soon that will strip objects of any bad integers/etc. recursively.

**Comment by suresttexas00** [comment]
I am thinking that a central solution might not be much better.  I could work ,but I think might be more trouble than its worth.  I actually am thinking the threads can work again with some modification.  I tried a central manager for the entity manager that seems to work well.  However, I have learned that it really is hard to take away 100% of all data race conditions, even with the locks.

What i have now with storage works pretty well, provided wrapper does not outright CRASH.

I actually think the problem with the old thread is that it tried a little __TOO__ hard by doing the deepcopies and comparing old and new objects and such.  I have found that even a deepcopy (my entity manager uses it) is subject to race conditions with the possibility of data changing in mid-iteration (while deepcopy is making the copy!).  I think the best thing would probably just have the threads do a somewhat infrequent (maybe like every 2-5 minutes) json save of the data.. and if said save fails due to a race, we let it go as an acceptable casualty in view of the fact that the shut down save will "save" the day.  The periodic saves are only there really for two reasons - 1) op to view the data by opening the disk file  2) in case of a crash, you don't lose everything.  For those purposes, what I propose should suffice.  Simple uncopied EAFTP may also prevent the weird data changing properties we were seeing.

Of course we have to ensure the threads terminate themselves properly, too.

While I have your attention ( :D ), I'd love to see your web/flask thing finished out.  I know absolutely nothing about that end of things.

**Comment by suresttexas00** [comment]
I should pull back yesterdays work so you have an up to date copy... 

I'm pretty happy with where it is now.  Working with ping-pong on the startup issues allowed be to fix a lot of issues that the "regular" "existing" "installation" never sees (because various folders and so forth are already created, etc).

My next item is proper name change handling, adding some api methods for working with entites, get the entity list accurate for 1.10 (polar bears!).. which means we probably have to go back to hard coding the lists since grahamcombe seems out of date., and may add a banlist() method for viewing bans.  That's the short list, any way... my promise is not to touch the stuff in management!  All yours!  ..and the IRC for now...  I don't use either, but I'm sure they need work.  We have outstanding issues on these.
