### ISSUE TITLE
Darkness3840 wrapper suggestions

### ISSUE THREAD

**Issue by suresttexas00** [benbaptist/minecraft-wrapper#319]
_Darkness3840 wrote_:

My suggestions to wrapper would be the following:
- [ ] Support for jline. This would probably be fairly challenging to implement, as jline is a Java library. However, it is a very useful handler. Jline is a Java library for handling console input. It makes it so all the console output from the server directly is shown correctly, with color if applicable(sponge, spigot, bukkit and forge have colored output at times). http://jline.sourceforge.net
- [ ] The ability to customize shutdown and restart messages
- [x] The ability to change what the prefix to commands is. (Instead of having '/'one could change it to '.') That is just a personal preference

**Comment by suresttexas00** [comment]
@Darkness3840 Please elaborate on item no. 2.  What shutdown startup messages (what source, server or wrapper, and what specific message).. bearing in mind the server says what is darn well wants...

**Comment by Darkness3840** [comment]
By "shutdown and startup messages" I meant the messages that are passed to the player when he/she is kicked because of the restart.

**Comment by suresttexas00** [comment]
I forgot, you can already do item 3 with your plugins (requires proxy mode):

In this sample, I used '--' in place of a slash:
```
    def playerRawMessage(self, payload):
        """ This is a client's chat/commands TO the server. """
        player = payload["player"]
        content = (payload["message"]).split(" ")

        if content[0][0:2] == "--":  # allow use of '--' instead of slash to prefix commands
            newcontent = "/%s" % content[0][2:]
            content[0] = newcontent

        # region put it back together for return
        returnedtext = " ".join(content)
        payload["message"] = str(returnedtext)
        return payload["message"]
```

**Comment by suresttexas00** [comment]
Now, watch out for changes here... the above presently works, but I may be changing that API a bit.  I think (for the sake of multiple plugins using the same event) that the payload format should be returned exactly as it was passed, which is presently not the case..

**Comment by Darkness3840** [comment]
I will be unable to use proxy mode, as I already have a bungeecord proxy established.

**Comment by suresttexas00** [comment]
Not a problem.. just set your wrapper mode to offline:
```
  "Proxy": {
    "convert-player-files": false, 
    "max-players": 1024, 
    "online-mode": false,  <===HERE 
    "proxy-bind": "0.0.0.0", 
    "proxy-enabled": true, 
    "proxy-port": 25564,  <== This port FROM bungee
    "server-port": 25565,  <==This port to server running in offline mode
    "spigot-mode": false  <== set to true for spigot (have not tested since 1.8)
  }
```

**Comment by suresttexas00** [comment]
Hope fully that works...

**Comment by Darkness3840** [comment]
I will be sure to check that out once I get time. Thanks

**Comment by suresttexas00** [comment]
One other thought before I retire for the night... If bungee proxies in online mode, the wrapper should be able to take the bungee port and proxy it to an offline mode server... So you might want wrapper to be in online mode.  So it should be set up something like (ports in [ ] ) ->

`Client -> [25565]->bungee->[25570]wrapper(inproxy)->[25571]Offlineserver`

This is how I am working to get wrapper used as a hub.  Except my version will use a separate hub server associated:
`Client -> [25565]->wrapper-hub(Online_inproxy)->[25570]wrapper-world1(Offline_inproxy)->
[25571]Offlineserver_world1`

**Comment by suresttexas00** [comment]
Build 145 adds the command prefix as a config item.  Wrapper console commands still retain '/'.  minecraft commands from the console are not prefixed at all.  Commands issued via the minecraft client use the configurable command prefix from the config for both wrapper and minecraft commands.

**Comment by suresttexas00** [comment]
#359 , #360
