### ISSUE TITLE
Command being typed gets carried off by console every time server generates output

### ISSUE THREAD

**Issue by Darkness3840** [benbaptist/minecraft-wrapper#326]
When I am typing a command in the console, what I am typing gets carried away with the output that the server is giving (every time there is a new line character, I believe). Example: http://imgur.com/1n7aAnn

**Comment by suresttexas00** [comment]
That is how every minecraft console works... since the server output and your input share the same window, I believe this is unavoidable...  why is your server spamming all that chunk generation output?

**Comment by Darkness3840** [comment]
The output is because I'm pre generating a world. Also, that did not occur when jline was being used. I'll look around to see if readline can be modified to support that.

**Comment by suresttexas00** [comment]
What did jline do?  Did it halt the output until you pressed the enter key?

**Comment by Darkness3840** [comment]
In jline, the output was still active, but the place where the command was being input had a '>' in front of it, and did not carry the text off as server was outputting.

**Comment by suresttexas00** [comment]
interesting.  I am used to the vanilla servers which carry the text off as well.  There also is not "prompt" of any kind (">"), which would be nice.

**Comment by Darkness3840** [comment]
Yeah. I don't know exactly how jline does it, but it's very useful

**Comment by suresttexas00** [comment]
All I can find on stackoverflow was this: http://stackoverflow.com/questions/25342420/keep-console-input-line-below-output
and the suggested module: https://docs.python.org/2/howto/curses.html

**Comment by Darkness3840** [comment]
I think you guys should incorporate that into the wrapper. Would be pretty helpful

**Comment by suresttexas00** [comment]
I am not sure it can yet... at least it could be way more complicated to implement than it is worth.  I think perhaps a command to mute the server output (temporarily, perhaps with a preset time limit) would be better.

**Comment by suresttexas00** [comment]
I have a plugin that does the same sort of thing while I am running commands in-game...

**Comment by Darkness3840** [comment]
Alright. What is that plugin called though?

**Comment by Darkness3840** [comment]
There is something called jython. Could be worth looking in to: https://wiki.python.org/jython/ConsoleChoices

**Comment by suresttexas00** [comment]
If I deviate from pure python, it would be to Cython, not jython.  However, were are really not looking to switch languages.  Even though these implementations of Python (mostly) use the same python source code ("MOSTLY"), and claim to be "python", they require a whole new program (interpreter), a whole other "thing" people have to install on their system (not just PIP, but a real install), and must be updated weeks/months/years after the corresponding version of Python is complete.

**Comment by suresttexas00** [comment]
Just one of my custom plugins (the reason "I" came to use wrapper - the create vanilla server "bukkit-like" plugins).

**Comment by Darkness3840** [comment]
Will you be implementing ncurses/curses into wrapper?

**Comment by suresttexas00** [comment]
Not likely.  I will try the escape sequences.

**Comment by suresttexas00** [comment]
also, see #319 (not sure you got the notification on this

**Comment by Darkness3840** [comment]
Okay

**Comment by suresttexas00** [comment]
This one is beyond my paygrade.

**Comment by Darkness3840** [comment]
Thats pretty fair

**Comment by suresttexas00** [comment]
I can't presently change the cursor behavior, but with build 142, you can specify items in core/mcserver.py's `self.spammy_stuff` variable that will mute console spam that matches the items you specify.

**Comment by Darkness3840** [comment]
I'm sorry I haven't been responding for the past few days. I've been fairly busy.

**Comment by suresttexas00** [comment]
No problem

**Comment by suresttexas00** [comment]
I am thinking I am going to be able to fix this by formatting all output with ANSI escape coding using "\033[F" + printed server line + '/n'... (go up one line, print the text, go back down).  My servers aren't spammy enough to test it.  I'll have to insert a plugin that spams server console lines..

However, based on some comments I found, there is a small possibility it may not work in your PuTTY sessions.

**Comment by suresttexas00** [comment]
I'll have a build for this shortly, but, for now, it will breaks/bypass readline usage (so no arrow keys!).  backspace is working, though.  Also, wrapper's own logger outputs will still carry text upwards.

to turn it back off (to use readline), set config item
```
    "Misc": { 
        "use-readline": False 
    }
``` 
to True

**Comment by suresttexas00** [comment]
Build 148 will make wrapper's output respect the user's input as well.

**Comment by suresttexas00** [comment]
I am stalled with any further progress:
https://github.com/magmax/python-readchar/issues/20

so, no arrow keys.  However, your scrolling issue is totally fixed.

**Comment by suresttexas00** [comment]
This has been a VERY nice enhancement over the vanilla console (even without arrow keys!).  It has been nice to backspace over mistakes, retype them, and see what you are doing!  I am still watching [This](https://github.com/magmax/python-readchar/issues/20), but am closing this issue.

**Comment by suresttexas00** [comment]
Have implemented left/right arrow keys (for insert edits), up/down (for command history), and delete/backspace, as well as original design to prevent scroll-off.
