### ISSUE TITLE
A new issue, just moved the server

### ISSUE THREAD

**Issue by AnanyaIG** [benbaptist/minecraft-wrapper#372]
So I moved servers recently and when I tried to run the wrapper, I had this error.

> Wrapper.py/proxy.py:4: DeprecationWarning: the md5 module is deprecated; use hashlib instead
> Traceback (most recent call last):
>   File "/usr/lib/python2.6/runpy.py", line 122, in _run_module_as_main
>     "__main__", fname, loader, pkg_name)
>   File "/usr/lib/python2.6/runpy.py", line 34, in _run_code
>     exec code in run_globals
>   File "Wrapper.py/__main__.py", line 8, in <module>
> ImportError: No module named importlib
> 
> 

To back this, I have already installed python 2.7 updated and latest pip. Although I've already searched and it seems that pip is somehow broken(?). And while installing pkg_resources, I got this error which I couldn't find a way to fix.

> `Collecting pkg-resources
> /usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:315: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#snimissingwarning.
>   SNIMissingWarning
> /usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:120: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
>   InsecurePlatformWarning
>   Could not find a version that satisfies the requirement pkg-resources (from versions: )
> No matching distribution found for pkg-resources
> `

If you guys need any more info, I'd be happy to provide it to you. It was running just fine before I moved. I even tried updating the Wrapper.py but it didn't work.

**Comment by suresttexas00** [comment]
You are using the master branch?

**Comment by suresttexas00** [comment]
I think you just have an error in your pip setup.

Your error indicates you need to do this:
https://urllib3.readthedocs.io/en/latest/user-guide.html#ssl-py2

**Comment by suresttexas00** [comment]
Your operating system is..?

When you say you "moved" your servers, do you mean:
1) you moved the files to a new machine
or
2) you moved the machine(s) to a different physical location?
or
3) you moved the files on the same machine to a different folder?

**Comment by AnanyaIG** [comment]
I tried `pip install urllib3[secure]` and I couldn't follow the rest as to where to put 
> >>> import urllib3
> >>> urllib3.disable_warnings()

So yeah. Kinda stuck there.

And to respond to moving situation:

I'm on debian 7.0 x64. I was on the same before the move. By move I mean, I physically moved servers and hosts.

**Comment by AnanyaIG** [comment]
And yes, I'm using the master branch.

**Comment by suresttexas00** [comment]
physically moved servers...  I presume you mean you moved the files to a different host's computers (file transfer to different machines)?  If so;

do you have physical access to the hardware or is everything over a terminal or application of some kind?

**Comment by AnanyaIG** [comment]
Yeah, everything's over terminal. I have remote access to the server tho. But since it's debian, no VNC. It's just SSH terminal.

**Comment by suresttexas00** [comment]
The master branch is getting pretty old now and has some issues with deprecation of many of its library imports (like the md5 module).  If there is a problem of some kind, we might try patching the error.  However, as far as I know, the importlib is a still a valid import.

Just curious, what features of wrapper do you use and what version of minecraft do you run (maybe master is not the better branch to run..)

**Comment by AnanyaIG** [comment]
I run the latest minecraft version, 1.11. And it worked fine before I moved servers. And yeah, I don't really use proxy mode, but I used to use web UI, but seeing the errors and stuff, I turned it off and the errors still persist.

**Comment by AnanyaIG** [comment]
So what do you suggest, I shall get the development branch?

**Comment by suresttexas00** [comment]
I'd say that having to do everything over terminals is part of the problems you have not just with this, but probably the IRC issue too.

Yes, I would suggest the developement branch, even without proxy mode.  Also, since that is the one I am testing/developing, I can fix errors faster as I am more familiar with the code base (and it is in better shape).

Web is still broke (probably) for dev (as I have assigned that to Ben) and IRC is untested... but otherwise it is much nicer.

**Comment by AnanyaIG** [comment]
Could you please let me know your issue with working over terminals? I can perform almost everything on the terminal. Whatever you want me to. So please let me know about it.

All I need is IRC lol. That's basically it. And are there any issues with CPU usage spikes or stuff? Since I need to keep the CPU in check, although it never triggered anything ever before, but since it's the dev branch, so that's the reason I'm asking it.

**Comment by suresttexas00** [comment]
The config setup has changed quite a bit, so the dev will need a few starts to configure itself.. then you will need to peruse the wrapper.properties.json and adjust them accordingly.  here is the comments on the items (from wrapper/core/config.py):

```
NEWCONFIG = {
    "Backups": {
        # Automatic backups with automatic backup pruning. Interval is in seconds.
        "backup-compression": False,
        # Specify files and folders you want backed up.  Items must be in your server folder (see 'General' section)
        "backup-folders": [
            "server.properties",
            "world"
        ],
        "backup-interval": 3600,
        "backup-location": "backup-directory",  # this location will be inside wrapper's directory
        "backup-notification": True,
        "backups-keep": 10,
        "enabled": False
    },
    "Gameplay": {
        "use-timer-tick-event": False,  # not recommended.  1/20th of a second timer option for plugin use. May
                                        # impact wrapper performance negatively.
    },
    "Entities": {
        "enable-entity-controls": False,  # enable entity controls.
        "entity-update-frequency": 4,  # how often the entity processor updates world entity counts
        "thinning-frequency": 30,  # how often thinning of mobs runs, in seconds.  a large difference between this and
                                   # the entity update frequency will ensure no 'overkill" occurs.
        "thinning-activation-threshhold": 100,  # when mobs < this number, thinning is inactive (server or player)
        "thin-Cow": 40,  # Example, starts thinning Cow > 40.  Name must match exactly.  Overrides 'thin-any-mob'.
        "thin-Sheep": 40,  # another example
        "thin-Chicken": 30  # because they are especially annoying
    },
    "Updates": {
        "auto-update-branch": None,  # Use one of the names listed herein (i.e. 'stable-branch')
        "auto-update-wrapper": False,  # If True, an "auto-update-branch" must be specified.
        # You can point these to another branch, if desired.
        "stable-branch": "https://raw.githubusercontent.com/benbaptist/minecraft-wrapper/master/build/version.json",
        "dev-branch": "https://raw.githubusercontent.com/benbaptist/minecraft-wrapper/development/build/version.json",
    },
    "Misc": {  # look 'n' feel type customizations
        "command-prefix": "/",  # if you change this, no minecraft command will work. Bug or feature? TODO not sure.
        "reboot-message": "Server is conducting a scheduled reboot. The server will be back momentarily!",
        "default-restart-message": "Server restarting...",
        "stop-message": "Stopping The Minecraft Server",
        "use-readline": False  # using readline is likely to be more-cross platform, but does not use wrapper's ability
                               # to keep console keystroke entries visually intact while server produces output.
    },
    "General": {
        "auto-restart": True,
        # You will need to update this to your particular server start command line.
        "command": "java -jar -Xmx2G -Xms1G server.jar nogui",
        "encoding": "UTF-8",
        # Set this to read the console properly for pre-1.7 servers.  DO NOT use proxy mode for pre-1.7 servers!
        "pre-1.7-mode": False,
        "server-directory": ".",  # Using the default '.' roots the server in the same folder with wrapper. Change
                                  # this to another folder to keep the wrapper and server folders separate.
                                  # Do not use a trailing slash.
                                  # '/full/pathto/the/server'
        "server-name": "Minecraft Server",
        "shell-scripts": False,
        "timed-reboot": False,
        "timed-reboot-seconds": "86400",
        "timed-reboot-warning-minutes": 5,
        "auto-update-branch": "deprecated",  # moved to group "Updates"
        "auto-update-dev-build": "deprecated",  # no separate item for wrapper/dev-build.
        "auto-update-wrapper": "deprecated",  # moved to group "Updates"
        "stable-branch":  "deprecated",  # moved to group "Updates"
        "dev-branch":  "deprecated",  # moved to group "Updates"
    },
    "IRC": {
        # This allows your users to communicate to and from the server via IRC and vise versa.
        # _________________________________
        "autorun-irc-commands": [
            "COMMAND 1",
            "COMMAND 2"
        ],
        "channels": [
            "#wrapper"
        ],
        "command-character": ".",
        "control-from-irc": False,
        "control-irc-pass": "password",
        "irc-enabled": False,
        "nick": "MinecraftWrap",
        "obstruct-nicknames": False,
        "password": None,
        "port": 6667,
        "server": "benbaptist.com",
        "show-channel-server": True,
        "show-irc-join-part": True
    },
    "Proxy": {
        # This is a man-in-the-middle proxy similar to BungeeCord, which is used for extra plugin functionality.
        # online-mode must be set to False in server.properties. Make sure that the server is not accessible directly
        # from the outside world.
        # _________________________________
        # Note: the online-mode option here refers to the proxy only, not to the server's offline mode.  Each server's
        # online mode will depend on its setting in server.properties
        # _________________________________
        # It is recommended that you turn network-compression-threshold to -1 (off) in server.properties
        # for fewer issues.
        # _________________________________
        "convert-player-files": False,
        "max-players": 1024,
        "online-mode": True,  # the wrapper's online mode, NOT the server.
        "proxy-bind": "0.0.0.0",
        "proxy-enabled": False,
        "proxy-port": 25565,  # the wrapper's proxy port that accepts client connections from the internet. This
                              # port is exposed to the internet via your port forwards.
        "server-port": "deprecated",  # This port is autoconfigured from server console output now.
        "spigot-mode": False
    },
    "Web": {
        "public-stats": True,
        "web-allow-file-management": True,
        "web-bind": "0.0.0.0",
        "web-enabled": False,
        "web-password": "password",
        "web-port": 8070
    }
}
```

**Comment by suresttexas00** [comment]
The dev branch does very well with memory.

**Comment by suresttexas00** [comment]
so did you ever get the IRC working on the master branch.. last I heard was this:
https://github.com/benbaptist/minecraft-wrapper/issues/261

**Comment by AnanyaIG** [comment]
Nah, I never got it working. I did hell lot of stuff but never worked. I had to move stuff over on my local machine, and back to a new host and then a lot happened, and one day it started working. I can't provide any info to guys for debugging it since I wasn't aware that it'd start working.

Again, I'll just backup the old wrapper.properties and files just in case and get the dev branch's Wrapper.py and run it. I'll configure it accordingly and let you guys know.

**Comment by suresttexas00** [comment]
So it did start working again at some point?

**Comment by suresttexas00** [comment]
I'd be interested to know if IRC works under dev.

**Comment by AnanyaIG** [comment]
Well, if it did, that'd be good. But it won't be under the same circumstances. So I don't think it'd be of any help in reference to the older [https://github.com/benbaptist/minecraft-wrapper/issues/261](url) issue.

**Comment by suresttexas00** [comment]
"a lot happened, and one day it started working." - so it DID start working again for a while under master?

**Comment by suresttexas00** [comment]
I will probably close that old thread issue then.  If a new error is generated, start a new issue.

**Comment by AnanyaIG** [comment]
So when I try running the new Wrapper.py, I get this error.

>  Traceback (most recent call last):
  File "/usr/lib/python2.6/runpy.py", line 122, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.6/runpy.py", line 34, in _run_code
    exec code in run_globals
  File "Wrapper.py/__main__.py", line 5, in <module>
  File "Wrapper.py/core/wrapper.py", line 24, in <module>
  File "Wrapper.py/proxy/base.py", line 8, in <module>
  File "Wrapper.py/utils/encryption.py", line 14, in <module>
ImportError: No module named Crypto.PublicKey

**Comment by AnanyaIG** [comment]
Also, I'd really love to know how do you insert codes so that the formatting isn't messed, the way you did here: https://github.com/benbaptist/minecraft-wrapper/issues/372#issuecomment-264718025

**Comment by suresttexas00** [comment]
to insert code snippets, enclose them in three backticks ' ` ' before the last line and and three after the last line.
'```

code

'```

**Comment by suresttexas00** [comment]
Sounds like you need pycrypto installed.

**Comment by suresttexas00** [comment]
However, I thought you were not using proxy?

**Comment by AnanyaIG** [comment]
I'm not using proxy, I don't even have a config file. And I already have pycrypto installed.

**Comment by suresttexas00** [comment]
I am creating a patch now.

**Comment by suresttexas00** [comment]
New code pushed...

**Comment by AnanyaIG** [comment]
Will check it now.

**Comment by suresttexas00** [comment]
Hold on, it still has an error...

**Comment by suresttexas00** [comment]
It probably did not affect the function in your case, but I had a typo.  All set now.

**Comment by AnanyaIG** [comment]
Okay

**Comment by suresttexas00** [comment]
This is a good test, because my system always has these modules, so these kinds of errors never get detected in my tests. :)

**Comment by AnanyaIG** [comment]
Still no luck. Same error message. I'll try to update and upgrade somethings and then I'll let you know. Also, could it be that it's using the python2.6 libraries and stuff which is cause the problems? Since I've got Python 2.7 installed as well.

**Comment by suresttexas00** [comment]
can you provide me with the server output and the error again?

**Comment by suresttexas00** [comment]
I would certainly update to the 2.7 libraries

**Comment by suresttexas00** [comment]
I enclosed the offending import in a try-except.. and in a different line.  the error message should be different.

**Comment by AnanyaIG** [comment]
This is the new one

```
Traceback (most recent call last):
  File "/usr/lib/python2.6/runpy.py", line 122, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.6/runpy.py", line 34, in _run_code
    exec code in run_globals
  File "Wrapper.py/__main__.py", line 5, in <module>
  File "Wrapper.py/core/wrapper.py", line 24, in <module>
  File "Wrapper.py/proxy/base.py", line 10, in <module>
  File "Wrapper.py/proxy/clientconnection.py", line 17, in <module>
  File "Wrapper.py/utils/encryption.py", line 14, in <module>
ImportError: No module named Crypto.PublicKey
```

**Comment by suresttexas00** [comment]
I just noticed.. you are running Py 2.6, not 2.7.

**Comment by suresttexas00** [comment]
Thanks.. actually, that is a different error.

**Comment by AnanyaIG** [comment]
Should I default to 2.7?  I'd hate to think that it'd have an effect on the current python stuff which are using python 2.6.

**Comment by suresttexas00** [comment]
I'd say just execute just wrapper with py2.7.. however, your dependencies you pipped are all probably 2.6

**Comment by suresttexas00** [comment]
let me fix this error first and we'll see...

**Comment by suresttexas00** [comment]
Build 155..

**Comment by AnanyaIG** [comment]
On it.

**Comment by AnanyaIG** [comment]
This is what I came up with. Also, this time I'll try to run it with python 2.7 if that's okay with you.
```
Traceback (most recent call last):
  File "/usr/lib/python2.6/runpy.py", line 122, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.6/runpy.py", line 34, in _run_code
    exec code in run_globals
  File "Wrapper.py/__main__.py", line 5, in <module>
  File "Wrapper.py/core/wrapper.py", line 28, in <module>
  File "Wrapper.py/core/plugins.py", line 5, in <module>
ImportError: No module named importlib
```

**Comment by suresttexas00** [comment]
now we are back to that LOL

**Comment by suresttexas00** [comment]
It may just be a 2.6 thing..
Is there a reason not to convert to 2.7?

**Comment by suresttexas00** [comment]
2.6 is getting pretty old now.

**Comment by AnanyaIG** [comment]
Nah, I think I will. I was onto something with 2.6 but I think I'll take it on another environment. And yeah, 2.6 is pretty old.

**Comment by suresttexas00** [comment]
yea, i'd do a full 2.7.x install including updating pip and all dependencies.

**Comment by suresttexas00** [comment]
maybe try this:
`sudo -H pip install importlib`

**Comment by suresttexas00** [comment]
Since our end-game is python 3 anyway, I may just limit official support to python 2.7.x in the code startup messages.

**Comment by AnanyaIG** [comment]
Yeah. I just tried running the dev branch, and I must say lol, things are really looking up. But there are things which need fixing. The server is offline, the IRC bot is still connected to the server. Wrapper is down I think. But the bot is still on IRC.

**Comment by AnanyaIG** [comment]
Correction: I closed Wrapper.py, but there are still instances for the server itself running. The IRC bot echoed that the server is now stopping. I was kicked out of the server, the server isn't reachable, but the IRC bot is on IRC and I still see the server running on the process list.

**Comment by AnanyaIG** [comment]
Also, I was alerted about this error while running it.

```
[2016-12-04 14:14:21] [Wrapper.py/ERROR]: ^[[31;40;1mPlugin 'IRC'
experienced an exception calling 'irc.join':
'dict' object has no attribute 'decode'^[[0m
Traceback (most recent call last):
  File "Wrapper.py/core/events.py", line 55, in callevent
    result = self.events[plugin_id][event](payload)
  File "Wrapper.py/core/irc.py", line 122, in onchanneljoin
    self.messagefromchannel(channel, "&a%s &rjoined the channel" % nick)
  File "Wrapper.py/core/irc.py", line 114, in messagefromchannel
    self.javaserver.broadcast("&6[%s] %s" % (channel, message))
  File "Wrapper.py/core/mcserver.py", line 311, in broadcast
    self.chattocolorcodes(json.loads(processcolorcodes(message)).decode(self.encoding)))
AttributeError: 'dict' object has no attribute 'decode'
[2016-12-04 14:14:28] [Wrapper.py/INFO]: ^[[32;40mServer started^[[0m
```

**Comment by suresttexas00** [comment]
Did you use /halt to stop the wrapper?  If you kill wrapper forceably, the server can still run in the background.

**Comment by suresttexas00** [comment]
Glad to hear it is an improvement.  So the original issue is fixed?

**Comment by suresttexas00** [comment]
Do you have the ability to restart the machine over terminal?  This is usually the best way to clear problem when ports and dead network processes and such are involved.

**Comment by suresttexas00** [comment]
For new errors like this one above, please re-post each one as a separate issue titled "IRC errors #[]"

**Comment by AnanyaIG** [comment]
Yeah, I do have the ability to do everything over the terminal. Also, I will post the errors that way from the next time.

Thanks for the help.

**Comment by suresttexas00** [comment]
i'll let you know when I have an idea about this one error.. even errors that seem benign like this one tend to crap wrapper out due to the exception calling process.

**Comment by suresttexas00** [comment]
That error is puzzling me now... per the code, that line should only run if your minecraft server version is less that 1.7?

**Comment by suresttexas00** [comment]
Ah... maybe this is a symptom of the server not being there...

**Comment by AnanyaIG** [comment]
Maybe, but the server is there, and the version is 1.11. The latest one.

**Comment by suresttexas00** [comment]
I may create a push with some print statements to debug this

**Comment by AnanyaIG** [comment]
Okay, but it might get late for me to reply, since I'm working on other things as well 😄 So yeah :)

**Comment by suresttexas00** [comment]
If you can try it now and give me a copy of the console readout.

**Comment by suresttexas00** [comment]
another problem may be the code line:
`if isinstance(message, dict):`
is not doing the same thing as `if type(message) is dict`, causing the dictionary message contents to be processed with string methods.

**Comment by suresttexas00** [comment]
I have thoroughly debugged and fixed the broadcast api that created this error.  However, the version thing still mystifies me.

after I push the next code, you will not get this error, but, the server output will depend on what version it detects.  1.6.4 and under will broadcast with the say command and 1.7 and above will use tellraw.


`tellraw @a {"text": "", "extra": [{"obfuscated": false, "underlined": false, "bold": false, "italic": false, "color": "white", "text": "", "clickEvent": {}, "strikethrough": false}, {"obfuscated": false, "bold": false, "color": "dark_purple", "text": "[WrapperCraft] welcome fahgoot!", "strikethrough": false, "underlined": false, "italic": false}]}`

versus

`say §f§5[WrapperCraft] welcome fahgoot!` (pre-1.7)

The difference in game being:
![image](https://cloud.githubusercontent.com/assets/10001762/20869542/d7ffa9c6-ba42-11e6-9e6c-acbe7518a81c.png)

where:
```
channel = "WrapperCraft"
message = "welcome fahgoot!"
```

#378

**Comment by suresttexas00** [comment]
In future errors (where they happen soon after the start). please enclose a cut/paste of the full console output.  This allows me to trace program flow and maybe spot the causes of errors.
