### ISSUE TITLE
Terminal no longer shows input after running Wrapper.py

### ISSUE THREAD

**Issue by l33tlinuxh4x0r** [benbaptist/minecraft-wrapper#406]
When running Wrapper.py, input to the server shows up on the wrong line and then when the server is stopped the terminal no longer shows any input on the new line and has to be restarted to show input again.

**Comment by suresttexas00** [comment]
ok... what version and build are we talking about?

Usually odd console behavior like this follows wrapper errors. Were there any?

There is also an option in the config for "use-readline".  Try setting it to "true".

**Comment by suresttexas00** [comment]
The failure of the console to produce output is certainly an error.  However, please define what you meant about the "wrong" line.  When 'use-readline' is set to `false`, the wrapper is _designed_ to write it's output one live above the cursor.  This was to address #326 .  Turning "use-readline" to true puts wrapper's output back top the default behavior.

**Comment by l33tlinuxh4x0r** [comment]
Wrong line was what you just described input above the current line in terminal... setting use-readling to true fixed both issues. Maybe this should be the default?

I am using Linux.

**Comment by suresttexas00** [comment]
It probably should be the default.  I am not concerned about the placing of hte output, as this is a nice feature to prevent "losing" your place while typing.  I am more concerned with the loss of console output.  I would like to investigate that further.  any information you have about any errors or manner in which the wrapper was stopped and whether you can type anything to the console would be helpful.

**Comment by suresttexas00** [comment]
Unfortunately, with that feature, I was unable to make it as full featured and store past inputs or use the arrow keys :( .. so using the default is also better in some ways.

**Comment by l33tlinuxh4x0r** [comment]
It would be like in the text box that you just typed into if it didn't show your text. In terminal when I type "exit" I cannot see it but it runs when I press enter. Also if I run a command that is supposed to show me some output it appears blank. I can just exit and restart terminal and it works again but it should not function in this way.

**Comment by l33tlinuxh4x0r** [comment]
Also, I ma using python 3.6 if that matters.

**Comment by suresttexas00** [comment]
Ok, the output from a program will get over-written; that is a good point.  The regular server output and wrapper's logging get "pushed up" in this mode, which normally averts your issue.

1) How long does it work for after restarting?
2) If I can get a log readout from the session during which it fails...
3) how are you stopping wrapper?

**Comment by suresttexas00** [comment]
fyi, using a wrapper `log` item in the plugin (versus a print statement) will also give you output to re-align properly.  if you do use a print statement, terminating it with a '\n' will push the output up and keep it from being over-written (say, if you are using prints to debug or something).

**Comment by suresttexas00** [comment]
I am REALLY interested in why wrapper stops console output sometimes.  This is a _very_ old error that has been around for a while.

**Comment by l33tlinuxh4x0r** [comment]
1. My terminal works flawlessly once I restart it. But every time I start the wrapper it gets messed up again. 
2. No failure just when I close the wrapper.
3. I use ctrl+c to close the server. Is there a better way? the typical /stop doesn't close the server by default.

**Comment by suresttexas00** [comment]
try using /halt.  That is the proper way.
does your typing output ever look similar to this screenshot (I am typing /halt here, but have not typed the 't' yet..):
![image](https://cloud.githubusercontent.com/assets/10001762/21786072/4133b09a-d690-11e6-8957-0152e6dece51.png)

**Comment by suresttexas00** [comment]
also, whether by control-c or '/halt', you should see lines that say the plugins disabled and wrapper storages save successfully.

![image](https://cloud.githubusercontent.com/assets/10001762/21786103/722d35fe-d690-11e6-8106-236cd8bc22f2.png)

**Comment by l33tlinuxh4x0r** [comment]
Yes my typing looks like that by default. (use-readline=false)
Using /halt instead of ctrl+c fixes the issue. I will see where the problem is happening on ctrl+c... It might not be shutting down all of the way.

**Comment by suresttexas00** [comment]
also, please verify that the /help (wrapper's help, with the '/') looks ok...

**Comment by l33tlinuxh4x0r** [comment]
do the up arrow, previous input keys work for you? They don't work for me use-readline=false or use-readline=true.

**Comment by suresttexas00** [comment]
ok... it may be something that is very specific to the way each distro/kernel handles control stops like ctrl-c and ctrl-z.  Only ctrl-z messes up my console.

**Comment by suresttexas00** [comment]
No, unfortunately, the code i use for doing the key reads does not read arrow keys properly (at this time).  That is an improvement I would like to make to remember last lines typed..

**Comment by l33tlinuxh4x0r** [comment]
ctrl-z has no negative effects for me.

**Comment by suresttexas00** [comment]
The way this works is that instead of the usual python input to read a typed line, I have a module that reads individual characters as you type them, and re-displays them one line above.  It erases an re-writes the line  for each keystroke you type.

Interesting about ctrl-z ... does wrapper save its storages and shutdown properly??

**Comment by l33tlinuxh4x0r** [comment]
yep

**Comment by suresttexas00** [comment]
It sounds like our two machines have opposite mappings of ctrl-c and ctrl-z.

**Comment by suresttexas00** [comment]
I have a warning in the README.md not to use ctrl-z.. perhaps it should say ctrl-c also...

**Comment by l33tlinuxh4x0r** [comment]
ctrl-z puts the program to "sleep" type `fg` in the same terminal to bring it back. Then you can exit the program normally.

**Comment by suresttexas00** [comment]
That does not happen in my machine (linux mint).  ctrl-z halts the program forcibly.

**Comment by suresttexas00** [comment]
I've learned a few things since I wrote that.. maybe I will revisit the code.  I had hit a roadblock before and moved on to other things (like getting the Python 3 working).

**Comment by l33tlinuxh4x0r** [comment]
weird. ctrl+c is supposed to halt the program forcibly and ctrl-z is supposed to be sleep is yours backwards? does your ctrl+c sleep?

**Comment by suresttexas00** [comment]
ctrl-c is caught by wrapper as a SIGINT.

Here is the wrapper code that handles the shutdowns:

```
    def signals(self):
        signal.signal(signal.SIGINT, self.sigint)  # CTRL-C
        signal.signal(signal.SIGTERM, self.sigint)  # (I dont think wrapper will actually be allowed to stop SIGTERM)

    def sigint(*args):
        self = args[0]  # We are only interested in the self component
        self._halt()

    def _halt(self):
        self.javaserver.stop("Halting server...")
        self.halt = True

    def shutdown(self):
        self._halt()
```

**Comment by suresttexas00** [comment]
as I said, on mine, ctrl-z halts the code forcibly.

**Comment by l33tlinuxh4x0r** [comment]
weird

**Comment by suresttexas00** [comment]
I googles this up and it looks like I should be supporting a `SIGTSTP` (ctrl-z)  as well as `SIGTERM` AND `SIGINT` .. but it appears you are correct about the way they __should__ work.

**Comment by suresttexas00** [comment]
I thing the SIGTSTP should be implemented as being the same as the server /freeze command.  pausing wrapper execution is just _not_ a good idea.

**Comment by suresttexas00** [comment]
I am guessing both wrapper _and the server_ are receiving the SIGTSTP... meaning the server will hang in the background, messing up wrappers proc() into the server.  I will re-investigate this whole schema we use for wrapper signal handling...

**Comment by suresttexas00** [comment]
I believe i will have this fixed... but first, can you tell me if just typing 'fg' _after_ wrapper is stopped restores the console part?

**Comment by l33tlinuxh4x0r** [comment]
`fg` restores console. As far as ctrl+z goes the server is still running in the background. Only the wrapper is stopped.

**Comment by suresttexas00** [comment]
I think I can get both fixed.  I should have a complete pull in a bit.  I'll let you know; I'm still testing it.

**Comment by l33tlinuxh4x0r** [comment]
Upon further investigation the server stops also and restarts when `fg` is run. However it doesn't kick the player until a ping timeout so you get about 15 seconds of being on a server that isn't there.

**Comment by suresttexas00** [comment]
try #407 by typing /update-wrapper in the console (I want to see if that works).

**Comment by suresttexas00** [comment]
Also let me know which ctrl-key maps to which SIG (it will say the sig in the terminal).

**Comment by suresttexas00** [comment]
Yea, I should re-implement the 'kick' for wrapper shutdowns.

**Comment by l33tlinuxh4x0r** [comment]
ctrl+c is sig and /update-wrapper works flawlessly.

**Comment by suresttexas00** [comment]
which sig? INT or TSTP?

**Comment by l33tlinuxh4x0r** [comment]
sigint

**Comment by suresttexas00** [comment]
ctrl-z should also work and neither should leave a phantom server restarting in the background.

**Comment by l33tlinuxh4x0r** [comment]
ctrl+z is sigtstp

**Comment by suresttexas00** [comment]
and the console input should be restored after the exit.

**Comment by suresttexas00** [comment]
Cool.

**Comment by l33tlinuxh4x0r** [comment]
yes they both work. I was just about to comment that.

**Comment by suresttexas00** [comment]
so we are all good?  I just need to look into making my keyreader better...

**Comment by l33tlinuxh4x0r** [comment]
yeah, all good. Just get the keyreader working and I think that it will be good. I am going to start to try to write some python plugins using the api.

**Comment by suresttexas00** [comment]
ok. Thanks for the help testing.

**Comment by suresttexas00** [comment]
For now, even though this part is fixed, you should `use-readline` to true for now while you are developing your plugins, in case you want to debug with prints and make sure an error does not get over-written.  I probably will go ahead and make it the default.
