### ISSUE TITLE
Wrapper crash: 'module' object has no attribute 'SIGTSTP'

### ISSUE THREAD

**Issue by Katipo007** [benbaptist/minecraft-wrapper#430]
Wrapper crashes on launch with the error 'module' object has no attribute 'SIGTSTP'

Known affected versions:
- Version [0, 11, 2] (development build #195)
- Version [0, 11, 2] (development build #196)

Version [0, 11, 2] (development build #195)'s logs were more useful but I have included both

---

Logs from Version [0, 11, 2] (development build #195):
logs/wrapper/wrapper.log:
> [2017-02-07 22:18:48] [root/INFO]: Logging configuration file (logging.json) located and loaded, logging configuration set!
[2017-02-07 22:18:48] [Wrapper.py/WARNING]: 'readline' not imported.  This is needed for proper console functioning
[2017-02-07 22:18:48] [Wrapper.py/INFO]: Wrapper.py started - Version [0, 11, 2] (development build #195)
[2017-02-07 22:18:48] [Wrapper.py/CRITICAL]: Wrapper.py crashed - stopping server to be safe ('module' object has no attribute 'SIGTSTP')
Traceback (most recent call last):
  File "Wrapper.py\__main__.py", line 67, in main
    wrapper.start()
  File "Wrapper.py\core\wrapper.py", line 142, in start
    self.signals()
  File "Wrapper.py\core\wrapper.py", line 219, in signals
    signal.signal(signal.SIGTSTP, self.sigtstp)
AttributeError: 'module' object has no attribute 'SIGTSTP'
[2017-02-07 22:18:48] [Wrapper.py/INFO]: Disabling plugins...
[2017-02-07 22:18:48] [Wrapper.py/INFO]: Disabling plugins...Done!
[2017-02-07 22:18:48] [Wrapper.py/CRITICAL]: Wrapper has no server instance. Server is likely killed but could still be running, or it might be corrupted! ('NoneType' object has no attribute 'stop')
Traceback (most recent call last):
  File "Wrapper.py\__main__.py", line 83, in main
    wrapper.javaserver.stop("Wrapper.py crashed - please contact the "
AttributeError: 'NoneType' object has no attribute 'stop'

logs/wrapper/wrapper.errors.log:

> [2017-02-07 22:18:48] [Wrapper.py/CRITICAL]: Wrapper.py crashed - stopping server to be safe ('module' object has no attribute 'SIGTSTP')
Traceback (most recent call last):
  File "Wrapper.py\__main__.py", line 67, in main
    wrapper.start()
  File "Wrapper.py\core\wrapper.py", line 142, in start
    self.signals()
  File "Wrapper.py\core\wrapper.py", line 219, in signals
    signal.signal(signal.SIGTSTP, self.sigtstp)
AttributeError: 'module' object has no attribute 'SIGTSTP'
[2017-02-07 22:18:48] [Wrapper.py/CRITICAL]: Wrapper has no server instance. Server is likely killed but could still be running, or it might be corrupted! ('NoneType' object has no attribute 'stop')
Traceback (most recent call last):
  File "Wrapper.py\__main__.py", line 83, in main
    wrapper.javaserver.stop("Wrapper.py crashed - please contact the "
AttributeError: 'NoneType' object has no attribute 'stop'

-----

Logs from Version [0, 11, 2] (development build #196):
logs/wrapper/wrapper.log

> [2017-02-08 21:26:21] [root/INFO]: Logging configuration file (logging.json) located and loaded, logging `configuration` set!
`[2017-02-08` 21:26:21] [Wrapper.py/INFO]: Wrapper.py started - Version [0, 11, 2] (development build #196)
`[2017-02-08` 21:26:21] [Wrapper.py/CRITICAL]: Wrapper.py crashed - please report this. ('module' object `has` no attribute 'SIGTSTP')

logs/wrapper/wrapper.errors.log
> [2017-02-08 21:26:21] [Wrapper.py/CRITICAL]: Wrapper.py crashed - please report this. ('module' object has no attribute 'SIGTSTP')

---

Will be glad to assist in any other way I can

**Comment by Katipo007** [comment]
Also here is my wrapper.properties.json encase anything there is a problem:

[wrapper.properties.json.zip](https://github.com/benbaptist/minecraft-wrapper/files/760094/wrapper.properties.json.zip)

**Comment by suresttexas00** [comment]
Hi.. Is this a windows or Unix type system?  I'll try:except this signal out and give you a build shortly.  I suspect may be going on here than just that...

**Comment by suresttexas00** [comment]
I am merging the build now (number 197). 
1) I note that you don't have readline (this could cause issues)
2) in your config, make sure this is the proper start parameters for your server (server jar name and so forth):
```
  "General": {
    "auto-restart": true, 
    "command": "java -jar -Xmx2G -Xms1G minecraft_server.jar nogui", 
    "encoding": "UTF-8", 
    "server-directory": ".", 
    "shell-scripts": false, 
    "timed-reboot": false, 
    "timed-reboot-minutes": 1440, 
    "timed-reboot-warning-minutes": 5
```

**Comment by Katipo007** [comment]
> Is this a windows or Unix type system?

Windows 10

> I note that you don't have readline (this could cause issues)

When I used "use-readline" enabled I get this warning in the logs:

`[2017-02-09 11:31:56] [Wrapper.py/WARNING]: 'readline' not imported.  This is needed for proper console functioning. Press <Enter> to acknowledge...`

So I had disabled it to see if it had something to do with issue #430, I had tested it with readline both enabled and disabled.


> in your config, make sure this is the proper start parameters for your server (server jar name and so forth)

I can confirm that "command": "java -jar -Xmx2G -Xms1G minecraft_server.jar nogui" works


Just ran Version [0, 11, 2] (development build #197), successfully starts and appears to be fine now. Tested with both readline enabled and disabled, although with readline enabled I still get the warning
`[2017-02-09 11:31:56] [Wrapper.py/WARNING]: 'readline' not imported.  This is needed for proper console functioning. Press <Enter> to acknowledge...`

**Comment by suresttexas00** [comment]
use-readline is not the 'readline module'.  There is a missing import "readline" that your system does not have.  It should be there regardless of whether you enable wrapper's anti-scrollback or not (I should rename these things).

Windows 10 :( LOL I knew it had to happen sooner or later.

**Comment by suresttexas00** [comment]
This was probably because windows does not have a Freeze ability with applications. It is good to have a Windows tester again.  I switched to Linux a year or two ago and have not used wrapper in Windows since.  The 'SIGTSTP' is (I think) Ctrl-X or Z and does not work on Windows which only supports halting with Ctrl-C.

**Comment by suresttexas00** [comment]
Fixed this by adding code to wrapper.py:
```
        try:
            # lacking in Windows
            signal.signal(signal.SIGTSTP, self.sigtstp)
        except:
            pass
```
