### ISSUE TITLE
proxy/packet.py send_slot doesn't support string type item ids

### ISSUE THREAD

**Issue by Katipo007** [benbaptist/minecraft-wrapper#435]
Discovered this whilst trying to update 'example-plugins/open.py'

Caused by 'proxy/packet.py' line 410
The newer versions of minecraft use strings rather than shorts for item ids. A special case needs adding to handle newer and older versions of minecraft to send the respective data type.

I would add a pull request but I haven't been through enough existing code yet to see how you handle version specific cases

**Comment by suresttexas00** [comment]
Which versions?

open.py was written by someone else, so it could be a plugin specific problem.

I will look at it.  For information, packet.py is just the generic parser.  The actual definitions (how a particular packet is parsed are in the parse_cb.py and parse_sb.py modules.

However, back to SLOT data.  slot is not a string and never will be.  It is a binary format; defined here:
http://wiki.vg/Slot_Data
See our wiki for links to the minecraft protocol wiki.

I am betting the error is elsewhere (probably the plugin itself is broken/incomplete.

**Comment by suresttexas00** [comment]
I don't particularly recommend you try to manually operate windows with the API.  The API currently only really exists to help manage wrapper's accounting of a players inventory (slots 0-9 in particular) so we can know what item a player is holding.

**Comment by suresttexas00** [comment]
I will apologize in advance if I take a while to move on these things, as a I have a number of projects, plus my regular job that are very busy for me at this time.  having a nice window managing API would be a very useful thing.

**Comment by suresttexas00** [comment]
OK, what I would like is for a full traceback of the error and the values the plugin was passing.  Then I will know what caused the error and how to fix it.

Even though the error shows up in packet.py, that is just the manifest point.  Packet.py line 410 is a low-level binary parser of the "slot" packet datatype.  Within the slot, data is specially encoded and is not a string or number.  It is most likely that open.py is passing incorrect data... in fact, it may not be compatible at all with the new proxy package.

**Comment by suresttexas00** [comment]
This has been outstanding for a while and I believe I addressed the base concern... The Slot data type in minecraft is a binary "slot".  It is not a string or anything.

**Comment by suresttexas00** [comment]
Feel free to respond with the traceback information and a copy of the codelines involved.  Please use the most recent wrapper version when doing so..
