### ISSUE TITLE
Backup not running

### ISSUE THREAD

**Issue by jspanos71** [benbaptist/minecraft-wrapper#445]
I have run wrapper for over a year (on the dev branch as of about 6 months ago) without proxy mode.  I use it for the auto-backup feature mostly.  I updated to the latest dev branch last weekend and now the backups are not running.  I changed logging level to debug and I never see wrapper trying to run a backup.    I have checked the config and everything is the same as it has been for the last year.  Did something change to break it?

OS: Ubuntu server 16.04.2
Wrapper: Dev build 201 
Minecraft: Snapshot 17w06a

**Comment by suresttexas00** [comment]
Can you get me a copy of the wrapper.properties.json?

**Comment by jspanos71** [comment]
Sure thing


[wrapper_properties.zip](https://github.com/benbaptist/minecraft-wrapper/files/808999/wrapper_properties.zip)

**Comment by suresttexas00** [comment]
Fixed in build 202.  The event timer was not running (serious problem, not just for backups!)

Thanks for bringing this to light.

**Comment by jspanos71** [comment]
That fixed it.  Thanks!

**Comment by suresttexas00** [comment]
You're welcome.  Thanks for submitting this.
