### ISSUE TITLE
Is it possible to backup multiple folders?

### ISSUE THREAD

**Issue by lukeeexd** [benbaptist/minecraft-wrapper#479]
In wrapper.properties Is it possible to add more folders to the backup line? "backup-folders = ['world']"

If so what is the way to do it, thanks

**Comment by suresttexas00** [comment]
backup folders is a List/Tuple of strings.  So:
```
backup-folders = ['world/playerdata', 'wrapper-data', 'world/data', 'world/DIM1', 'world/DIM-1' ]
```
I'll look at the code again; my example shows multiple relative paths.  I'm not sure how the code parses paths that are not in the same folder with Wrapper.

**Comment by lukeeexd** [comment]
They would be in the same folder. I would like to backup the nether and the end as well as the world folder

**Comment by suresttexas00** [comment]
backing up "world" (the world folder) will back up the entire world which includes all the various subfolders, like the end, nether, and playerstats.

**Comment by suresttexas00** [comment]
The end and nether are the ones like 'world/DIM__x__'

**Comment by lukeeexd** [comment]
But I have world_nether and world_the_end folders?

**Comment by suresttexas00** [comment]
I see.. because of the Spigot thing.. RIght ;)

Ok, so (assuming they are in the same folder with wrapper??);
```
backup-folders = ['world', 'world_nether, 'world_the_end' ]
```

I forgot Bukkit/Spigot does that...

**Comment by suresttexas00** [comment]
you may want to add you server jar too:
`backup-folders = ['spigot_server.jar', 'world', 'world_nether, 'world_the_end' ]`

you know, case they break a build.. :)

**Comment by lukeeexd** [comment]
https://gyazo.com/ca3194eb7f0455a7b83f1a512671ef8c Yep in same folder. Will try and report back

**Comment by suresttexas00** [comment]
My interest in Wrapper was finding a way to ditch Bukkit/Spigot (after the DMCA takledown fiasco) and always be able to use the newest vanilla without waiting for spigot updates... So it's been a while since I used them.

**Comment by lukeeexd** [comment]
Just realized that there's no point in me in backing up the end and the nether.

Also while I have you. For the automatic restart any way of getting a custom message for what it will say instead of "server closed" or even just "Server is restarting" if custom message cant be done

**Comment by suresttexas00** [comment]
check in the configfile 'wrapper.properties.json'.  I believe there is a section for that.

**Comment by lukeeexd** [comment]
I don't seem to have that file. Only have wrapper.properties

**Comment by suresttexas00** [comment]
What version of wrapper are you running??

**Comment by suresttexas00** [comment]
are you sure the extension is not being "hid" from you by the OS?
you will know it is the right file because the content will be json, not plain text.

**Comment by lukeeexd** [comment]
Latest. I can see other json's like banned users, whitelist etc

**Comment by suresttexas00** [comment]
Give me a folder view like you did before.  You should also have a superops.txt and logging.json.  Latest being 0.13.5?

**Comment by lukeeexd** [comment]
Oh no I have 0.7.6 thought I had the latest going by this http://wrapper.benbaptist.com/download.php

Whats the easiest way to update?

**Comment by suresttexas00** [comment]
There is a autoupdate feature in the wrapper.properties.  Try that first.  If that does not work, then manually download the file Wrapper.py file from the github repo:
https://github.com/benbaptist/minecraft-wrapper

**Comment by suresttexas00** [comment]
You're in for some changes .... try to read the docs and figure it out:

https://github.com/benbaptist/minecraft-wrapper/blob/master/documentation/index.md

read thoroughly:
https://github.com/benbaptist/minecraft-wrapper#installation

**Comment by lukeeexd** [comment]
The autoupdate doesn't work. It says something like I dont have some package and links to stackoverflow. Tried fixing it but cant find how. I just need to download wrapper.py? Don't need to run the wget command shown?

**Comment by suresttexas00** [comment]
you can download manually or with WGET.

What packages are you missing?

**Comment by lukeeexd** [comment]
requests apparently. Using ubuntu

**Comment by lukeeexd** [comment]
Ah got the lastest now.

**Comment by suresttexas00** [comment]
you will need requests

**Comment by lukeeexd** [comment]
when I type "python2.7 Wrapper.py" its just spamming this https://gyazo.com/bbed8dd13c65fddf0d657e1ccce93ecb over and over

**Comment by suresttexas00** [comment]
that means the server is not getting successfully started.  check your startup line in the wrapper.properties.json.  by the way, you should just cut and paste connsole content instead of screen shots.  You can fit more content that way enclose it with \`\`\` three backticks and line feed, the CODE then another set of three back ticks(\`\`\`)

\`\`\`
console text lines
\`\`\`

**Comment by lukeeexd** [comment]
java -jar -Xmx1G -Xms1G PaperSpigot-latest.jar nogui

Literally exact same from the previous version I was on

**Comment by suresttexas00** [comment]
Give me the full wrapper.properties.json and a full readout of the console text from start until the repeat errors happen.

**Comment by lukeeexd** [comment]
I’m in bed now can’t give you much until tomorrow. And the console is just spamming what I linked. It’s like it’s blinking it’s going that fast

**Comment by suresttexas00** [comment]
OK, I need that console output before the error happens.  Ctrl break it as soon as the error starts and paste the console out put here when you get a chance.

**Comment by lukeeexd** [comment]
Only problem with that is, I run it in screen. So when I control break it, the text that appears after cuts most of the error

**Comment by suresttexas00** [comment]
are you running this on a hosted server or something?  don't you have access to the console so you can scroll back to the problem area?

**Comment by lukeeexd** [comment]
Yeah it’s a dedicated server. I use screen to run the servers in so when I close the ssh client it keeps running and screen doesn’t display everything it cuts parts off. Guess I could just run it out of screen to get the full error.

**Comment by suresttexas00** [comment]
Please do that.  I need a full console readout.  I am not omniscient :)

**Comment by lukeeexd** [comment]
Error:
```[12:09:12] [root/INFO]: Logging configuration file (logging.json) located and loaded, logging configuration set!
[12:09:12] [Wrapper.py/INFO]: Wrapper.py started - Version 233 (stable)
[12:09:12] [Wrapper.py/INFO]: Loading plugins...
[12:09:12] [Wrapper.py/INFO]: Starting server...
[12:09:12] [Wrapper.py/INFO]: Starting server...
Dec 09, 2017 12:09:12 PM org.bukkit.craftbukkit.Main main
SEVERE: f is not a recognized option
Option                                  Description
------                                  -----------
-?, --help                              Show the help
-C, --commands-settings <File: Yml      File for command settings (default:

-P, --plugins <File: Plugin directory>  Plugin directory to use (default:

-S, --spigot-settings <File: Yml file>  File for spigot settings (default:

-W, --universe, --world-container, --   World container


-b, --bukkit-settings <File: Yml file>  File for bukkit settings (default:

-c, --config <File: Properties file>    Properties file to use (default:

-d, --date-format <SimpleDateFormat:    Format of the date to display in the

--demo                                  Demo mode
-h, --host, --server-ip <String:        Host to listen on

--log-append <Boolean: Log append>      Whether to append to the log file

--log-count <Integer: Log count>        Specified how many log files to cycle

--log-limit <Integer: Max log size>     Limits the maximum size of the log

--log-pattern <String: Log filename>    Specfies the log filename pattern

--log-strip-color                       Strips color codes from log file
--noconsole                             Disables the console
--nojline                               Disables jline and emulates the

-o, --online-mode <Boolean:             Whether to use online authentication

-p, --port, --server-port <Integer:     Port to listen on

--paper, --paper-settings <File: Yml    File for paper settings (default:

-s, --max-players, --size <Integer:     Maximum amount of players

--server-name <String: Name>            Name of the server (default: Unknown

-v, --version                           Show the CraftBukkit Version
-w, --level-name, --world <String:      World name

[12:09:13] [Wrapper.py/INFO]: Starting server...
Dec 09, 2017 12:09:13 PM org.bukkit.craftbukkit.Main main
SEVERE: f is not a recognized option
Option                                  Description
------                                  -----------
-?, --help                              Show the help
-C, --commands-settings <File: Yml      File for command settings (default:

-P, --plugins <File: Plugin directory>  Plugin directory to use (default:

-S, --spigot-settings <File: Yml file>  File for spigot settings (default:

-W, --universe, --world-container, --   World container


-b, --bukkit-settings <File: Yml file>  File for bukkit settings (default:

-c, --config <File: Properties file>    Properties file to use (default:

-d, --date-format <SimpleDateFormat:    Format of the date to display in the

--demo                                  Demo mode
-h, --host, --server-ip <String:        Host to listen on

--log-append <Boolean: Log append>      Whether to append to the log file

--log-count <Integer: Log count>        Specified how many log files to cycle

--log-limit <Integer: Max log size>     Limits the maximum size of the log

--log-pattern <String: Log filename>    Specfies the log filename pattern

--log-strip-color                       Strips color codes from log file
--noconsole                             Disables the console
--nojline                               Disables jline and emulates the

-o, --online-mode <Boolean:             Whether to use online authentication

-p, --port, --server-port <Integer:     Port to listen on

--paper, --paper-settings <File: Yml    File for paper settings (default:

-s, --max-players, --size <Integer:     Maximum amount of players

--server-name <String: Name>            Name of the server (default: Unknown

-v, --version                           Show the CraftBukkit Version
-w, --level-name, --world <String:      World name

[12:09:13] [Wrapper.py/INFO]: Starting server...
Dec 09, 2017 12:09:13 PM org.bukkit.craftbukkit.Main main
SEVERE: f is not a recognized option
Option                                  Description
------                                  -----------
-?, --help                              Show the help
-C, --commands-settings <File: Yml      File for command settings (default:

-P, --plugins <File: Plugin directory>  Plugin directory to use (default:

-S, --spigot-settings <File: Yml file>  File for spigot settings (default:

-W, --universe, --world-container, --   World container


-b, --bukkit-settings <File: Yml file>  File for bukkit settings (default:

-c, --config <File: Properties file>    Properties file to use (default:

-d, --date-format <SimpleDateFormat:    Format of the date to display in the

--demo                                  Demo mode
-h, --host, --server-ip <String:        Host to listen on

--log-append <Boolean: Log append>      Whether to append to the log file

--log-count <Integer: Log count>        Specified how many log files to cycle

--log-limit <Integer: Max log size>     Limits the maximum size of the log

--log-pattern <String: Log filename>    Specfies the log filename pattern

--log-strip-color                       Strips color codes from log file
--noconsole                             Disables the console
--nojline                               Disables jline and emulates the

-o, --online-mode <Boolean:             Whether to use online authentication

-p, --port, --server-port <Integer:     Port to listen on

--paper, --paper-settings <File: Yml    File for paper settings (default:

-s, --max-players, --size <Integer:     Maximum amount of players

--server-name <String: Name>            Name of the server (default: Unknown

-v, --version                           Show the CraftBukkit Version
-w, --level-name, --world <String:      World name

[12:09:13] [Wrapper.py/INFO]: Starting server...
^C[12:09:13] [Wrapper.py/INFO]: Wrapper.py received SIGINT; halting...

[12:09:13] [Wrapper.py/INFO]: Stopping Minecraft server with reason: Halting server...
Dec 09, 2017 12:09:13 PM org.bukkit.craftbukkit.Main main
SEVERE: f is not a recognized option
Option                                  Description
------                                  -----------
-?, --help                              Show the help
-C, --commands-settings <File: Yml      File for command settings (default:

-P, --plugins <File: Plugin directory>  Plugin directory to use (default:

-S, --spigot-settings <File: Yml file>  File for spigot settings (default:

-W, --universe, --world-container, --   World container


-b, --bukkit-settings <File: Yml file>  File for bukkit settings (default:

-c, --config <File: Properties file>    Properties file to use (default:

-d, --date-format <SimpleDateFormat:    Format of the date to display in the

--demo                                  Demo mode
-h, --host, --server-ip <String:        Host to listen on

--log-append <Boolean: Log append>      Whether to append to the log file

--log-count <Integer: Log count>        Specified how many log files to cycle

--log-limit <Integer: Max log size>     Limits the maximum size of the log

--log-pattern <String: Log filename>    Specfies the log filename pattern

--log-strip-color                       Strips color codes from log file
--noconsole                             Disables the console
--nojline                               Disables jline and emulates the

-o, --online-mode <Boolean:             Whether to use online authentication

-p, --port, --server-port <Integer:     Port to listen on

--paper, --paper-settings <File: Yml    File for paper settings (default:

-s, --max-players, --size <Integer:     Maximum amount of players

--server-name <String: Name>            Name of the server (default: Unknown

-v, --version                           Show the CraftBukkit Version
-w, --level-name, --world <String:      World name

[12:09:13] [Wrapper.py/INFO]: Disabling plugins...
[12:09:13] [Wrapper.py/INFO]: Disabling plugins...Done!
[12:09:13] [Wrapper.py/INFO]: Plugins disabled
[12:09:13] [Wrapper.py/INFO]: Wrapper Storages closed and saved.
[12:09:13] [Wrapper.py/INFO]: Ending threads, please wait...```

Config:
```
{
  "Backups": {
    "backup-compression": false, 
    "backup-folders": [
      "server.properties", 
      "world"
    ], 
    "backup-interval": 3600, 
    "backup-location": "backup-directory", 
    "backup-notification": true, 
    "backups-keep": 10, 
    "enabled": false
  }, 
  "Entities": {
    "enable-entity-controls": false, 
    "entity-update-frequency": 4, 
    "thin-Chicken": 30, 
    "thin-Cow": 40, 
    "thin-Sheep": 40, 
    "thin-cow": 40, 
    "thin-zombie_pigman": 200, 
    "thinning-activation-threshhold": 100, 
    "thinning-frequency": 30
  }, 
  "Gameplay": {
    "use-timer-tick-event": false
  }, 
  "General": {
    "auto-restart": true, 
    "command": "java -jar -Xmx1G -Xms1G PaperSpigot-latest.jar nogui", 
    "encoding": "UTF-8", 
    "server-directory": ".", 
    "shell-scripts": false, 
    "timed-reboot": false, 
    "timed-reboot-minutes": 2, 
    "timed-reboot-warning-minutes": 5
  }, 
  "IRC": {
    "autorun-irc-commands": [
      "COMMAND 1", 
      "COMMAND 2"
    ], 
    "channels": [
      "#wrapper"
    ], 
    "command-character": ".", 
    "control-from-irc": false, 
    "control-irc-pass": "password", 
    "irc-enabled": false, 
    "nick": "MinecraftWrap", 
    "obstruct-nicknames": false, 
    "password": null, 
    "port": 6667, 
    "server": "benbaptist.com", 
    "show-channel-server": true, 
    "show-irc-join-part": true
  }, 
  "Misc": {
    "command-prefix": "/", 
    "default-restart-message": "Server restarting...", 
    "reboot-message": "Server is conducting a scheduled reboot. The server will be back momentarily!", 
    "stop-message": "Stopping The Minecraft Server", 
    "use-readline": true
  }, 
  "Proxy": {
    "convert-player-files": false, 
    "hidden-ops": [
      "SurestTexas00", 
      "BenBaptist"
    ], 
    "max-players": 1024, 
    "online-mode": true, 
    "proxy-bind": "0.0.0.0", 
    "proxy-enabled": false, 
    "proxy-port": 25565, 
    "proxy-sub-world": false, 
    "silent-ipban": true, 
    "spigot-mode": false
  }, 
  "Updates": {
    "auto-update-branch": null, 
    "auto-update-wrapper": false, 
    "dev-branch": "https://raw.githubusercontent.com/benbaptist/minecraft-wrapper/development/build/version.json", 
    "stable-branch": "https://raw.githubusercontent.com/benbaptist/minecraft-wrapper/master/build/version.json"
  }, 
  "Web": {
    "public-stats": false, 
    "server-name": "Minecraft Server", 
    "web-allow-file-management": true, 
    "web-bind": "0.0.0.0", 
    "web-enabled": false, 
    "web-password": "password", 
    "web-port": 8070
  }
}
```

**Comment by suresttexas00** [comment]
I have created a new version with the possible fix for this.  Please try it out and let me know how it goes.

**Comment by lukeeexd** [comment]
Works, thank you :)

**Comment by suresttexas00** [comment]
I need more console output from that error.  This is probably due to differences between SPigot and Vanilla server outputs.  Always give me the entire context for errors like these.

**Comment by lukeeexd** [comment]
```
[17:03:21] [root/INFO]: Logging configuration file (logging.json) located and loaded, logging configuration set!
[17:03:21] [Wrapper.py/INFO]: Wrapper.py started - Version 235 (stable)
[17:03:21] [Wrapper.py/INFO]: Loading plugins...
[17:03:21] [Wrapper.py/INFO]: Starting server...
Loading libraries, please wait...
2017-12-09 17:03:21,848 main WARN Disabling terminal, you're running in an unsupported environment.
[17:03:23 INFO]: Starting minecraft server version 1.12.2
[17:03:23 INFO]: Loading properties
[17:03:23 INFO]: Default game type: SURVIVAL
[17:03:23 INFO]: This server is running Paper version git-Paper-1270 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
[17:03:23 INFO]: Server Ping Player Sample Count: 12
[17:03:23 INFO]: Using 4 threads for Netty based IO
[17:03:23 INFO]: Debug logging is disabled
[17:03:23 INFO]: Generating keypair
[17:03:23 INFO]: Starting Minecraft server on :25569
[17:03:23] [Wrapper.py/ERROR]: list index out of range
Traceback (most recent call last):
  File "Wrapper.py/core/mcserver.py", line 212, in handle_server
    self.readconsole(line.replace("\r", ""))
  File "Wrapper.py/core/mcserver.py", line 749, in readconsole
    self.vitals.server_port = get_int(buff.split('on *:')[1])
IndexError: list index out of range
[17:03:23 INFO]: Using epoll channel type
[17:03:23 INFO]: Set PluginClassLoader as parallel capable
[17:03:23 INFO]: [CoreProtect] Loading CoreProtect v2.14.2
[17:03:23 INFO]: [WorldEdit] Loading WorldEdit v6.1.8-SNAPSHOT;cd4729f
[17:03:23 INFO]: [SeePlayerInventory] Loading SeePlayerInventory v2.2
```

**Comment by lukeeexd** [comment]
Now this, server still boots up. Nothing before it just this 
```
[23:54:56] [Wrapper.py/ERROR]: could not convert string to float: [world]-2307.99691307211
Traceback (most recent call last):
  File "Wrapper.py/core/mcserver.py", line 212, in handle_server
    self.readconsole(line.replace("\r", ""))
  File "Wrapper.py/core/mcserver.py", line 808, in readconsole
    float(locationtext[0])), get_int(
ValueError: could not convert string to float: [world]-2307.99691307211
```

**Comment by suresttexas00** [comment]
I fixed the first one (again due to differences in how spigot servers chat).  I will be pulling fixes to the development branch only until these are all fixed, so use this instead:

wget https://raw.githubusercontent.com/benbaptist/minecraft-wrapper/development/Wrapper.py

The second one is a result of a player teleport occurring.  I need the entire console start to finish for that one too.

**Comment by suresttexas00** [comment]
What I am looking for is what a teleport line looks like.  On a vanilla server, it looks like this:
`[21:58:31] [Server thread/INFO]: Teleported SurestTexas00 to 65.5, 69.0, -267.5`

It appears like the Spigot also includes the world name in the teleport line?

**Comment by lukeeexd** [comment]
Never got an email about your replies, apologies. I can get full console tomorrow if I can replicate it

**Comment by suresttexas00** [comment]
Thanks.. a nice example of what is sent while running a server will help me see what parts are different between Spigot and Vanilla now.

**Comment by suresttexas00** [comment]
I believe this answered some questions I was wondering about backups.  By the way, Wrapper supports having your server in a different directory from the wrapper (you see hints about this below):

```
"Backups":

"backup-compression": False,
# Specify files and folders you want backed up. Items must be in your server 
# folder (see 'General' section)
"backup-folders":
    [
        "server.properties",
        "world"
    ],
"backup-interval": 3600,

# backup location is inside wrapper's directory
"backup-location": "backup-directory",
"backup-notification": True,
"backups-keep": 10,
"enabled": False
```

```
"General":
# Using the default '.' roots the server in the same folder with wrapper. 
# Change this to another folder to keep the wrapper and server folders 
# separate.  Do not use a trailing slash...  e.g. - '/full/pathto/the/server'

"server-directory": ".",
```

**Comment by lukeeexd** [comment]
Apologies, was doing exams. heres more of the error from start up.

```minecraft@ns349091:~/vanillatest$ python2.7 Wrapper.py
[00:00:09] [root/INFO]: Logging configuration file (logging.json) located and loaded, logging configuration set!
[00:00:09] [Wrapper.py/INFO]: Wrapper.py started - Version 235 (stable)
[00:00:09] [Wrapper.py/INFO]: Loading plugins...
[00:00:09] [Wrapper.py/INFO]: Starting server...
Loading libraries, please wait...
2017-12-18 00:00:09,736 main WARN Disabling terminal, you're running in an unsupported environment.
[00:00:11 INFO]: Starting minecraft server version 1.12.2
[00:00:11 INFO]: Loading properties
[00:00:11 INFO]: Default game type: SURVIVAL
[00:00:11 INFO]: This server is running Paper version git-Paper-1270 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
[00:00:11 INFO]: Server Ping Player Sample Count: 12
[00:00:11 INFO]: Using 4 threads for Netty based IO
[00:00:11 INFO]: Debug logging is disabled
[00:00:11 INFO]: Generating keypair
[00:00:11 INFO]: Starting Minecraft server on 188.165.251.221:25569
[00:00:11] [Wrapper.py/ERROR]: list index out of range
Traceback (most recent call last):
  File "Wrapper.py/core/mcserver.py", line 212, in handle_server
    self.readconsole(line.replace("\r", ""))
  File "Wrapper.py/core/mcserver.py", line 749, in readconsole
    self.vitals.server_port = get_int(buff.split('on *:')[1])
IndexError: list index out of range
[00:00:11 INFO]: Using epoll channel type
[00:00:11 INFO]: Set PluginClassLoader as parallel capable
[00:00:11 INFO]: [WorldEdit] Loading WorldEdit v6.1.8-SNAPSHOT;cd4729f
[00:00:11 INFO]: [SeePlayerInventory] Loading SeePlayerInventory v2.2
[00:00:11 INFO]: [NoPoppyDrop] Loading NoPoppyDrop v1.0
[00:00:11 INFO]: [CustomWhitelist] Loading CustomWhitelist v1.4
[00:00:11 INFO]: [NameColor] Loading NameColor v1.3
[00:00:11 INFO]: [Nicky] Loading Nicky v0.6.9
[00:00:11 INFO]: [TWSConfiguration] Loading TWSConfiguration v3.0.0
[00:00:11 INFO]: [PlaceholderAPI] Loading PlaceholderAPI v2.8.2
[00:00:11 INFO]: [PacketListenerApi] Loading PacketListenerApi v3.6.0-SNAPSHOT
[00:00:11 INFO]: [ReflectionHelper] Version is v1_12_R1 (11201)
[00:00:11 INFO]: [PacketListenerAPI] Using INChannel
[00:00:11 INFO]: [PacketListenerAPI] Injected custom channel handlers.
[00:00:11 INFO]: [ClearLag] Loading ClearLag v2.9.7
[00:00:11 INFO]: [PermissionsEx] Loading PermissionsEx v1.23.4
[00:00:11 INFO]: [KeepChunks] Loading KeepChunks v1.3.7
[00:00:11 INFO]: [InactivityChecker] Loading InactivityChecker v1.0.0
[00:00:11 INFO]: [ViaVersion] Loading ViaVersion v1.3.0
[00:00:11 INFO]: [ViaVersion] ViaVersion 1.3.0 is now loaded, injecting!
[00:00:12 INFO]: [RelaAutoBroadcast] Loading RelaAutoBroadcast v1.9
[00:00:12 INFO]: [Tablist] Loading Tablist v1.3.2.9
```

**Comment by suresttexas00** [comment]
The first error is fixed.  You will have to update from the development branch to get the fix,as it is not part of the master branch.  The second error I will work on.  I would like for you to also show me what happens when you TP a player.

**Comment by lukeeexd** [comment]
Wow whats the chances of that. Came to check if you replied and you replied 34seconds ago. I will test TPing now, and will make a new comment with the error.

**Comment by lukeeexd** [comment]
```
[00:31:12 INFO]: lukeeexd issued server command: /tp Frankieh907 lukeeexd
[00:31:12 INFO]: Frankieh907 has made the advancement [The End?]
[00:31:12 INFO]: [lukeeexd: Teleported Frankieh907 to lukeeexd]
```

Nothing

**Comment by suresttexas00** [comment]
The console does not list the coordinates?  What about a TP to specific coordinates (`tp SurestTexas00 1920, 63, 2001`)?

**Comment by suresttexas00** [comment]
I had a pretty critical fix in a few places including the "/update-wrapper" command (which was broke).

You should re-wget the development version:
`wget https://raw.githubusercontent.com/benbaptist/minecraft-wrapper/development/Wrapper.py`

After this, future updates can be gotten with /update-wrapper from the console.

**Comment by lukeeexd** [comment]
Still getting this error on different server. I know its not fixed yet but just showing again.
```[18:08:38 INFO]: lukeeexd[/51.37.121.101:63835] logged in with entity id 6113 at ([world_the_end]55.42876079681521, 62.03762570748349, 28.404513284157694)
[18:08:39] [Wrapper.py/ERROR]: could not convert string to float: [world_the_end]55.42876079681521
Traceback (most recent call last):
  File "Wrapper.py/core/mcserver.py", line 212, in handle_server
    self.readconsole(line.replace("\r", ""))
  File "Wrapper.py/core/mcserver.py", line 795, in readconsole
    location = get_int(float(locationtext[0])), get_int(
ValueError: could not convert string to float: [world_the_end]55.42876079681521
```

No errors if I TP to a specific coordinate
