### ISSUE TITLE
Custom messages in "misc" don't work and timed-reboot-warning-minutes

### ISSUE THREAD

**Issue by lukeeexd** [benbaptist/minecraft-wrapper#492]
If the server does a scheduled reboot, it says ```server closed``` instead of ```Server is conducting a scheduled reboot. The server will be back momentarily!```. Also the warning minutes show up all at the same time just before it restarts. So if warning minutes is 5. It will say rebooting in 5, 4, 3, 2, 1 all at the same time just before it reboots.

Video: https://streamable.com/cxvhb

**Comment by suresttexas00** [comment]
Thanks for reporting this.. Can you give me the version and build you are using (this is displayed when wrapper starts)?

**Comment by lukeeexd** [comment]
version 245(?)

**Comment by suresttexas00** [comment]
if you are using a modern version of wrapper, it should be right in the startup text:
```
[15:22:08] [Wrapper.py/INFO]: Wrapper.py started - Version [0, 14, 1] (development build #245) 
[15:22:08] [Wrapper.py/DEBUG]: Wrapper is using Python 3.5.
[15:22:08] [Wrapper.py/DEBUG]: [Wrapper.py] Registered help group 'Wrapper' with 13 commands
[15:22:08] [Wrapper.py/INFO]: Loading plugins...
```
build 245 should definitely not be 0.8.0.

**Comment by lukeeexd** [comment]
```[21:36:07] [root/INFO]: Logging configuration file (logging.json) located and loaded, logging configuration set!
[21:36:07] [Wrapper.py/INFO]: Wrapper.py started - Version 245 (stable)
[21:36:07] [Wrapper.py/INFO]: Loading plugins...
[21:36:07] [Wrapper.py/INFO]: Starting server...
```

**Comment by lukeeexd** [comment]
Just downloaded from github and it still says 

```
[21:36:07] [root/INFO]: Logging configuration file (logging.json) located and loaded, logging configuration set!
[21:36:07] [Wrapper.py/INFO]: Wrapper.py started - Version 245 (stable)
[21:36:07] [Wrapper.py/INFO]: Loading plugins...
[21:36:07] [Wrapper.py/INFO]: Starting server...
```

**Comment by suresttexas00** [comment]
Ok, that is correct, albeit, the version is supposed to show, not the build :)

**Comment by suresttexas00** [comment]
Looking at your video again and testing it myself, I can tell you that the likely problem is that the timed reboot warning is occurring in 'seconds', not minutes.

Until I fix this, you can probably just change your config file like so (pretending the warning is in seconds):
`"timed-reboot-warning-minutes": 120`  (i.e., 120 seconds is two minutes).

Once I fix it, I will let you know (I am going to fix the server messages too).  After it is fixed, you will need to change it back to 2 minutes...

**Comment by suresttexas00** [comment]
DIsregard that... if you do, it will still give the message every second (just for 120 seconds).
I'll let you know when I fix it.

**Comment by suresttexas00** [comment]
Both issues are now fixed.  Please note: This fix is only in the development branch!  You will need to switch branches to use this!

**Comment by lukeeexd** [comment]
How do I switch branches?

**Comment by lukeeexd** [comment]
```minecraft@ns349091:~/vanillatest$ python2.7 Wrapper.py
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "Wrapper.py/__main__.py", line 10, in <module>
  File "Wrapper.py/core/wrapper.py", line 36, in <module>
  File "Wrapper.py/utils/crypt.py", line 8, in <module>
ImportError: No module named cryptography.hazmat.primitives
```

**Comment by suresttexas00** [comment]
you need to `pip install cryptography`

**Comment by suresttexas00** [comment]
I'll do a better job about error checking that first.  You should also install bcrypt (although wrapper will start without it).

**Comment by suresttexas00** [comment]
You may also want to review the documentation for the config file as some items were added and changed:
[new plugin methods self.api.hash_password and check_password](https://github.com/benbaptist/minecraft-wrapper/blob/development/documentation/base.rst)

[New config items](https://github.com/benbaptist/minecraft-wrapper/blob/development/documentation/wrapperconfig.rst)

**Comment by lukeeexd** [comment]
Do i have to install it? The user my servers run off dont have sudo access

**Comment by suresttexas00** [comment]
Unfortunately, just like requests, cryptography will become a standard wrapper requirement.  I can fix it so wrapper will start, but you will not be able to use features that implement passwords; like IRC and Web (once they are fixed, of course)

Do you mean your user's system does not have a Sudo command?

Normally, you should just be able to `sudo -H pip install cryptography` and get prompted for the system password...

Also, you should probably review the linux install readme on my branch (I have not pushed it to Ben's yet): https://github.com/suresttexas00/minecraft-wrapper

**Comment by suresttexas00** [comment]
I will go ahead and pull the next version I was working on with the fix to allow you to not use cryptography.

**Comment by lukeeexd** [comment]
All good. I gave the user sudo access then installed cryptography

**Comment by suresttexas00** [comment]
Ok, well I did push the next version, which supports creating encrypted passwords using the config file.  You may wish to re-check the [developement branch config documentation](https://github.com/benbaptist/minecraft-wrapper/blob/development/documentation/wrapperconfig.rst)

Also note that these versions require the user to enter a passphrase at wrapper startup.  If they dont want to be prompted each time, they can put the passphrase in the wrapper start command:
```
python Wrapper.py --passphrase "your passphrase"
```

**Comment by suresttexas00** [comment]
Are you running in proxy mode or not?

**Comment by lukeeexd** [comment]
I did ```python2.7 Wrapper.py --passphrase "your passphrase"``` and it asks to setup passphrase 

I'm not running in proxy mode

**Comment by suresttexas00** [comment]
what happens when you type "python2.7 Wrapper.py -h"

**Comment by lukeeexd** [comment]
Do you have discord or anything? That I can report issues to you instead of spamming your github

**Comment by suresttexas00** [comment]
I dont mind.. on on GH right now.  I don't really have chat programs, aside from facebook (which I am not on much)

**Comment by lukeeexd** [comment]
```python2.7 Wrapper.py -h
usage: Wrapper.py [-h] [--encoding] [--betterconsole]
                  [--passphrase PASSPHRASE]

Wrapper.py startup arguments

optional arguments:
  -h, --help            show this help message and exit
  --encoding, -e        Specify an encoding (other than utf-8)
  --betterconsole, -b   Use "better console" feature to anchor your imput at
                        the bottom of the console (anti- scroll-away feature)
  --passphrase PASSPHRASE, -p PASSPHRASE
                        Passphrase used to encrypt sensitive information in
                        Wrapper. Please use as fairly long phrase (minimum is
                        8 characters). If not specified, or incorrectly
                        supplied, Wrapper will prompt for a new passphrase
                        before starting! Use "--passphrase none" to start
                        wrapper with passwords disabled.

Created by SurestTexas00
```

**Comment by suresttexas00** [comment]
--passphrase ought to be sending that passphrase (you should use something different LOL) to wrapper... heres a thought... you are using the quotes around the passphrase, right?

**Comment by suresttexas00** [comment]
the quotes are needed if the pass phrase is multiple words.  If that is not the problem, then use a single long word:
python2.7 Wrapper.py --passphrase longonewordpassphrase

**Comment by suresttexas00** [comment]
I'll have to recheck what the code does to kick players when not in proxy mode.

**Comment by lukeeexd** [comment]
I'm not using quotes. But my passphrase isnt multiple words, just one

**Comment by suresttexas00** [comment]
how long is the passphrase (must be >7 characters)?

**Comment by lukeeexd** [comment]
Ah I'm dumb. It has to be more than 8, I had 7. Works now.

**Comment by lukeeexd** [comment]
But the reboot message doesnt work still. says server closed

**Comment by suresttexas00** [comment]
I was going to say, if a password did not work when in wrapper, it wont work in the --passphrase option either...

**Comment by lukeeexd** [comment]
Suppose that wouldn't be too hard to do. Also what does the alert thing alert? Is there docs on it

**Comment by suresttexas00** [comment]
I just pushed a new build.  I did not test it, but it is a simple fix and should work.

Alerts are a new feature I am working on.  the idea is if the server goes down, I can tell wrapper to send me an email or maybe a text, etc...  only the config is there.  it is not implemented yet.

**Comment by lukeeexd** [comment]
I'll test for you now. Okay that sounds cool. Would it be possible for the alert to detect low TPS and email/sms ?

**Comment by suresttexas00** [comment]
Found another bug I need to fix, so Ill reply later (bug does not affect you at this time - I hope!)

**Comment by lukeeexd** [comment]
Didn't work. I'm pretty sure it kicked me and then restarted. But still says server closed

**Comment by lukeeexd** [comment]
Think I might know why. I'm exempt from kick. One sec let me get a player to test

**Comment by lukeeexd** [comment]
https://gyazo.com/c95df6b771a3aea4a2d5cf0c34f70028

Still said server closed

**Comment by suresttexas00** [comment]
I looks like Mcbans slowed down the kicking process so that the server was able to shutdown before you actually got kicked.

**Comment by lukeeexd** [comment]
https://i.imgur.com/xGyIe5F.jpg Good shout

**Comment by suresttexas00** [comment]
what did you do; disable Mcbans for the test?

**Comment by suresttexas00** [comment]
I can add a small sleep timer after the kick to give Spigot/mcbans another second to kick...

**Comment by lukeeexd** [comment]
I uninstalled mcbans. It wasnt really even used so just removed it. I do all the testing on my test world.

**Comment by suresttexas00** [comment]
I added a sleep timer to the kicks.. can you see if it works with mcbans now?

**Comment by lukeeexd** [comment]
Works

**Comment by lukeeexd** [comment]
Ok, just put latest build from dev branch onto live server. Will report back with any bugs.

**Comment by suresttexas00** [comment]
Thanks.  These were bugs that definitely needed fixed and it is good to have people testing this for me.
