### ISSUE TITLE
change more settings through IRC, such as server.properties

### ISSUE THREAD

**Issue by benbaptist** [benbaptist/minecraft-wrapper#5]

**Comment by JasonBristol** [comment]
Is this necessary given the opportunity for a refactored dashboard?

**Comment by benbaptist** [comment]
Nah - this was definitely from another era before the dashboard existed/was prevalent.

**Comment by suresttexas00** [comment]
understandable given that wrapper appears to have actually been birthed as a way to connect IRC to a server!
