### ISSUE TITLE
Unencrypted passwords get saved in the wrapper.log

### ISSUE THREAD

**Issue by jspanos71** [benbaptist/minecraft-wrapper#513]
Issue: 
Saving a password using /password Alerts password <password> results in the command being saved in wrapper.log in plain text. 

Expected result:
The password that was entered by the user should be redacted to prevent the password from leaking.
`CONSOLE OPERATOR executed: /password Alerts password <redacted>`

**Comment by suresttexas00** [comment]
Good catch.  I'll have it not log that command entirely

In the meantime Use:
/password Alerts prompt

You will be prompted for the password (which will not be visible)

FYI, Alerts is an alpha feature I have not actually started on yet.

**Comment by suresttexas00** [comment]
You may also enter passwords into the '\<whateverPassword\>-plaintext' field and wrapper will encrypt them and store them in the associated '\<whateverPassword\>' field, such as these examples in IRC.  Just substitute your password for the `false` (your plaintext password is erased and the field set to false once wrapper is done).

```
    "control-irc-pass": "gAAAAABaS7Czgma0dPMTwReQkwJz5N_jkkfttgkBUJV49a9najpGeiEtZsWVKpt0E9Ah9FbEwTohV4JpOn5WQF-boSzicLuTeg==", 
    "control-irc-pass-plaintext": false, 
    "irc-enabled": false, 
    "nick": "surest", 
    "obstruct-nicknames": true, 
    "password": "gAAAAABaS78Caw719qRsS9pN_BZloebdEdCBgJZs6ehBcs_OQAGCaxAW_NdJS-5cVb6QAp2arwTAYrDj1f5s2O2Kb2JWZwHE8A==", 
    "password-plaintext": false, 
    "port": 6667, 
    "server": "irc.freenode.net", 
    "show-channel-server": true, 
    "show-irc-join-part": true
```
