### ISSUE TITLE
Web mode bugs and broken functionality 

### ISSUE THREAD

**Issue by suresttexas00** [benbaptist/minecraft-wrapper#518]
This issue is not addressing "improvements", but only seeks to repair what appear to be existing or staged Web mode features.  Proper HTTPS is not required to close this issue; it is here as food for thought.

_Remaining Web bugs_
 - [x] Generally, shouldn't buttons (server restarts and so forth), get feedback from wrapper that they actually completed the operation (most events prematurely or just flatly assume it succeeded)?
 - [x] `Server` - No feed back from console.
 - [x] `Server` - No chat feed back ~~~or player list~~~
 - [x] `Server` `files` - Working great, but we should:
        - implement the "new directory" function/button.
        ~~~- maybe a file viewer for text files like server properties does??~~~
 - [x] `Server` `Server Properties` - re-enable the editing/saving function.
 - [x] `Dashboard` - nothing works except the 'Power' drop-down button.  Don't get me wrong, that's great, but the ticking event that gathers server info needs repaired.
 - [x] Clicking logout does not log you out of the web page or prevent further access to the interface items.  You have to clear the history and close the browser....
 - [x] The remember_me checkbox probably does nothing...
 ~~~One day, proper HTTPS would be nice so the password we so carefully encrypted within wrapper can't be seen when the client web page sends it via an unencryted `GET` request :o ...~~~
 - [x] Oh yes... almost forgot.. Web is still likely not working on Python 3

**Comment by benbaptist** [comment]
Wait, so is this a plugin now or did we just decide to keep it internally? I haven't actually looked at the code or anything yet to confirm this, so consider this me being lazy. :P

**Comment by suresttexas00** [comment]
I am keeping it internally for now.  As I said on gitter, it's actually done :) Just need py3 compatibility before I make the final push.

**Comment by suresttexas00** [comment]
Final working product!
