### ISSUE TITLE
Update the Wrapper.py Website

### ISSUE THREAD

**Issue by benbaptist** [benbaptist/minecraft-wrapper#520]
This website certainly is a touch outdated, and could stand to be updated. Whoopsie. 

I can also give SurrestTexas (and others - I'm not 100% up to speed with who actively works on Wrapper.py at this moment) if they'd like to use it. 

The website itself should probably be in some sort of Git repository to be easily maintained. I was also thinking that it would be cool to make some aspects of this site dynamic, such as the version numbers on the Downloads page, having an automatically-updated build list (stable & dev channels), and perhaps even more interesting: a plugin repository. 

And dat copyright year tho.

[Wrapper.py's Homepage](http://wrapper.benbaptist.com/)

**Comment by suresttexas00** [comment]
Despite the labels "saying" different versions, the website does actually point to the correct content.  So, yes, I think just some more dynamic parsing of the content to properly update the labels should fix it up nicely.  At the present, It is just me doing major code writing.  JasonBristol wanted to pursue a grander version of his own and has not been active in a while.

**Comment by benbaptist** [comment]
Nice, yeah - I noticed that it still points correctly to the Github and works as intended. Huzzahs are in order! 

But indeed, it would be nice to have the labels up to par. I might try working on this Sunday, since Saturday will be a bit of a jam-packed day for me.

**Comment by suresttexas00** [comment]
When you do this, please note the current versioning API:

The location for the version information is (for development):
```
https://raw.githubusercontent.com/benbaptist/minecraft-wrapper/development//build/buildinfo.py
```

do not use items in `./build/version.json` as two thirds of that file is strictly legacy support for all wrapper version.  Also dont use `./docs/version.json`, as that is legacy also for wrappers 0.7.6 to 0.8.0.

The current version information is formatted thusly:
```
__version__ = [1, 0, 0, 'beta', 1]
__branch__ = 'dev'
```
\_\_Version\_\_ is a 5-part tuple.  The last element, [4] is the build number.  Builds only matter when the first four elements are identical.  Possible values for [3], the release type, are: 'alpha', 'beta', 'rc', 'final'.

Release types actually trump the [0]-[2] version number parts.

Build numbers are now unique to a given release and major version.  (So one day, when 2.0 comes out, the build numbers will start over).  They can also start over once a difference release type is created (i.e., the move from 'beta' to 'rc').

\_\_Branch\_\_, as always. is just 'dev' or 'stable'.

The master branch buildinfo.py currently looks like this until we push the final Dev verson onto it:
```
__version__ = [0, 15, 0]
__build__ = 254
__branch__ = 'stable'
```
I'm going to assume that once you get to this, master and development will have the same setup with just version and branch

**Comment by suresttexas00** [comment]
If you do use `./build/version.json` (which might be easier for web page code), just ignore all dictionary items except \_\_branch\_\_ and \_\_version\_\_...

**Comment by suresttexas00** [comment]
You can also remove the Web disclaimer now :)

**Comment by suresttexas00** [comment]
Wow, yes; a separate plugin repo would be awesome!

**Comment by suresttexas00** [comment]
Sorry:Sorry (for all the separate responses today).. and also, you can make your decumentation tab point here: https://github.com/benbaptist/minecraft-wrapper/tree/master/documentation

**Comment by suresttexas00** [comment]
Just a note to remind you; our new RC (both branches) fully supports HUBs!  Let the minigames begin!

You don't even need to use player connect!  There is a section in the config for configuring your worlds.  For example, my test hub:

```
  "Proxy": {
    "auto-name-changes": true,
    "built-in-hub": true,
    "disconnect-nonproxy-connections": true,
    "max-players": 2,
    "online-mode": true,
    "proxy-bind": "0.0.0.0",
    "proxy-enabled": true,
    "proxy-port": 25565,
    "silent-ipban": true,
    "hidden-ops": ["SurestTexas00"]
    "worlds": {
      "cottage": {
        "desc": "a cottage in the woods",
        "port": 25611
      },
      "islands": {
        "desc": "an island world",
        "port": 25614
      },
      "test": {
        "desc": "a place to test my plugins",
        "port": 25616
      },
      "vanilla": {
        "desc": "a beach fort",
        "port": 25612
      }
    }
  },
```

**Comment by benbaptist** [comment]
Slightly updated website to always reflect what's in version.json.

**Comment by benbaptist** [comment]
Also, copyright year. Also, probably going to close this for the time being.
