### ISSUE TITLE
Proxy mode changes the UUIDs...

### ISSUE THREAD

**Issue by suresttexas00** [benbaptist/minecraft-wrapper#53]
Which means that if i implement wrapper on an existing server, players will be treated as new players when they login... starting back out at the spawn point, bed spawns lost, no XP, lost inventories, and achievements starting over.  Is there a way to work around this?

This is not just a wrapper issue, I guess its just the way proxies work because I have the same issue with my bungeecord worlds if I tried to bungeecord to a vanilla jar (works fine with spigot because it's designed to bo configued with bungeecord).

**Comment by benbaptist** [comment]
Yeah, 1.7.5 and over really screwed offline-mode servers over bad with this
UUID crap. Unfortunately, it is a design flaw with the UUID changing when
going into offline mode. The only solution that I'm aware of is to rename
all of the .DAT files to their offline mode UUID equivalent. I should write
a script to do that, actually.

**Comment by suresttexas00** [comment]
let's say a person with online UUID xxxxxx-345 named "digboy" is issued a UUID of xxxxxx- a2c by the proxy'd minecraft... and he changes his name (in the future when they allow it) to "digman".... 

His online UUID will still be xxxxxx-345... will his local UUID still be xxxxxx- a2c or will he be assigned a new one??

**Comment by suresttexas00** [comment]
how do you know what the offline mode equivalent is before they log in for the first time in the offline mode?

**Comment by suresttexas00** [comment]
I found the answer here:
http://www.reddit.com/r/admincraft/comments/29vugf/converting_an_onlinemode_server_to_an_offlinemode/

Get a list of all players (from the logs, a database, whitelist, ...)
Get all associations for online UUIDs (player name -> UUID). You can, for instance, get them from the minecraft.net API, from your logs, a database you already have, ...
Rename all files from <online_uuid>.dat to <playername>.dat
Put the files in a directory called players (what it was called before the UUID change).
Remove the playerdata directory if it's still there.
Start your server in offline mode. The existence of the players directory should trigger the UUID conversion and rename the player files from <playername>.dat to <offline_uuid>.dat automatically.

**Comment by suresttexas00** [comment]
Yours is working well enough that I will be moving my production server to wrapper...

**Comment by suresttexas00** [comment]
still some other bugs I will bring up later, but they are not affecting performance in the areas I can see.

**Comment by suresttexas00** [comment]
Did not know if want this kept open or not...

**Comment by benbaptist** [comment]
Ooh, clever way. I would've just done the UUID conversion from online to
offline myself, but that might be a tad bit simpler and more reliable, by
just letting the server do it.

Offline UUIDs are generated using md5 with the following string:
"OfflinePlayer:username". It's how I know what the server thinks their UUID
is - I have to convert a lot of network packets because most of them send
their  offline UUID, which screws and confuses a lot of things up. I think
you can even get the offline UID with player.serverUUID. I might be wrong,
but I think that is the variable.

**Comment by suresttexas00** [comment]
Uh oh.. I may have a problem.  I used the usercache,json and was able to import like 143 records and create a batch file to rename the UUIDs to Usernames.  However, the playerdata folder contains over 300 UUID's....  So over half have no entry in the usercache.  There does not seem to be any particular time/date to which I can tie these missing UUIDs.  This server has never run in offline mode.. do you think maybe they are created when the mojang servers go down or something?

**Comment by suresttexas00** [comment]
OK.. figured this out.  These extra UUID's are probably named "entities" (custom mobs) I use in various parts of the map.

**Comment by suresttexas00** [comment]
Well, everything is transferred over and running smoothly on wrapper.  No one yelling that their stuff is gone o_o.  a few TP's to get people to their homes so they can set them, that's it.

**Comment by benbaptist** [comment]
I think the issue is because usercache.json only keeps a certain amount of
UUIDs, so it doesn't grow to being in the thousands and get really huge.
For the rest of the UUIDs, you'll have to actually poll Mojang's own API.
But don't worry, eventually I'll get a script out when I get the time.

On Fri, Jan 9, 2015 at 4:19 PM, Surest Texas <notifications@github.com>
wrote:

> Closed #53 <https://github.com/benbaptist/minecraft-wrapper/issues/53>.
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/benbaptist/minecraft-wrapper/issues/53#event-216760192>
> .
>



-- 
http://sawmaster2.no-ip.org:82/

iPod network

**Comment by suresttexas00** [comment]
well, I have already migrated and no complaints.  I really think these were named mobs, mostly... the dates line up with such an explanation.  I have a question about the player.connect(ip, address) function... these two arguments... 1) IP - does it have to be numeric? or will a URL work?2) what does address mean, if you already are specifying an IP?
3) What are the data types of the arguments?
 		 	   		  =

**Comment by benbaptist** [comment]
Wow, I don't know how I messed that up so badly doc-wise. :P

It should be player.connect(address, port) with address being an actual IP
or domain, and port being a port. I just messed up the docs.

On Fri, Jan 9, 2015 at 11:52 PM, Surest Texas <notifications@github.com>
wrote:

> well, I have already migrated and no complaints. I really think these were
> named mobs, mostly... the dates line up with such an explanation. I have a
> question about the player.connect(ip, address) function... these two
> arguments... 1) IP - does it have to be numeric? or will a URL work?2) what
> does address mean, if you already are specifying an IP?
> 3) What are the data types of the arguments?
> =
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/benbaptist/minecraft-wrapper/issues/53#issuecomment-69440793>
> .
>



-- 
http://sawmaster2.no-ip.org:82/

iPod network

**Comment by suresttexas00** [comment]
what are the data types for the arguments?  if I use a URL, does it have to be in quotes?  is the port a string (and same second half of other question) or an integer?

Date: Fri, 9 Jan 2015 22:02:43 -0800
