### ISSUE TITLE
Running snapshots with proxy mode throws an error.  Need method to run Custom snapshots.

### ISSUE THREAD

**Issue by l33tlinuxh4x0r** [benbaptist/minecraft-wrapper#546]
`Proxy mode cannot run because the server is a pre-Netty version:

http://wiki.vg/Protocol_version_numbers#Versions_before_the_Netty_rewrite

Server will continue in non-proxy mode.
[19:45:04] [Wrapper.py/WARNING]: 
Proxy mode is now turned off in wrapper.properties.json.
`
I am not positive but I believe that this error is a mistake because the wrapper doesn't know about the Minecraft version being used. Is there a way to bypass this check or override it to allow proxy mode with the recent Aquatic Update snapshots?

**Comment by l33tlinuxh4x0r** [comment]
I have a fix however I do not know how to use git hub correctly. I'll post the fix here.
file wrapper/core/mcserver.py 

`            #l33tlinuxh4x0r's snapshot fix.
            if "." not in self.vitals.version:
                self.log.warning("\nYou are running a Minecraft Snapshot "
                                 "\nExpect odd behavior!!! ")
                self.vitals.version_compute = -1

            # 1.7.6 (protocol 5) is the cutoff where ops.txt became ops.json
            if self.vitals.version_compute > 10705 and self.vitals.protocolVersion < 0:  # noqa
                self.vitals.protocolVersion = 5
                self.wrapper.api.registerPermission("mc1.7.6", value=True)

            if self.vitals.version_compute < 10702 and self.vitals.version_compute > 0 and self.wrapper.proxymode:
                self.log.warning("\nProxy mode cannot run because the "
                                 "server is a pre-Netty version:\n\n"
                                 "http://wiki.vg/Protocol_version_numbers"
                                 "#Versions_before_the_Netty_rewrite\n\n"
                                 "Server will continue in non-proxy mode.")
                self.wrapper.disable_proxymode()
                return`
I will try to post this correctly if I can figure out github :/

**Comment by l33tlinuxh4x0r** [comment]
I have issued a Pull request that fixes this issue. Please review.

**Comment by suresttexas00** [comment]
The pre-release protocol is (Here)[http://wiki.vg/Pre-release_protocol].

You will note they are changing all the packets again.  This will require updates to packets_cb.py and packets_sb.py and adding new constants for this protocol to proxy/utils/constants.py.

**Comment by suresttexas00** [comment]
If you are able to connect to proxy, you would be immediately kicked because it will send the wrong packets.

**Comment by l33tlinuxh4x0r** [comment]
Yeah the kick is not immediate but it does happen and it complains about packets so you are correct about that as well.

**Comment by suresttexas00** [comment]
I reviewed the code more fully.  All your changes do is prevent the error message and the disabling of proxy mode:
because version_compute = -1, this if statement is False:
```
            if self.vitals.version_compute < 10702 and self.wrapper.proxymode:
                self.log.warning("\nProxy mode cannot run because the "
                                 "server is a pre-Netty version:\n\n"
                                 "http://wiki.vg/Protocol_version_numbers"
                                 "#Versions_before_the_Netty_rewrite\n\n"
                                 "Server will continue in non-proxy mode.")
                self.wrapper.disable_proxymode()
                return
```
You are not closing proxy _but_ you still could not get a client to connect...  they will never get past the login handshake.

**Comment by suresttexas00** [comment]
If you want this to work, you need to make changes in three places (and revert the ones you did make):
in proxy/utils/constants.py, you need to add a AQUA_SNAP = 368 (for 18w11a, protocol 368):
```
# -*- coding: utf-8 -*-

# Copyright (C) 2016, 2017 - BenBaptist and Wrapper.py developer(s).
# https://github.com/benbaptist/minecraft-wrapper
# This program is distributed under the terms of the GNU
# General Public License, version 3 or later.

# Mincraft version constants
# use these constants decide how a packet should be parsed.

# Still in development at versions 201-210(6/14/16)

# def Wrapper.py Constants:
# """
PROTOCOL_MAX = 4000
<<<<Add here>>>>>
PROTOCOL_1_12_2END = 340
PROTOCOL_1_12_2 = 340
...
# PAGE: http://wiki.vg/index.php?title=Protocol&oldid=7817
# post- 1.9 "pre" releases (1.9.2 - 1.9.3 pre-1)
PROTOCOL_1_9_3PRE3 = 109

```

Then using the (wiki page), you will have to go through both of these files and change the packet [PKT] constants for each file, proxy/packets/`mcpackets_cb.py` and `mcpackets_sb.py`:
You will need to add a line that says:
`        if protocol >= AQUA_SNAP:`
then you will add the packets, using the wiki, just like this example from `mcpackets_cb.py`:

```
        # 1.12.1 CHANGES AGAIN! (to 340)
        if protocol >= PROTOCOL_1_12_1START:
            self.CRAFT_RECIPE_RESPONSE[PKT] = 0x2b
            self.PLAYER_ABILITIES[PKT] = 0x2c
            self.COMBAT_EVENT[PKT] = 0x2d
            self.PLAYER_LIST_ITEM[PKT] = 0x2e
            self.PLAYER_POSLOOK[PKT] = 0x2f
            self.USE_BED[PKT] = 0x30
            self.UNLOCK_RECIPES[PKT] = 0x31
            self.DESTROY_ENTITIES[PKT] = 0x32
            self.REMOVE_ENTITY_EFFECT[PKT] = 0x33
            self.RESOURCE_PACK_SEND[PKT] = 0x34
            self.RESPAWN[PKT] = 0x35
            self.ENTITY_HEAD_LOOK[PKT] = 0x36
            self.SELECT_ADVANCEMENT_TAB[PKT] = 0x37
            self.WORLD_BORDER[PKT] = 0x38
            self.CAMERA[PKT] = 0x39
            self.HELD_ITEM_CHANGE[PKT] = 0x3a
            self.DISPLAY_SCOREBOARD[PKT] = 0x3b
            self.ENTITY_METADATA[PKT] = 0x3c
            self.ATTACH_ENTITY[PKT] = 0x3d
            self.ENTITY_VELOCITY[PKT] = 0x3e
            self.ENTITY_EQUIPMENT[PKT] = 0x3f
            self.SET_EXPERIENCE[PKT] = 0x40
            self.UPDATE_HEALTH[PKT] = 0x41
            self.SCOREBOARD_OBJECTIVE[PKT] = 0x42
            self.SET_PASSENGERS[PKT] = 0x43
            self.TEAMS[PKT] = 0x44
            self.UPDATE_SCORE[PKT] = 0x45
            self.SPAWN_POSITION[PKT] = 0x46
            self.TIME_UPDATE[PKT] = 0x47
            self.TITLE[PKT] = 0x48
            self.SOUND_EFFECT[PKT] = 0x49
            self.PLAYER_LIST_HEADER_AND_FOOTER[PKT] = 0x4a
            self.COLLECT_ITEM[PKT] = 0x4b
            self.ENTITY_TELEPORT[PKT] = 0x4c
            self.ADVANCEMENTS[PKT] = 0x4d
            self.ENTITY_PROPERTIES[PKT] = 0x4e
            self.ENTITY_EFFECT[PKT] = 0x4f

```

**Comment by suresttexas00** [comment]
It is a lot of work to go through and the snapshot will probably be different in the final release anyway.  Mojang shuffles these packet numbers like they are playing poker, so I don't bother until they release an actual version.  The packets are easy enough, but they also make changes were and there to the [PARSER] lists.

**Comment by suresttexas00** [comment]
for your snapshot, you could just add the packets that wrapper parses in proxy/client/parse_sb.py and proxy/server/parse_cb... but that would be a temporary hack.

Once you get these constants in place, the server should connect just fine and let you on.

**Comment by suresttexas00** [comment]
If a vital packet we parse changes parsing elements, then that packet[PARSER] will need changed too...

**Comment by suresttexas00** [comment]
I pushed some code to my development branch that allows running the 18w14b snapshot:
https://github.com/suresttexas00/minecraft-wrapper

To summarize: the SLOT data type has changed some and it is messing with inventory management. If you would like to clone my dev and see if you can correct the SLOT (wrapper/proxy/packets/packet.py) feel free to do so..

**Comment by suresttexas00** [comment]
This will need more work once the actual release hits the streets.  The present snapshot seems buggy to me, and it looks like they may still have a while before it becomes a final version.

**Comment by suresttexas00** [comment]
This is fully fixed unless you use the new serverAutocompletes event.  I have not tested the impact that the snapshot changes may have on plugins that access player inventory.  The Wiki hints that items IDs might have changed:

![image](https://user-images.githubusercontent.com/10001762/38456219-24f69940-3a50-11e8-8bed-49cfe3c9aa15.png)

#587
