### ISSUE TITLE
In proxy mode items on ground do not show in game.

### ISSUE THREAD

**Issue by l33tlinuxh4x0r** [benbaptist/minecraft-wrapper#547]
I was running version 1.12.2 and picked up some seeds. When I threw them on the ground they did not appear in game however when I walked over where they should have been I picked them up. Also If I try the same thing on the same server using the non proxy mode port I everything functions as normal.

**Comment by l33tlinuxh4x0r** [comment]
I have issued a Pull request that fixes this issue. Please review.

**Comment by suresttexas00** [comment]
I believe it is you other fix that corrects this since that permission has no use in proxy code.

.. but i will look into it, as I have also noted this behaviour.

**Comment by suresttexas00** [comment]
See my notes on the last PR for other "known issues" I have slated to fix in the next week.

**Comment by suresttexas00** [comment]
This one is a real bug I have noticed too.  It is not related to the permission.  It is probably an error in the proxy/server or proxy/client parses.

**Comment by suresttexas00** [comment]
I believe I have this fixed.   I believe our clientconnection.py and serverconnection.py flush() time.sleep times were too short.  Will have a build shortly that corrected it on my system.  Let me know how it does for you.. of course it's not snapshot version, just 1.12.2
