### ISSUE TITLE
Wrapper.py has unreadable code

### ISSUE THREAD

**Issue by githubl0ver69** [benbaptist/minecraft-wrapper#599]
I'm assuming that everything is in the wrapper.py so excuse me if I'm wrong. But how come I can't edit the file? I basically want to tweak things, add things, etc.

**Comment by suresttexas00** [comment]
Wrapper.py is not the source code: 
https://github.com/benbaptist/minecraft-wrapper#start-up

**Comment by suresttexas00** [comment]
You open Wrapper.py with a zip file type program.  It is an archive file containing the actual python files.
