### ISSUE TITLE
Build 72 breaks help

### ISSUE THREAD

**Issue by suresttexas00** [benbaptist/minecraft-wrapper#63]
/help now produces:
![image](https://cloud.githubusercontent.com/assets/10001762/5706906/92568668-9a52-11e4-94c3-2422f879762d.png)

I think it would be helpful to keep the former ability to optionally register one's own version of /help.

**Comment by benbaptist** [comment]
Wait a moment - I thought I commented out the code for /help.

**Comment by benbaptist** [comment]
Just pushed #74 which should actually remove the code temporarily. I also need to remember to allow registerCommand() to actually override Wrapper commands.
