### ISSUE TITLE
minecraft.getplayer() not working

### ISSUE THREAD

**Issue by suresttexas00** [benbaptist/minecraft-wrapper#65]
```
[18:25:28] [Wrapper.py/INFO] Server started
[18:25:34] [Wrapper.py/INFO] Minecraftboy2019 logged in (UUID: 54880482-2b03-47e
5-a268-8290fd1e0b46 | IP: 184.18.6.142)
[18:25:34] [Wrapper.py/INFO] SurestTexas00 logged in (UUID: 4f953255-6775-4dc6-a
612-fb4230588eff | IP: 184.18.6.142)
[18:25:34] [Server thread/INFO]: Minecraftboy2019[/127.0.0.1:50589] logged in wi
th entity id 86 at (-5.929453122828301, 67.5, 59.2162825799223)
[18:25:34] [Server thread/INFO]: Minecraftboy2019 joined the game
[18:25:34] [Server thread/INFO]: SurestTexas00[/127.0.0.1:50590] logged in with
entity id 203 at (-4.662569043032987, 64.0, 56.53559989959318)
[18:25:34] [Server thread/INFO]: SurestTexas00 joined the game
[18:25:57] [Wrapper.py/INFO] SurestTexas00 executed: /tell Minecraftboy2019 yo mayn
[18:25:57] [Wrapper.py/ERROR] Plugin 'com.suresttexas00.plugins.simple' errored
out when executing command: '<SurestTexas00> /{'callback': <bound method Main._t
ell of <simple.Main instance at 0x02F39E18>>, 'permission': None}':
[18:25:57] [Wrapper.py/ERROR] Traceback (most recent call last):
[18:25:57] [Wrapper.py/ERROR]   File "C:\Users\JRUSSELL\Desktop\vanilla\Wrapper\
__main__.py", line 420, in playerCommand
[18:25:57] [Wrapper.py/ERROR]     command["callback"](payload["player"], payload
["args"])
[18:25:57] [Wrapper.py/ERROR]   File "wrapper-plugins\simple.py", line 247, in _
tell
[18:25:57] [Wrapper.py/ERROR]     if self.minecraft.getPlayer(targetname) == oth
erplayer:
[18:25:57] [Wrapper.py/ERROR] AttributeError: Main instance has no attribute 'mi
necraft'
[18:25:57] [Wrapper.py/ERROR]
```

Here is the plugin code:

	def _tell(self, player, args):
		# check to make sure there are arguments
		if len(args) <= 1:
			player.message({"text": "Usage: /tell <player> <private message ...>", "color": "red"})
			return
		#set some variables
		otherplayer = args[0]
		mess = ""
		for index in range(len(args)-1):
			mess = mess + args[index+1] + " "
		mess = mess.replace("\"","'")
		#Error checking for not self
		if otherplayer == player.username:
			player.message({"text": "You can't send a private message to yourself!", "color": "red"})
			return
		#Error checking for valid otherplayer
		playeron = False
		targetisOp = False

Line 247 --->		**for targetname in self.api.minecraft.getPlayers():**

			if self.minecraft.getPlayer(targetname) == otherplayer:
				playeron = True
				if self.minecraft.getPlayer(targetname).isOp():
					targetisOp = True

**Comment by benbaptist** [comment]
If I'm not mistaken, it looks like you don't have `self.minecraft =
api.minecraft` in the __init__ method. Or you could just do
self.api.minecraft.getPlayer (the long way).

**Comment by suresttexas00** [comment]
I think this is related to 
https://github.com/benbaptist/minecraft-wrapper/issues/61

**Comment by suresttexas00** [comment]
It's true, I don't.  Actually, all I have is:

	def __init__(self, api, log):
		self.api = api
		self.log = log

yet these commands seem to work fine:
self.minecraft.console("")
player.message("")

Why would those commands work, but not this one?

**Comment by suresttexas00** [comment]
It appears to not error out, but I am getting an unexpected result:

		#Error checking for valid otherplayer
		playeron = False
		for targetname in self.api.minecraft.getPlayers():
			if self.api.minecraft.getPlayer(targetname) == otherplayer:
				player.message("player on is true")
				playeron = True


player on never becomes true, even though both players are on, and I am using the m.c. autocomplete of the name in question.

**Comment by suresttexas00** [comment]
turns out in this code
        if self.minecraft.getPlayer(targetname) == otherplayer:
            playeron = True
            if self.minecraft.getPlayer(targetname).isOp():
                targetisOp = True

I actually have to str() self.minecraft.getPlayer(targetname) and otherplayer.  Otherwise, the comparison returns false

**Comment by benbaptist** [comment]
player.message works because player is usually defined by the arguments
passed to the function. Are you 100% sure self.minecraft.console works?

[This message was delayed due to bad connectivity.]

It's true, I don't. Actually, all I have is:

def __init__(self, api, log):
    self.api = api
    self.log = log

yet these commands seem to work fine:
self.minecraft.console("")
player.message("")

Why would those commands work, but not this one?

--
Reply to this email directly or view it on GitHub
<https://github.com/benbaptist/minecraft-wrapper/issues/65#issuecomment-69847798>
.

**Comment by suresttexas00** [comment]
No I am not sure anymore because I changed everything to self.api.
However, this explains why player.message() did not work in the "def onEnable(self):", yet worked in the other functions :)
