### ISSUE TITLE
How do you...

### ISSUE THREAD

**Issue by suresttexas00** [benbaptist/minecraft-wrapper#68]
Can you hide someone (i.e., the OP) from the tabbed player list?

**Comment by overjt** [comment]
1)
```
	def __init__(self, api, log):
		self.api = api
		self.minecraft = api.minecraft
		self.log = log

	def onEnable(self):
		self.api.registerCommand("hideuser",self.hideUser)

	def hideUser(self,player, args):
		if len(args) == 1:
			playersOnline = self.minecraft.getPlayers()
			if args[0] in playersOnline:
				playerUuid = playersOnline[args[0]].uuid
				for playerO in playersOnline:
					self.minecraft.getPlayer(playerO).client.send(0x38, "varint|varint|uuid",(4,1,playerUuid))
			else:
				player.message("&c"+ args[0] + " is not online")
		else:
			player.message("&c/hideuser username")

```

This sends a packet to each connected user:
```
for playerO in playersOnline:
    self.minecraft.getPlayer(playerO).client.send(0x38, "varint|varint|uuid",(4,1,playerUuid))
```

More info about minecraft protocol: http://wiki.vg/Protocol#Player_List_Item

**Comment by suresttexas00** [comment]
Thanks!
  
    
    
  
  
 		 	   		  =

**Comment by suresttexas00** [comment]
Well, that works for about as long as the player is on the server.  Once his client logs off and then back on, he can see you again.  Also, of course, the player still shows in the server player count when you hover over it (before logging in).

I tried to do something like:

	def playerLogin(self, payload):
		#hide hiddenplayers
		hiddenplayers = self.container["hiddenplayers"]
		for playerO in hiddenplayers: 
			playerUuid = hiddenplayers[playerO].uuid
			payload["player"].client.send(0x38, "varint|varint|uuid",(4,1,playerUuid))

**Comment by suresttexas00** [comment]
ok, well I think this might not be working because I did not write the code to place the hidden player in "hiddenplayers" ! LOL

**Comment by suresttexas00** [comment]
We'll not even talk about how wrong all that was... coding-wise.. Still interested in how to hide the playerlist from the server list.

**Comment by suresttexas00** [comment]
I should separate these questions...

**Comment by suresttexas00** [comment]
I can't tell from the chart how this gets configured.
can you give me an example on how a "0 (ADD_PLAYER)" would work?  I can't tell from this document what order the fields are supposed to be in or how many,etc.. I just end up disconnecting all my players I send the packet to D:

Packet ID	Category	Bound To	Field Name	Field Type	Notes
0x38	Play	Client	Action	VarInt	
Length	VarInt	The following fields are repeated length times
UUID	UUID	The uuid of the player
Action	
0 (ADD_PLAYER)	Name	String	
Number of properties	VarInt	
Properties	Name	String	
Value	String	
Is Signed	Boolean	
Signature	String	Only if Is Signed is true
Gamemode	VarInt	
Ping	VarInt	
Has Display Name	Boolean	
Display Name	Chat	Only send if Has Diplay Name is true
1 (UPDATE_GAMEMODE)	Gamemode	VarInt	
2 (UPDATE_LATENCY)	Ping	VarInt	
3 (UPDATE_DISPLAY_NAME)	Has Display Name	Boolean	
Display Name	Chat	Only send if Has Diplay Name is true
4 (REMOVE_PLAYER)

**Comment by suresttexas00** [comment]
let me be more specific:
I know the first field varint is the action.  In my case, I want to be able to "re-appear"; so I use `0` (ADD_PLAYER)..
now it gets hairy for me...
- Field named length... I don't know what goes here.  the text note "The following fields are repeated length times" does not seem to clear this up for me... the only following field I see is UUID
- ADD_PLAYER seems to have a whole bunch of extra stuff related to it.   Where do these data items go? (are they additional fields or part of the same field?) If additional fields, where do they fit in? (after the UUID, after the length, etc..)

not sure what is supposed to go in fields like "ping" or "chat" either :(
