### ISSUE TITLE
"blah blah"  is not JSON serializable

### ISSUE THREAD

**Issue by suresttexas00** [benbaptist/minecraft-wrapper#75]
What does it mean sometihng is not JSON serializable? This happens whenever i do something like:

			playerUuid = player.uuid
			humanname = str([player.username])
			self.container["hiddenplayers"][humanname] = playerUuid

```
Traceback (most recent call last):
  File "C:\Python27\lib\threading.py", line 810, in __bootstrap_inner
    self.run()
  File "C:\Python27\lib\threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "Wrapper\storage.py", line 39, in periodicSave
    self.save()
  File "Wrapper\storage.py", line 56, in save
    f.write(json.dumps(self.data))
  File "C:\Python27\lib\json\__init__.py", line 243, in dumps
    return _default_encoder.encode(obj)
  File "C:\Python27\lib\json\encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Python27\lib\json\encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "C:\Python27\lib\json\encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
  TypeError: UUID('4f953255-6775-4dc6-a612-fb4230588eff') is not JSON serializable
```
this seems to be happening when it attempts to save to disk

**Comment by benbaptist** [comment]
You're trying to put a variable type into the storage that isn't one of the traditional variable types (i.e. strings, integers/numbers, lists, dictionaries, etc.), but rather special things like classes, functions, etc.

In this case, you're not trying to store a UUID string - you're trying to store the UUID class itself from the UUID module. That cannot be saved, and thus it causes this error. To fix this, put str() around player.uuid. It needs to be converted to an actual string before it can be saved to disk.

**Comment by suresttexas00** [comment]
If I do that, will I get a string of :
 `UUID('4f953255-6775-4dc6-a612-fb4230588eff')`
 or `'4f953255-6775-4dc6-a612-fb4230588eff'`

**Comment by suresttexas00** [comment]
suppose I will find out..

**Comment by benbaptist** [comment]
You will get 4f953255-6775-4dc6-a612-fb4230588eff. Inside of the UUID class, they defined an internal function called __str__. When someone tries to str() their class, it'll call __str__ and whatever __str__ returns, is what the string is made from. Because of that, in this case, it's smart enough to know '4f953255-6775-4dc6-a612-fb4230588eff' is what should be returned, not anything weird like UUID('4f953255-6775-4dc6-a612-fb4230588eff').
