### ISSUE TITLE
hide console chat

### ISSUE THREAD

**Issue by suresttexas00** [benbaptist/minecraft-wrapper#76]
how do you hide a specific console output from players.. like "\<OPname\> joined the game"

**Comment by benbaptist** [comment]
By registering the player.chatbox event, checking the contents of the message (which is stored in the JSON chat format, e.g. {text:"Ohai! This is yellow.",color:yellow,extra:[{text:" This is red.", color:red}]} and returning False to stop it from appearing on the client's side.
