### ISSUE TITLE
permissions

### ISSUE THREAD

**Issue by suresttexas00** [benbaptist/minecraft-wrapper#79]
So, up to this point, I have avoided permissions and did everything on an OP/not-OP basis.  So I have a few questions about how this should be implemented.  I see permissions "used" in the examples, but they seem to assume the user already has/does not have the nodes.

how do you "assign" permissions and where are they stored??  Do I need to create a new container with usernames/uuids and their permissions or is this done already in wrapper?

**Comment by benbaptist** [comment]
This is already performed in the Wrapper itself - the /permissions command can be used to modify permissions (or /perms, /perm, and /super as aliases)

By default, nobody has permissions and if your command requires a permission, it won't work unless they are assigned that particular permission/have all permissions (e.g. a wildcard). If you want a permission to be allowed by everyone by default, then you can use api.setPermission("permission.node", True) to explicity set it to true by default. Then, if the user wants to forbid that command from being run by regular users, they can "add" the permission "-permission.node" to the default group (with the minus sign). 

Also, permissions can be more than just True and False - they can be full strings. As long as it's not False, it'll allow the command to be run. You can use player.hasPermission("permission.node") to return the contents of that node (e.g. True/False or the string).

**Comment by suresttexas00** [comment]
I cant use `api.setPermission("permission.node", True)`
if i use `self.api.setPermission("permission.node", True)` wrapper says "api instance has no attribute setPermission"

if i use `api.setPermission("permission.node", True)` it says "global name api is not defined"

Where in the code would this go?  I was attempting to use it in the "onEnable" section....

**Comment by suresttexas00** [comment]
yes, i was using my own permission node.

**Comment by benbaptist** [comment]
Sorry, the way I do things sometimes is a bit confusing. I cut off 'self' just for the sake of quickly typing it out, but in general you usually want to type self.api for most stuff.

Also, I'm an idiot - it's actually self.api.registerPermission, not setPermission. My bad. :P

**Comment by suresttexas00** [comment]
I want to remove a particular player's ability to use commands that are provided by default under the  players.home permission...

I.e. I want the code to do what would be a manually entered command:
`/perms users minecraftplayer01 set players.home False`

I noted that I cannot just `self.api.minecraft.console` this command...
