### ISSUE TITLE
Help printout and permissions

### ISSUE THREAD

**Issue by suresttexas00** [benbaptist/minecraft-wrapper#83]
I don't think the permission nodes should be part of the help file printout.  It's unneeded clutter and the actual nodes only need be known by the ops/admins.

I DO think the permissions should be used to determine whether a particular command prints out.  Just as the default minecraft commands do not print out things like "clone" and "gamemode" when printing the help for non-op players.

**Comment by benbaptist** [comment]
Good idea. Will put this on the to-do.
