### ISSUE TITLE
Permissions error?

### ISSUE THREAD

**Issue by suresttexas00** [benbaptist/minecraft-wrapper#91]
Just noticed that on my system, the permissions.py does not create a run-time permissions.pyc file.. usually that means there is some kind of (syntax) error that it can create the pyc file...
![image](https://cloud.githubusercontent.com/assets/10001762/5850956/89242bdc-a1cc-11e4-9c4b-bf6d7f69f53e.png)

**Comment by suresttexas00** [comment]
Fyi, I DO run the source code directly (just rename src folder to wrapper).. so the picture is of the src folder contents after startup.

**Comment by benbaptist** [comment]
Oh, that's fine - I actually don't use permissions.py, oddly enough. All of the code for permissions is either in __main__ or somewhere in the api folder. I mostly put the permissions.py file there to remind me to organize the code a bit more and move some of the code into there, as it should be.
