### ISSUE TITLE
Excessive padding

### ISSUE THREAD

**Issue by suresttexas00** [benbaptist/minecraft-wrapper#96]
This probably should not be in here because it will unnecessarily flush 20 lines of chat history.

```
					for i in range(20):
						player.message(" ") # Padding, for the sake of making it look a bit nicer
```

**Comment by suresttexas00** [comment]
There is still another instance of this in line 310 of `__Main__.py`

**Comment by benbaptist** [comment]
Whoops - I thought I caught all of them. I guess that'll have to go in the 0.7.7 patches.

**Comment by suresttexas00** [comment]
OK
