### ISSUE TITLE
Web mode and Pkg_resources

### ISSUE THREAD

**Issue by suresttexas00** [benbaptist/minecraft-wrapper#97]
I thought this was only needed for memory usage functions..

```
			else:
				self.log.error("Web remote could not be started because you do not have the required modules installed: pkg_resources")
				self.log.error("Hint: http://stackoverflow.com/questions/7446187")
```

**Comment by benbaptist** [comment]
No, that was the 'resource' module. pkg_resources has always been a dependency for web mode, for extracting the HTML and other files out of the 'html' folder.

**Comment by benbaptist** [comment]
It appears the documentation was changed and was not written properly - I will fix that.

**Comment by suresttexas00** [comment]
Nooooo......  :'(   Resource was a part of the Pkg_resources and it will not install or does not come with the windows... we went through this before...

```
Windows PowerShell
Copyright (C) 2013 Microsoft Corporation. All rights reserved.

C:\Users\JRUSSELL\Documents\GitHub> pip install pkg_resources
Downloading/unpacking pkg-resources
  Real name of requirement pkg_resources is pkg-resources
  Could not find any downloads that satisfy the requirement pkg-resources
Cleaning up...
No distributions at all found for pkg-resources
Storing debug log for failure in C:\Users\JRUSSELL\pip\pip.log
C:\Users\JRUSSELL\Documents\GitHub>
```
This statement is correct:
```Wrapper.py doesn't require any special modules for most of the basic features to work, but web mode and proxy mode require requests and pycrypto. On Linux, the Memory usage features (/mem) will require pkg_resources. This function is not available on Windows platforms.```

If I am wrong, please explain how I can get pkg_resources to install...

**Comment by suresttexas00** [comment]
how do I use web mode?  I have set a password and enabled it in the wrapper.properties:
```
[Web]
web-enabled = True
web-bind = 0.0.0.0
web-port = 8070
web-password = J1m2sr5ss
public-stats = True
web-allow-file-management = False
```

**Comment by suresttexas00** [comment]
I changed it to 127.0.0.1

and now I am this far:
![image](https://cloud.githubusercontent.com/assets/10001762/5988740/2c0b76b4-a93b-11e4-93a4-fa495a627e00.png)

if I click the link I get a 404 page not found error...

**Comment by benbaptist** [comment]
The IP should be set to 0.0.0.0 if you want it to be accessible from
outside of your computer. You can still do 127.0.0.1:8070 or localhost:8070
from inside of your browser.

The 404 must be a result of not having pkg_resources OR if you fixed that,
then maybe another bloody Windows bug. Icwoudlnt be surprised if it wanted
me to use backslashes \ instead of regular slashes / for finding the path.

**Comment by suresttexas00** [comment]
Yes, I'm trying to access it LOCAL only first.. don't want any www exposure until I know what i am doing.
you are probably right about the slashes.. i'll test that

**Comment by suresttexas00** [comment]
and no luck with pkg-resources.  Ever.. ever.. and I googled the crap out of it.

**Comment by suresttexas00** [comment]
so is that link i see above generated by wrapper or is that some sort of default for accessing that port?

**Comment by benbaptist** [comment]
Yes, that was generated by Wrapper. But IIRC it is hard coded into the code
and isn't an actual .HTML hence why it probably worked fine without pkg
resources.

**Comment by suresttexas00** [comment]
its weird, i can find a "pkg_resources.py" file in the Libs folder of python27... i am trying a fix that involves moving it to another directory...

**Comment by suresttexas00** [comment]
The problem is with my version of pkg-resources... it has some bad references like:

`from urllib.parse import urlparse, urlunparse` and 
`import importlib._bootstrap as importlib_bootstrap`

**Comment by suresttexas00** [comment]
never mind.. those are only activated for py v3 files

**Comment by suresttexas00** [comment]
what version of setuptools are you using?  Evidently, pkg_resources is a "subset" of setuptools and not its own pip installable resource...

**Comment by suresttexas00** [comment]
TURNS OUT; that pkg resources is installed and working (I don't get the error message about it not being installed)... However, I still get the "404 - not found" error, but now for the weird part...

JUST AFTER I CLICK THE LINK and JUST BEFORE I get the 404 error, something was flashing on the page.  I took slow motion video of it on my iPhone and I discovered that a web page flashes real quickly and has the following items:
```[Toggle navigation] Wrapper.py

- Dashboard
- Server
- Plugins
- About

-Logout
.... and goes on.
```

**Comment by suresttexas00** [comment]
according to VS, there are errors in the admin.html at line 587, 588... and 413 (or so)
it does not like the 
```
								<th>Face</th><th>Username</th><th>UUID</th><th>Options</th></tr>
							</tbody>
```
it's making green squiggle marks under the `/tr`, some of the `/th`s and under the `/tbody`

**Comment by suresttexas00** [comment]
read the preceding comment first because that is more important.  This is just FYI - Pkg_resources is a part of setuptools and does not need a separate installation.  However, for windows, some additions to the PATH may be needed to get it to see it... imma guessin' ....  Got it to work, though.

**Comment by suresttexas00** [comment]
I found the problem.  The web page is attempting to send me from admin.html to login.html.. which does not exist in the source code (which I am running directly from the /src folder)...

**Comment by suresttexas00** [comment]
As a matter of fact, it seems to require quite a bit of stuff in this folder that is not in the source to work properly.... however, now that it's working.. OOOoo had no idea this was so fancy!! :D

**Comment by benbaptist** [comment]
Oh. My git setup has issues when it comes to pushing all of the right
files. I'll have to fix that.

**Comment by benbaptist** [comment]
My recommendation is to extract the "HTML" folder from the latest
Wrapper.py itself and drop that in there.

**Comment by benbaptist** [comment]
Oh! Just read your latest posts. Dang email being out of order :P. Yay, awesome that it is working. Indeed it is fancy :D

**Comment by suresttexas00** [comment]
yea, I've stopped replying from the emails and reply directly on github..
