### ISSUE TITLE
Player can /wrapper halt

### ISSUE THREAD

**Issue by suresttexas00** [benbaptist/minecraft-wrapper#98]
Should be an `if player.isOp()` here!

```
		if payload["command"] == "wrapper":
			player = payload["player"]
			buildString = self.getBuildString()
			if len(args(0)) > 0:
				subcommand = args(0)
				if subcommand == "update":
					player.message({"text": "Checking for new Wrapper.py updates...","color":"yellow"})
					update = self.checkForNewUpdate()
```

**Comment by benbaptist** [comment]
Holy crap, seriously!? That's a crucial update. I will get on my laptop
when I arrive at my destination and release a quick fix.

Wait, why did you close it? False alarm?

**Comment by suresttexas00** [comment]
I have the patch pull request already awaiting your approval!  (why i closed this)

**Comment by suresttexas00** [comment]
I closed the one patch because I made it patch to the master release.  The correct pull request for the development version is not in this thread... but it is in your pull requests.

**Comment by suresttexas00** [comment]
BY the say, if you are going to patch the release version, consider adding my pull request to fix the backups.py as well :D

**Comment by benbaptist** [comment]
Ah, okay! Let me slowly navigate my way over on 1X speeds. :P
